"""Shared pytest fixtures for Labeled Features tests.

Provides sys.modules stubs for the homeassistant symbols the package
__init__ pulls in, so pure-logic tests can run without a full HA install.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import sys
import types
from pathlib import Path

# Make the repo root importable so `custom_components.labeled_features` resolves.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))


def _install_ha_stubs() -> None:
    """Install just-enough `homeassistant.*` stubs for import-time symbols."""
    try:
        import homeassistant  # noqa: F401
        return  # Real HA is installed; no stubs needed.
    except ImportError:
        pass

    def _ns(name: str) -> types.ModuleType:
        mod = types.ModuleType(name)
        sys.modules[name] = mod
        return mod

    ha = _ns("homeassistant")
    _ns("homeassistant.config_entries")
    _ns("homeassistant.const")
    _ns("homeassistant.core")
    _ns("homeassistant.helpers")
    _ns("homeassistant.helpers.entity_platform")
    _ns("homeassistant.helpers.restore_state")
    _ns("homeassistant.helpers.entity_registry")
    _ns("homeassistant.helpers.area_registry")
    _ns("homeassistant.helpers.floor_registry")
    _ns("homeassistant.helpers.label_registry")
    _ns("homeassistant.helpers.device_registry")
    _ns("homeassistant.helpers.issue_registry")
    _ns("homeassistant.helpers.config_validation")
    _ns("homeassistant.helpers.selector")
    _ns("homeassistant.util")
    _ns("homeassistant.util.dt")
    _ns("homeassistant.components")
    _ns("homeassistant.components.sensor")

    # Populate the symbols referenced at import time.
    ce = sys.modules["homeassistant.config_entries"]
    ce.ConfigEntry = type("ConfigEntry", (), {})
    ce.ConfigFlowResult = dict

    class _ConfigFlow:
        def __init_subclass__(cls, **kwargs):  # noqa: D401
            pass

    ce.ConfigFlow = _ConfigFlow
    ce.OptionsFlow = type("OptionsFlow", (), {})

    core = sys.modules["homeassistant.core"]
    core.HomeAssistant = type("HomeAssistant", (), {})
    core.Event = type("Event", (), {})
    core.State = type("State", (), {})
    core.ServiceCall = type("ServiceCall", (), {})

    def _callback(fn):
        return fn

    core.callback = _callback

    const = sys.modules["homeassistant.const"]
    const.EVENT_HOMEASSISTANT_START = "homeassistant_start"

    class _Platform:
        SENSOR = "sensor"

    const.Platform = _Platform

    sensor_mod = sys.modules["homeassistant.components.sensor"]
    sensor_mod.SensorEntity = type("SensorEntity", (), {})

    class _SensorStateClass:
        MEASUREMENT = "measurement"

    sensor_mod.SensorStateClass = _SensorStateClass

    rs = sys.modules["homeassistant.helpers.restore_state"]
    rs.RestoreEntity = type("RestoreEntity", (), {})
    rs.ExtraStoredData = type("ExtraStoredData", (), {})

    ir = sys.modules["homeassistant.helpers.issue_registry"]

    def _noop(*args, **kwargs):
        return None

    ir.async_create_issue = _noop
    ir.async_delete_issue = _noop

    class _IssueSeverity:
        ERROR = "error"
        WARNING = "warning"

    ir.IssueSeverity = _IssueSeverity

    cv = sys.modules["homeassistant.helpers.config_validation"]
    cv.string = str
    cv.boolean = bool

    sel = sys.modules["homeassistant.helpers.selector"]

    def _passthrough_cls(name):
        return type(name, (), {})

    sel.SelectSelector = lambda cfg: cfg
    sel.SelectSelectorConfig = dict
    sel.SelectSelectorMode = types.SimpleNamespace(DROPDOWN="dropdown")

    dt = sys.modules["homeassistant.util.dt"]

    import datetime as _dt

    def _now():
        return _dt.datetime.now(_dt.timezone.utc)

    dt.now = _now
    dt.utcnow = _now

    er = sys.modules["homeassistant.helpers.entity_registry"]
    er.EntityRegistry = type("EntityRegistry", (), {})
    er.async_get = lambda hass: types.SimpleNamespace(entities={}, async_get=lambda eid: None)

    ar = sys.modules["homeassistant.helpers.area_registry"]
    ar.async_get = lambda hass: types.SimpleNamespace(async_get_area=lambda aid: None, async_list_areas=lambda: [])

    fr = sys.modules["homeassistant.helpers.floor_registry"]
    fr.async_get = lambda hass: types.SimpleNamespace()

    lr = sys.modules["homeassistant.helpers.label_registry"]
    lr.async_get = lambda hass: types.SimpleNamespace(async_list_labels=lambda: [], async_get_label=lambda lid: None)

    dr_mod = sys.modules["homeassistant.helpers.device_registry"]
    dr_mod.async_get = lambda hass: types.SimpleNamespace(async_get=lambda did: None)

    ep = sys.modules["homeassistant.helpers.entity_platform"]
    ep.AddEntitiesCallback = type("AddEntitiesCallback", (), {})


_install_ha_stubs()
