"""Tests for the label parser.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import pytest

from custom_components.labeled_features.label_parser import (
    has_decreasing,
    has_increasing,
    has_invert,
    match_disable,
    match_enable,
    parse_component_override,
    parse_leader_label,
    parse_mode_label,
    parse_provides_label,
    scope_prefix,
)


class TestParseLeader:
    def test_bare_leader_is_global(self):
        assert parse_leader_label("Leader: Night") == ("global", "Night")

    def test_area_leader(self):
        assert parse_leader_label("Area Leader: Screen") == ("area", "Screen")

    def test_floor_leader(self):
        assert parse_leader_label("Floor Leader: Night") == ("floor", "Night")

    def test_case_sensitive_keyword(self):
        assert parse_leader_label("leader: Night") is None
        assert parse_leader_label("Area leader: Night") is None

    def test_case_sensitive_feature(self):
        # Lowercase feature is accepted verbatim as the feature name.
        assert parse_leader_label("Leader: night") == ("global", "night")

    def test_non_leader_label(self):
        assert parse_leader_label("Feature Leader") is None
        assert parse_leader_label("Area Follower: Night") is None

    def test_empty_feature_rejected(self):
        assert parse_leader_label("Leader: ") is None


class TestParseProvides:
    def test_bare_provides_is_none_scope(self):
        assert parse_provides_label("Provides: Audio Mode") == ("none", "Audio Mode")

    def test_area_provides(self):
        assert parse_provides_label("Area Provides: Media Player") == (
            "area",
            "Media Player",
        )

    def test_floor_provides(self):
        assert parse_provides_label("Floor Provides: Night") == ("floor", "Night")

    @pytest.mark.parametrize(
        "kw",
        ["Component", "Min", "Max", "Step", "Unit", "Icon", "Initial", "Mode", "Device Class"],
    )
    def test_modifier_labels_filtered(self, kw):
        assert parse_provides_label(f"Area Provides: Audio Mode {kw}: foo") is None

    def test_provides_option_not_a_provides(self):
        # "Provides Option: <F>" doesn't match "Provides: <F>" — different pattern.
        assert parse_provides_label("Area Provides Option: Audio Mode") is None


class TestParseMode:
    def test_bare_mode_is_global(self):
        assert parse_mode_label("Night Mode: All") == ("global", "Night", "all")

    def test_area_mode(self):
        assert parse_mode_label("Area Screen Mode: Leader") == ("area", "Screen", "leader")

    def test_floor_mode(self):
        assert parse_mode_label("Floor Night Mode: Any") == ("floor", "Night", "any")

    def test_case_sensitive_values(self):
        # `Mode:` value is case-sensitive on the label side (Leader|Any|All);
        # anything else fails to parse.
        assert parse_mode_label("Night Mode: leader") is None
        assert parse_mode_label("Night Mode: ALL") is None


class TestParseComponentOverride:
    def test_area_component(self):
        assert (
            parse_component_override(
                "Area Provides Audio Mode Component: select",
                "Audio Mode",
                "Area ",
            )
            == "select"
        )

    def test_wrong_prefix_returns_none(self):
        assert (
            parse_component_override(
                "Floor Provides Audio Mode Component: select",
                "Audio Mode",
                "Area ",
            )
            is None
        )

    def test_wrong_feature_returns_none(self):
        assert (
            parse_component_override(
                "Area Provides Other Component: select",
                "Audio Mode",
                "Area ",
            )
            is None
        )


class TestModifierMatchers:
    def test_match_enable(self):
        assert match_enable("Area Night Enable: playing", "Night", "Area ") == "playing"

    def test_match_enable_wrong_prefix(self):
        assert match_enable("Floor Night Enable: playing", "Night", "Area ") is None

    def test_match_disable(self):
        assert match_disable("Screen Disable: off", "Screen", "") == "off"

    def test_has_invert(self):
        assert has_invert(["Area Night Invert: True"], "Night", "Area ") is True
        # Case-sensitive True
        assert has_invert(["Area Night Invert: true"], "Night", "Area ") is False

    def test_has_increasing_decreasing(self):
        assert has_increasing(["Screen Increasing: True"], "Screen", "") is True
        assert has_decreasing(["Screen Decreasing: True"], "Screen", "") is True
        assert has_increasing([], "Screen", "") is False


class TestScopePrefix:
    def test_scope_prefixes(self):
        assert scope_prefix("area") == "Area "
        assert scope_prefix("floor") == "Floor "
        assert scope_prefix("global") == ""
        assert scope_prefix("none") == ""
