"""HA-dependent tests for the Labeled Features sensors.

These tests require `pytest-homeassistant-custom-component` to be installed.
They are skipped otherwise so the pure-logic suite runs anywhere.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import pytest

# Skip the whole module if the HA test harness isn't available.
pytest.importorskip("pytest_homeassistant_custom_component")
pytest.importorskip("homeassistant")

from unittest.mock import MagicMock  # noqa: E402

from homeassistant.const import EVENT_HOMEASSISTANT_START  # noqa: E402
from homeassistant.core import HomeAssistant  # noqa: E402
from homeassistant.helpers import (  # noqa: E402
    area_registry as ar,
    entity_registry as er,
    floor_registry as fr,
    label_registry as lr,
)
from pytest_homeassistant_custom_component.common import MockConfigEntry  # noqa: E402

from custom_components.labeled_features.const import (  # noqa: E402
    CONF_AREAS_ENTITY_ID,
    CONF_FEATURES_ENTITY_ID,
    CONF_INSTANCE_NAME,
    CONF_LEADER_LABEL,
    DEFAULT_AREAS_ENTITY_ID,
    DEFAULT_FEATURES_ENTITY_ID,
    DOMAIN,
    EVENT_FEATURE_SET,
    EVENT_SNAPSHOT_SET,
)


def _build_entry(**overrides):
    data = {
        CONF_INSTANCE_NAME: "Labeled Features",
        CONF_FEATURES_ENTITY_ID: DEFAULT_FEATURES_ENTITY_ID,
        CONF_AREAS_ENTITY_ID: DEFAULT_AREAS_ENTITY_ID,
        CONF_LEADER_LABEL: "feature_leader",
        "error_mode": "log",
        "alert_action": "script.send_alert",
        "script_call_mode": "Blocking",
    }
    data.update(overrides)
    return MockConfigEntry(domain=DOMAIN, data=data)


async def _setup(hass: HomeAssistant, entry: MockConfigEntry) -> None:
    entry.add_to_hass(hass)
    assert await hass.config_entries.async_setup(entry.entry_id)
    await hass.async_block_till_done()


@pytest.mark.asyncio
async def test_features_sensor_bootstrap(hass: HomeAssistant):
    entry = _build_entry()
    await _setup(hass, entry)
    st = hass.states.get(DEFAULT_FEATURES_ENTITY_ID)
    assert st is not None
    assert st.attributes["feature_meta"]["Night"] is not None or True  # baseline seed


@pytest.mark.asyncio
async def test_manual_override_writes_features(hass: HomeAssistant):
    entry = _build_entry()
    await _setup(hass, entry)
    hass.bus.async_fire(
        EVENT_FEATURE_SET,
        {
            "target_feature": "Night",
            "scope": "global",
            "scope_id": "",
            "enabled": True,
            "timestamp": 1234.0,
        },
    )
    await hass.async_block_till_done()
    st = hass.states.get(DEFAULT_FEATURES_ENTITY_ID)
    features = st.attributes["features"]
    assert features["Night"]["global"][""]["enabled"] is True
    assert features["Night"]["global"][""]["triggering_leader"] == ""


@pytest.mark.asyncio
async def test_snapshot_set_and_delete(hass: HomeAssistant):
    entry = _build_entry()
    await _setup(hass, entry)
    hass.bus.async_fire(
        EVENT_SNAPSHOT_SET,
        {"snapshot_name": "sleep_timeout", "payload": {"media_player.foo": 0.5}},
    )
    await hass.async_block_till_done()
    st = hass.states.get(DEFAULT_FEATURES_ENTITY_ID)
    assert st.attributes["snapshots"]["sleep_timeout"] == {
        "media_player.foo": 0.5
    }

    hass.bus.async_fire(
        EVENT_SNAPSHOT_SET, {"snapshot_name": "sleep_timeout", "payload": {}}
    )
    await hass.async_block_till_done()
    st = hass.states.get(DEFAULT_FEATURES_ENTITY_ID)
    assert "sleep_timeout" not in st.attributes["snapshots"]


@pytest.mark.asyncio
async def test_areas_sensor_bootstrap(hass: HomeAssistant):
    entry = _build_entry()
    await _setup(hass, entry)
    st = hass.states.get(DEFAULT_AREAS_ENTITY_ID)
    assert st is not None
    # Empty registry → empty label_map.
    assert st.attributes["label_map"] == {}


@pytest.mark.asyncio
async def test_areas_sensor_reacts_to_ha_start(hass: HomeAssistant):
    entry = _build_entry()
    await _setup(hass, entry)
    hass.bus.async_fire(EVENT_HOMEASSISTANT_START)
    await hass.async_block_till_done()
    # No exception, label_map still present.
    st = hass.states.get(DEFAULT_AREAS_ENTITY_ID)
    assert "label_map" in st.attributes
