"""Tests for the per-leader truth evaluator.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import pytest

from custom_components.labeled_features.evaluator import (
    eval_leader_truth,
    fold_triple,
    resolve_mode,
)


class TestDefaultTruth:
    def test_state_equals_feature_name(self):
        # `input_select` on state 'Night' with `Leader: Night` label
        assert (
            eval_leader_truth(
                labels=[],
                domain="input_select",
                current_value="Night",
                previous_value="Day",
                feature="Night",
                scope="global",
            )
            is True
        )

    def test_state_equals_feature_name_is_case_sensitive(self):
        assert (
            eval_leader_truth(
                labels=[],
                domain="input_select",
                current_value="night",
                previous_value="Day",
                feature="Night",
                scope="global",
            )
            is False
        )

    @pytest.mark.parametrize(
        "cv", ["on", "true", "home", "open", "detected", "active", "unlocked", "ON", "TrUe"]
    )
    def test_truthy_strings(self, cv):
        assert (
            eval_leader_truth(
                labels=[],
                domain="binary_sensor",
                current_value=cv,
                previous_value="off",
                feature="OpenDoor",
                scope="area",
            )
            is True
        )

    def test_falsy_default(self):
        assert (
            eval_leader_truth(
                labels=[],
                domain="binary_sensor",
                current_value="off",
                previous_value="on",
                feature="OpenDoor",
                scope="area",
            )
            is False
        )

    def test_event_domain_always_true(self):
        assert (
            eval_leader_truth(
                labels=[],
                domain="event",
                current_value="1_short_release",
                previous_value="",
                feature="Night Buttons",
                scope="area",
            )
            is True
        )


class TestEnableDisable:
    def test_enable_match(self):
        assert (
            eval_leader_truth(
                labels=["Area Media Playing Enable: playing"],
                domain="media_player",
                current_value="playing",
                previous_value="idle",
                feature="Media Playing",
                scope="area",
            )
            is True
        )

    def test_enable_no_match(self):
        assert (
            eval_leader_truth(
                labels=["Area Media Playing Enable: playing"],
                domain="media_player",
                current_value="paused",
                previous_value="playing",
                feature="Media Playing",
                scope="area",
            )
            is False
        )

    def test_disable_only(self):
        # Only Disable: enabled == NOT (state matches disable value)
        assert (
            eval_leader_truth(
                labels=["Area Screen Disable: standby"],
                domain="media_player",
                current_value="on",
                previous_value="standby",
                feature="Screen",
                scope="area",
            )
            is True
        )
        assert (
            eval_leader_truth(
                labels=["Area Screen Disable: standby"],
                domain="media_player",
                current_value="standby",
                previous_value="on",
                feature="Screen",
                scope="area",
            )
            is False
        )


class TestDirection:
    def test_increasing_true(self):
        assert (
            eval_leader_truth(
                labels=["Screen Increasing: True"],
                domain="sensor",
                current_value="15",
                previous_value="10",
                feature="Screen",
                scope="global",
            )
            is True
        )

    def test_increasing_false(self):
        assert (
            eval_leader_truth(
                labels=["Screen Increasing: True"],
                domain="sensor",
                current_value="5",
                previous_value="10",
                feature="Screen",
                scope="global",
            )
            is False
        )

    def test_direction_wins_over_enable(self):
        # Direction takes precedence over Enable/Disable labels.
        assert (
            eval_leader_truth(
                labels=[
                    "Screen Increasing: True",
                    "Screen Enable: 5",
                ],
                domain="sensor",
                current_value="5",
                previous_value="10",
                feature="Screen",
                scope="global",
            )
            is False
        )

    def test_direction_non_numeric_is_false(self):
        assert (
            eval_leader_truth(
                labels=["Screen Increasing: True"],
                domain="sensor",
                current_value="hello",
                previous_value="10",
                feature="Screen",
                scope="global",
            )
            is False
        )


class TestInvert:
    def test_invert_after_default(self):
        assert (
            eval_leader_truth(
                labels=["Area Night Invert: True"],
                domain="binary_sensor",
                current_value="on",
                previous_value="off",
                feature="Night",
                scope="area",
            )
            is False
        )

    def test_invert_after_direction(self):
        assert (
            eval_leader_truth(
                labels=["Screen Increasing: True", "Screen Invert: True"],
                domain="sensor",
                current_value="15",
                previous_value="10",
                feature="Screen",
                scope="global",
            )
            is False
        )


class TestFoldTriple:
    def test_leader_mode_uses_first(self):
        assert fold_triple("leader", [True]) is True
        assert fold_triple("leader", [False]) is False
        # More than one value: leader still uses index 0.
        assert fold_triple("leader", [True, False]) is True

    def test_any_mode(self):
        assert fold_triple("any", [False, True, False]) is True
        assert fold_triple("any", [False, False]) is False

    def test_all_mode(self):
        assert fold_triple("all", [True, True]) is True
        assert fold_triple("all", [True, False]) is False

    def test_empty(self):
        assert fold_triple("any", []) is False
        assert fold_triple("all", []) is False


class TestResolveMode:
    def test_default_leader(self):
        assert resolve_mode([], "Night", "area") == "leader"

    def test_area_mode_label(self):
        assert (
            resolve_mode(["Area Night Mode: All"], "Night", "area") == "all"
        )

    def test_wrong_scope_ignored(self):
        # Floor-prefixed Mode label is ignored for an area-scoped query.
        assert (
            resolve_mode(["Floor Night Mode: All"], "Night", "area") == "leader"
        )

    def test_global_mode(self):
        assert resolve_mode(["Night Mode: Any"], "Night", "global") == "any"
