"""Tests for the error handler helper.

Uses HA fixtures when available; otherwise exercises the pure helpers.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from custom_components.labeled_features.error_handler import _issue_id


class TestIssueId:
    def test_deterministic(self):
        assert _issue_id("SourceA", "boom") == _issue_id("SourceA", "boom")

    def test_source_message_differ(self):
        assert _issue_id("SourceA", "boom") != _issue_id("SourceB", "boom")
        assert _issue_id("SourceA", "boom") != _issue_id("SourceA", "bang")

    def test_prefix(self):
        assert _issue_id("SourceA", "boom").startswith("component_error_")
