"""Labeled Features integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant, callback

from .const import (
    CONF_ALERT_ACTION,
    CONF_DEFAULT_ERROR_MODE,
    DEFAULT_ALERT_ACTION,
    DEFAULT_ERROR_MODE,
    DOMAIN,
)
from .coordinator import LabeledFeaturesCoordinator
from .error_mode import (
    ErrorModeHandler,
    async_register_error_mode_service,
    async_unregister_error_mode_service,
)
from .services import async_setup_services, async_unsetup_services

type LabeledFeaturesConfigEntry = ConfigEntry[LabeledFeaturesCoordinator]

_LOGGER = logging.getLogger(__name__)


async def async_setup_entry(
    hass: HomeAssistant, entry: LabeledFeaturesConfigEntry
) -> bool:
    """Set up Labeled Features from a config entry."""
    coordinator = LabeledFeaturesCoordinator(hass, entry)
    await coordinator.async_setup()
    entry.runtime_data = coordinator

    error_mode_handler = ErrorModeHandler(
        hass,
        entry.data.get(CONF_DEFAULT_ERROR_MODE, DEFAULT_ERROR_MODE),
        entry.data.get(CONF_ALERT_ACTION, DEFAULT_ALERT_ACTION),
    )
    entry.async_on_unload(entry.add_update_listener(_async_reload_entry))

    await async_setup_services(hass)
    await async_register_error_mode_service(hass, error_mode_handler)

    await hass.config_entries.async_forward_entry_setups(
        entry, [Platform.SENSOR]
    )

    return True


async def async_unload_entry(
    hass: HomeAssistant, entry: LabeledFeaturesConfigEntry
) -> bool:
    """Unload a config entry."""
    coordinator: LabeledFeaturesCoordinator = entry.runtime_data
    coordinator.async_unload()

    unload_ok = await hass.config_entries.async_unload_platforms(
        entry, [Platform.SENSOR]
    )
    if unload_ok:
        await async_unsetup_services(hass)
        await async_unregister_error_mode_service(hass)

    return unload_ok


@callback
async def _async_reload_entry(
    hass: HomeAssistant, entry: ConfigEntry
) -> None:
    """Reload config entry when options change."""
    await hass.config_entries.async_reload(entry.entry_id)