"""Labeled Features integration — core manager.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging
import re
from typing import Any, Callable

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import (
    Event,
    EventStateChangedData,
    HomeAssistant,
    callback,
)
from homeassistant.helpers import area_registry as ar
from homeassistant.helpers import entity_registry as er
from homeassistant.util import dt as dt_util

from .const import (
    CONF_ALERT_SCRIPT,
    CONF_ERROR_MODE_DEFAULT,
    DEFAULT_ERROR_MODE,
    DOMAIN,
    ENTRY_DATA_ALERT_SCRIPT,
    ENTRY_DATA_ERROR_MODE_DEFAULT,
    EVENT_LABELED_FEATURE_SET,
    EVENT_LABELED_FEATURE_SNAPSHOT_SET,
    FEATURE_META,
    MODIFIER_LABEL_PATTERN,
    SKIP_EVENT_SUFFIX,
    SUPPORTED_ERROR_MODES,
    TRUTHY_VALUES,
)
from .services import async_setup_services

_LOGGER = logging.getLogger(__name__)

# Regex for parsing leader labels
LEADER_RE = re.compile(r"^(Area |Floor |)Leader: (.+)$")
# Regex for parsing Provides labels
PROVIDES_RE = re.compile(r"^(Area |Floor |)Provides: (.+)$")


def _compute_floor_id(hass: HomeAssistant, area_id: str) -> str:
    """Compute the floor_id for a given area_id using the area registry."""
    area_reg = ar.async_get(hass)
    area = area_reg.areas.get(area_id)
    if area is None:
        return ""
    return area.floor_id or ""


class LabeledFeaturesManager:
    """Central manager for labeled features state.

    Replaces the Jinja2 template sensors with pure Python logic.
    All computation is done synchronously using registry lookups,
    matching the Jinja2 template behavior exactly.
    """

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry) -> None:
        """Initialize."""
        self.hass = hass
        self.entry = entry

        # Config values
        self._alert_script: str = entry.data.get(
            ENTRY_DATA_ALERT_SCRIPT, ""
        )
        self._error_mode_default: str = entry.data.get(
            ENTRY_DATA_ERROR_MODE_DEFAULT, DEFAULT_ERROR_MODE
        )

        # Internal state (mirrors sensor attributes)
        self._state_value: int = 0
        self._leaders: dict[str, dict[str, Any]] = {}
        self._features: dict[str, dict[str, dict[str, dict[str, Any]]]] = {}
        self._snapshots: dict[str, dict[str, Any]] = {}

        # Areas state
        self._areas_state_value: int = 0
        self._label_map: dict[str, dict[str, Any]] = {}

        # Event listeners
        self._listeners: list[Callable[[], None]] = []

        # Sensor update callbacks
        self._state_sensor_callbacks: list[Callable[[], None]] = []
        self._areas_sensor_callbacks: list[Callable[[], None]] = []

    @property
    def state_value(self) -> int:
        """Return the state value (count of feature_leader entities)."""
        return self._state_value

    @property
    def areas_state_value(self) -> int:
        """Return the areas state value (count of areas with feature_leader)."""
        return self._areas_state_value

    @property
    def attributes(self) -> dict[str, Any]:
        """Return the full attribute dict for LabeledFeaturesStateSensor."""
        return {
            "feature_meta": FEATURE_META,
            "leaders": dict(self._leaders),
            "features": self._deep_copy_dict(self._features),
            "snapshots": self._deep_copy_dict(self._snapshots),
        }

    @property
    def areas_attributes(self) -> dict[str, Any]:
        """Return the attribute dict for LabeledFeatureAreasStateSensor."""
        return {"label_map": self._deep_copy_dict(self._label_map)}

    def _deep_copy_dict(self, d: dict) -> dict:
        """Deep copy a dict for attribute serialization."""
        return self._deepcopy_helper(d)

    def _deepcopy_helper(self, obj: Any) -> Any:
        """Recursively copy an object (dict/list/primitives)."""
        if isinstance(obj, dict):
            return {k: self._deepcopy_helper(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [self._deepcopy_helper(item) for item in obj]
        return obj

    def get_alert_script(self) -> str:
        """Get the alert script entity_id (options override data)."""
        opts = self.entry.options.get(ENTRY_DATA_ALERT_SCRIPT, "")
        return opts if opts else self.entry.data.get(
            ENTRY_DATA_ALERT_SCRIPT, ""
        )

    def get_error_mode_default(self) -> str:
        """Get the default error mode (options override data)."""
        opts = self.entry.options.get(ENTRY_DATA_ERROR_MODE_DEFAULT, "")
        return opts if opts else self.entry.data.get(
            ENTRY_DATA_ERROR_MODE_DEFAULT, DEFAULT_ERROR_MODE
        )

    async def async_setup(self) -> None:
        """Set up event listeners and initial state."""
        await async_setup_services(self.hass)

        # Subscribe to events
        self._listeners.append(
            self.hass.bus.async_listen(
                "state_changed",
                self._on_state_changed,
            )
        )
        self._listeners.append(
            self.hass.bus.async_listen(
                "label_registry_updated",
                self._on_registry_updated,
            )
        )
        self._listeners.append(
            self.hass.bus.async_listen(
                "area_registry_updated",
                self._on_registry_updated,
            )
        )
        self._listeners.append(
            self.hass.bus.async_listen(
                "floor_registry_updated",
                self._on_registry_updated,
            )
        )
        self._listeners.append(
            self.hass.bus.async_listen(
                "homeassistant_start",
                self._on_homeassistant_start,
            )
        )
        self._listeners.append(
            self.hass.bus.async_listen(
                EVENT_LABELED_FEATURE_SET,
                self._on_labeled_feature_set,
            )
        )
        self._listeners.append(
            self.hass.bus.async_listen(
                EVENT_LABELED_FEATURE_SNAPSHOT_SET,
                self._on_labeled_feature_snapshot_set,
            )
        )

        # Initial reconciliation on boot
        self._recompute_all()

    async def async_will_remove_from_hass(self) -> None:
        """Clean up event listeners."""
        for listener in self._listeners:
            listener()
        self._listeners.clear()

    async def async_update_config(self, data: dict[str, Any]) -> None:
        """Update config entry data and options."""
        if CONF_ALERT_SCRIPT in data:
            self._alert_script = data[CONF_ALERT_SCRIPT]
        if CONF_ERROR_MODE_DEFAULT in data:
            self._error_mode_default = data[CONF_ERROR_MODE_DEFAULT]

    # ------------------------------------------------------------------
    # Entity/area/floor lookup helpers (sync, using registries directly)
    # ------------------------------------------------------------------

    def _get_feature_leader_entities(self) -> list[str]:
        """Get all entity_ids labeled with 'feature_leader' using the entity registry."""
        entity_reg = er.async_get(self.hass)
        return [
            entry.entity_id
            for entry in entity_reg.entities.values()
            if entry.labels and "feature_leader" in entry.labels
        ]

    def _get_entity_labels(self, entity_id: str) -> set[str]:
        """Get all labels for an entity using the entity registry."""
        entity_reg = er.async_get(self.hass)
        entry = entity_reg.entities.get(entity_id)
        if entry and entry.labels:
            return set(entry.labels)
        return set()

    def _get_area_labels(self, area_id: str) -> set[str]:
        """Get all labels for an area using the area registry."""
        area_reg = ar.async_get(self.hass)
        area = area_reg.areas.get(area_id)
        if area and area.labels:
            return set(area.labels)
        return set()

    def _get_area_id(self, entity_id: str) -> str:
        """Get the area_id for an entity using the entity registry."""
        entity_reg = er.async_get(self.hass)
        entry = entity_reg.entities.get(entity_id)
        if entry and entry.area_id:
            return entry.area_id
        return ""

    # ------------------------------------------------------------------
    # Event handlers
    # ------------------------------------------------------------------

    async def _on_state_changed(self, event: Event) -> None:
        """Handle state_changed events."""
        event_data: EventStateChangedData = event.data
        entity_id = event_data.get("entity_id", "")
        old_state = event_data.get("old_state")

        # Check if this entity is a feature_leader
        all_leader_entities = self._get_feature_leader_entities()

        if entity_id not in all_leader_entities:
            return

        # Skip events with no real prior state (boot restore, reconnection)
        if old_state is None or (
            old_state.state.lower() in ["unknown", "unavailable", "none"]
        ):
            return

        # Rebuild state
        self._recompute_leaders(entity_id)
        self._recompute_features(entity_id, "state_changed")
        self._notify_state_sensors()
        self._notify_areas_sensors()

    async def _on_registry_updated(self, event: Event) -> None:
        """Handle registry update events (label, area, floor)."""
        self._recompute_all()
        self._notify_state_sensors()
        self._notify_areas_sensors()

    async def _on_homeassistant_start(self, event: Event) -> None:
        """Reconcile all state on homeassistant.start."""
        self._recompute_all()
        self._notify_state_sensors()
        self._notify_areas_sensors()

    async def _on_labeled_feature_set(self, event: Event) -> None:
        """Handle a labeled_feature_set event (Set Feature catalog entry).

        This allows external scripts to set feature state via the event bus,
        maintaining backward compatibility with the Jinja2 template sensor.
        """
        data = event.data
        await self.async_handle_manual_set(
            target_feature=data.get("target_feature", ""),
            scope=data.get("scope", "global"),
            scope_id=data.get("scope_id", ""),
            enabled=data.get("enabled", False),
            timestamp=data.get("timestamp", dt_util.now().timestamp()),
        )

    async def _on_labeled_feature_snapshot_set(self, event: Event) -> None:
        """Handle a labeled_feature_snapshot_set event (Set Snapshot catalog entry).

        This allows external scripts to set snapshot data via the event bus,
        maintaining backward compatibility with the Jinja2 template sensor.
        """
        data = event.data
        self.async_handle_snapshot_set(
            snapshot_name=data.get("snapshot_name", ""),
            payload=data.get("payload", {}),
        )

    def _recompute_all(self) -> None:
        """Full recomputation of all state."""
        self._recompute_state_value()
        self._recompute_areas_state_value()
        self._recompute_label_map()
        self._recompute_leaders()
        # features doesn't have a changed_eid on full recompute — start fresh
        self._recompute_features("", "")

    # ------------------------------------------------------------------
    # State value computation
    # ------------------------------------------------------------------

    def _recompute_state_value(self) -> None:
        """Recompute the state value (count of feature_leader entities)."""
        self._state_value = len(self._get_feature_leader_entities())

    def _recompute_areas_state_value(self) -> None:
        """Recompute the areas state value (count of areas with feature_leader)."""
        leader_entity_ids = self._get_feature_leader_entities()
        areas_with_leaders = set()
        for eid in leader_entity_ids:
            area_id = self._get_area_id(eid)
            if area_id:
                areas_with_leaders.add(area_id)
        self._areas_state_value = len(areas_with_leaders)

    # ------------------------------------------------------------------
    # Leaders attribute computation
    # ------------------------------------------------------------------

    def _recompute_leaders(self, changed_eid: str = "") -> None:
        """Recompute the leaders attribute.

        Matches the Jinja2 template exactly.
        """
        all_leader_entities = self._get_feature_leader_entities()

        # Defensive: coerce carried-over data to dict
        prev_leaders_raw = self._leaders
        if not isinstance(prev_leaders_raw, dict):
            prev_leaders_raw = {}

        ns_result: dict[str, dict[str, Any]] = {}

        # Carry through existing entries for entities still labeled
        for eid, ldat in prev_leaders_raw.items():
            if eid in all_leader_entities and eid != changed_eid:
                ns_result[eid] = ldat

        # Add entries for newly-labeled leaders
        for eid in all_leader_entities:
            if eid not in ns_result and eid != changed_eid:
                st = self.hass.states.get(eid)
                lct = (
                    st.last_changed_timestamp
                    if st is not None and hasattr(st, "last_changed_timestamp")
                    else 0
                )
                ns_result[eid] = {
                    "current_value": st.state if st is not None else "",
                    "previous_value": "",
                    "last_changed_timestamp": lct,
                }

        # Rebuild the changed leader's entry
        if changed_eid and changed_eid in all_leader_entities:
            new_state = self.hass.states.get(changed_eid)
            cv_raw = self._get_current_value(changed_eid, new_state)
            is_skip = self._should_skip_event(cv_raw)

            prev_l = prev_leaders_raw.get(changed_eid, {})
            if is_skip:
                cv = prev_l.get("current_value", cv_raw)
                cv_ts = prev_l.get(
                    "last_changed_timestamp",
                    self._get_timestamp(new_state),
                )
            else:
                cv = cv_raw
                cv_ts = self._get_timestamp(new_state)

            old_cv_l = prev_l.get("current_value", "")
            old_pv_l = prev_l.get("previous_value", "")
            prev_cv_l_raw = old_cv_l if cv != old_cv_l else old_pv_l
            prev_cv_l = (
                ""
                if self._should_skip_event(prev_cv_l_raw)
                else prev_cv_l_raw
            )

            ns_result[changed_eid] = {
                "current_value": cv,
                "previous_value": prev_cv_l,
                "last_changed_timestamp": cv_ts,
            }

        self._leaders = ns_result

    def _get_current_value(self, entity_id: str, state) -> str:
        """Get the current value for a leader entity."""
        if state is None:
            return ""
        domain = entity_id.split(".")[0]
        if domain == "event":
            return state.attributes.get("event_type", state.state)
        return state.state

    def _get_timestamp(self, state) -> float:
        """Get the timestamp for a state."""
        if state is None or state.last_changed is None:
            return dt_util.now().timestamp()
        return state.last_changed.timestamp()

    def _should_skip_event(self, event_value: str) -> bool:
        """Check if an event should be skipped."""
        if event_value is None:
            return False
        if event_value.endswith(SKIP_EVENT_SUFFIX):
            return True
        if event_value.lower() in ["unknown", "unavailable", "none"]:
            return True
        return False

    # ------------------------------------------------------------------
    # Features attribute computation
    # ------------------------------------------------------------------

    def _recompute_features(
        self, changed_eid: str = "", evtype: str = ""
    ) -> None:
        """Recompute the features attribute.

        Matches the Jinja2 template exactly.
        """
        all_leader_entities = self._get_feature_leader_entities()

        # Defensive: coerce legacy schema
        prev_features_raw = self._features
        if not isinstance(prev_features_raw, dict):
            prev_features_raw = {}

        # Step 1: Build triples map: (feature, scope, scope_id) → [leader entity_ids]
        triples: dict[str, list[str]] = {}
        for eid in all_leader_entities:
            aid = self._get_area_id(eid)
            aid = aid.strip()
            fid = _compute_floor_id(self.hass, aid) if aid else ""

            entity_labels = self._get_entity_labels(eid)
            for lbl in entity_labels:
                m = LEADER_RE.match(lbl)
                if not m:
                    continue
                prefix = m.group(1).strip()
                fname = m.group(2).strip()

                if prefix == "Area":
                    scope_val = "area"
                elif prefix == "Floor":
                    scope_val = "floor"
                else:
                    scope_val = "global"

                if scope_val == "area" and aid == "":
                    continue
                if scope_val == "floor" and fid == "":
                    continue

                scope_id_val = (
                    aid
                    if scope_val == "area"
                    else (fid if scope_val == "floor" else "")
                )

                if scope_val == "area" and scope_id_val == "":
                    continue

                key = f"{fname}||{scope_val}||{scope_id_val}"
                if key not in triples:
                    triples[key] = []
                if eid not in triples[key]:
                    triples[key].append(eid)

        # Step 2: Resolve mode for each triple from sensor labels
        sensor_labels = self._get_entity_labels("sensor.labeled_features_state")
        mode_for: dict[str, str] = {}
        for key in triples.keys():
            parts = key.split("||")
            fname = parts[0]
            scope_val = parts[1]
            scope_pfx = (
                "Area "
                if scope_val == "area"
                else ("Floor " if scope_val == "floor" else "")
            )

            mode_found = "leader"
            for lbl in sensor_labels:
                expected = scope_pfx + fname + " Mode: "
                if lbl.startswith(expected):
                    mode_val = lbl[len(expected):]
                    if mode_val in ("Leader", "Any", "All"):
                        mode_found = mode_val.lower()
                        break
            mode_for[key] = mode_found

        # Step 3: Start with carried-through entries
        ns_result: dict[str, dict[str, dict[str, dict[str, Any]]]] = {}

        for fname, scopes_map in prev_features_raw.items():
            if not isinstance(scopes_map, dict):
                continue
            for scope_val, sids in scopes_map.items():
                if not isinstance(sids, dict):
                    continue
                for scope_id_val, entry in sids.items():
                    if not isinstance(entry, dict):
                        continue
                    key = f"{fname}||{scope_val}||{scope_id_val}"
                    has_leader = key in triples
                    is_manual = entry.get("triggering_leader", "") == ""
                    if has_leader or is_manual:
                        ns_result.setdefault(fname, {}).setdefault(
                            scope_val, {}
                        )[scope_id_val] = entry

        # Step 4: Handle state_changed path
        is_state_changed = (
            evtype == "state_changed"
            and changed_eid
            and changed_eid in all_leader_entities
        )
        if is_state_changed:
            new_state = self.hass.states.get(changed_eid)
            cv_raw = self._get_current_value(changed_eid, new_state)
            is_skip = self._should_skip_event(cv_raw)

            if not is_skip:
                ts = self._get_timestamp(new_state)
                prev_cv = self._leaders.get(changed_eid, {}).get(
                    "current_value", ""
                )

                for key, leaders_list in triples.items():
                    if changed_eid not in leaders_list:
                        continue

                    parts = key.split("||")
                    fname = parts[0]
                    scope_val = parts[1]
                    scope_id_val = parts[2]
                    scope_pfx = (
                        "Area "
                        if scope_val == "area"
                        else ("Floor " if scope_val == "floor" else "")
                    )
                    mode = mode_for.get(key, "leader")

                    # Evaluate the changed leader
                    this_truth = self._evaluate_leader(
                        changed_eid, fname, scope_pfx, cv_raw, prev_cv
                    )

                    if mode == "leader":
                        new_enabled = this_truth
                    else:
                        values = []
                        for other_eid in leaders_list:
                            if other_eid == changed_eid:
                                values.append(this_truth)
                            else:
                                other_st = self.hass.states.get(other_eid)
                                other_cv = (
                                    other_st.state if other_st else ""
                                )
                                other_prev = self._leaders.get(
                                    other_eid, {}
                                ).get("previous_value", "")
                                other_truth = self._evaluate_leader(
                                    other_eid,
                                    fname,
                                    scope_pfx,
                                    other_cv,
                                    other_prev,
                                )
                                values.append(other_truth)

                        if mode == "all":
                            new_enabled = min(values)
                        else:  # any
                            new_enabled = max(values)

                    # Get previous entry
                    existing_f = ns_result.get(fname, {})
                    existing_s = (
                        existing_f.get(scope_val, {})
                        if isinstance(existing_f, dict)
                        else {}
                    )
                    prev_entry = (
                        existing_s.get(scope_id_val, {})
                        if isinstance(existing_s, dict)
                        else {}
                    )
                    prev_enabled = prev_entry.get("enabled", None)
                    prev_ts = prev_entry.get(
                        "last_changed_timestamp", ts
                    )

                    # Check if enabled flipped
                    leader_dom = changed_eid.split(".")[0]
                    is_button_leader = leader_dom in ["event", "button"]
                    flipped = (
                        prev_enabled is None
                        or prev_enabled != new_enabled
                        or is_button_leader
                    )
                    new_ts = ts if flipped else prev_ts

                    new_entry = {
                        "enabled": new_enabled,
                        "mode": mode,
                        "last_changed_timestamp": new_ts,
                        "triggering_leader": changed_eid,
                    }

                    ns_result.setdefault(fname, {}).setdefault(
                        scope_val, {}
                    )[scope_id_val] = new_entry

        self._features = ns_result

    def _evaluate_leader(
        self,
        entity_id: str,
        feature_name: str,
        scope_prefix: str,
        cv: str,
        prev_cv: str,
    ) -> bool:
        """Evaluate whether a leader enables a feature.

        Matches the Jinja2 `eval_leader` macro exactly.
        Returns the post-Invert boolean enabled value.
        """
        entity_labels = self._get_entity_labels(entity_id)
        dom = entity_id.split(".")[0]

        inc_lbl = (
            scope_prefix + feature_name + " Increasing: True"
        ) in entity_labels
        dec_lbl = (
            scope_prefix + feature_name + " Decreasing: True"
        ) in entity_labels

        if inc_lbl or dec_lbl:
            cur_n = None
            prev_n = None
            try:
                cur_n = float(cv) if cv else None
            except (ValueError, TypeError):
                pass
            try:
                prev_n = float(prev_cv) if prev_cv else None
            except (ValueError, TypeError):
                pass

            has_mov = cur_n is not None and prev_n is not None
            is_inc = has_mov and cur_n > prev_n
            is_dec = has_mov and cur_n < prev_n

            base = (inc_lbl and is_inc) or (dec_lbl and is_dec)
        else:
            # Look for Enable: / Disable: labels
            en_lbl = ""
            dis_lbl = ""
            enable_prefix = scope_prefix + feature_name + " Enable: "
            disable_prefix = scope_prefix + feature_name + " Disable: "
            for lbl in entity_labels:
                if lbl.startswith(enable_prefix):
                    en_lbl = lbl[len(enable_prefix):]
                elif lbl.startswith(disable_prefix):
                    dis_lbl = lbl[len(disable_prefix):]

            if en_lbl or dis_lbl:
                cur_st = self.hass.states.get(entity_id)
                state_val = cur_st.state if cur_st else ""
                by_en = en_lbl != "" and state_val == en_lbl
                by_dis = dis_lbl != "" and state_val == dis_lbl

                if en_lbl and dis_lbl:
                    base = by_en and not by_dis
                elif en_lbl:
                    base = by_en
                else:
                    base = not by_dis
            else:
                # Default truth function
                if dom in ["event", "button"]:
                    base = True
                else:
                    st = self.hass.states.get(entity_id)
                    state_val = st.state if st else ""
                    base = (
                        state_val == feature_name
                        or state_val.lower() in TRUTHY_VALUES
                    )

        # Apply Invert
        inverted = (
            scope_prefix + feature_name + " Invert: True"
        ) in entity_labels
        return (not base) if inverted else base

    # ------------------------------------------------------------------
    # Manual override (Set Feature)
    # ------------------------------------------------------------------

    async def async_handle_manual_set(
        self,
        target_feature: str,
        scope: str,
        scope_id: str,
        enabled: bool,
        timestamp: float,
    ) -> None:
        """Handle a manual feature set event."""
        if not target_feature or scope not in ("area", "floor", "global"):
            return

        # Carry through existing entries
        prev_features_raw = self._features
        if not isinstance(prev_features_raw, dict):
            prev_features_raw = {}

        ns_result: dict[str, dict[str, dict[str, dict[str, Any]]]] = {}

        for fname, scopes_map in prev_features_raw.items():
            if not isinstance(scopes_map, dict):
                continue
            for scope_val, sids in scopes_map.items():
                if not isinstance(sids, dict):
                    continue
                for sid, entry in sids.items():
                    if not isinstance(entry, dict):
                        continue
                    ns_result.setdefault(fname, {}).setdefault(
                        scope_val, {}
                    )[sid] = entry

        # Write the manual override
        prev_entry = (
            ns_result.get(target_feature, {})
            .get(scope, {})
            .get(scope_id, {})
        )
        mode = prev_entry.get("mode", "leader")

        ns_result.setdefault(target_feature, {}).setdefault(
            scope, {}
        )[scope_id] = {
            "enabled": enabled,
            "mode": mode,
            "last_changed_timestamp": timestamp,
            "triggering_leader": "",
        }

        self._features = ns_result
        self._notify_state_sensors()

    # ------------------------------------------------------------------
    # Snapshots attribute computation
    # ------------------------------------------------------------------

    def async_handle_snapshot_set(
        self, snapshot_name: str, payload: dict[str, Any]
    ) -> None:
        """Handle a snapshot set event (Set Snapshot catalog entry).

        Updates the snapshots attribute and notifies sensors.
        Empty payload deletes the entry.
        """
        if not snapshot_name:
            return

        prev = self._snapshots if isinstance(self._snapshots, dict) else {}

        if not isinstance(payload, dict) or len(payload) == 0:
            # Delete the entry
            prev.pop(snapshot_name, None)
        else:
            prev[snapshot_name] = payload

        self._snapshots = prev
        self._notify_state_sensors()

    # ------------------------------------------------------------------
    # Label map (areas state)
    # ------------------------------------------------------------------

    def _recompute_label_map(self) -> None:
        """Recompute the label_map attribute for areas_state sensor.

        Matches the Jinja2 template exactly.
        Uses registries directly (no async calls).
        """
        # Pass 1: Build empty scope skeleton for every area gated by feature_leader
        leader_entity_ids = self._get_feature_leader_entities()
        areas_with_leaders = set()
        for eid in leader_entity_ids:
            aid = self._get_area_id(eid)
            if aid.strip():
                areas_with_leaders.add(aid.strip())

        # Pass 2: Parse each gated area's labels for (Area|Floor)Provides: <Label>
        scopes: dict[str, dict[str, Any]] = {}
        for aid in areas_with_leaders:
            fid = _compute_floor_id(self.hass, aid)
            scopes[aid] = {
                "kind": "area",
                "floor_id": fid,
                "labels": {},
            }

        # Parse area labels for Provides: declarations
        area_reg = ar.async_get(self.hass)
        modifier_re = re.compile(MODIFIER_LABEL_PATTERN)

        for aid in areas_with_leaders:
            area = area_reg.areas.get(aid)
            if area is None:
                continue

            area_lbls = list(area.labels) if area.labels else []
            this_floor_id = scopes[aid]["floor_id"]

            for lbl in area_lbls:
                m = PROVIDES_RE.match(lbl)
                if not m:
                    continue

                prefix = m.group(1).strip()
                lname = m.group(2).strip()

                # Skip modifier labels
                if modifier_re.match(lname):
                    continue

                if lname == "":
                    continue

                scope_val = (
                    "area"
                    if prefix == "Area"
                    else ("floor" if prefix == "Floor" else "none")
                )
                scope_id_val = (
                    aid
                    if scope_val in ("area", "none")
                    else this_floor_id
                )

                if scope_id_val == "":
                    continue

                # Component hint
                scope_prefix = (
                    "Area "
                    if scope_val == "area"
                    else ("Floor " if scope_val == "floor" else "")
                )
                comp_override = ""
                comp_pattern_prefix = (
                    scope_prefix + "Provides " + lname + " Component: "
                )
                for area_lbl in area_lbls:
                    if area_lbl.startswith(comp_pattern_prefix):
                        comp_override = area_lbl[
                            len(comp_pattern_prefix):
                        ].strip()
                        break
                component = comp_override if comp_override else "select"

                lentry = {
                    "scope": scope_val,
                    "scope_id": scope_id_val,
                    "component": component,
                    "declaring_area_id": aid,
                }

                if scope_id_val not in scopes:
                    scopes[scope_id_val] = {
                        "kind": "floor",
                        "floor_id": scope_id_val,
                        "labels": {lname: lentry},
                    }
                else:
                    existing = scopes[scope_id_val]
                    if lname not in existing.get("labels", {}):
                        labels = dict(existing.get("labels", {}))
                        labels[lname] = lentry
                        existing["labels"] = labels

        # Flatten to public <scope_id>||<label> → label_data map
        fns: dict[str, dict[str, Any]] = {}
        for sid, sdat in scopes.items():
            for lname, ldat in sdat.get("labels", {}).items():
                fns[f"{sid}||{lname}"] = {
                    "scope_id": sid,
                    "label": lname,
                    "scope": ldat.get("scope", "area"),
                    "component": ldat.get("component"),
                    "declaring_area_id": ldat.get("declaring_area_id"),
                    "label_data": ldat,
                }

        self._label_map = fns

    # ------------------------------------------------------------------
    # Error handling
    # ------------------------------------------------------------------

    async def async_handle_error(
        self,
        error_mode: str,
        message: str,
        source: str = "Labeled Features",
        severity: str = "medium",
    ) -> None:
        """Handle errors per the Error Mode tiers.

        Matches script.labeled_feature_error_mode behavior exactly.

        Tiers:
        - silent: no-op
        - log: system_log.write at warning
        - alert: script.send_alert
        - stop: system_log.write at error (caller must do stop: error: true)
        """
        if error_mode not in SUPPORTED_ERROR_MODES:
            error_mode = self._error_mode_default

        if error_mode == "silent":
            pass
        elif error_mode == "log":
            await self.hass.services.async_call(
                "system_log",
                "write",
                {
                    "level": "warning",
                    "message": f"{source}: {message}",
                },
                blocking=True,
            )
        elif error_mode == "alert":
            alert_script = self._alert_script
            if alert_script:
                await self.hass.services.async_call(
                    "script",
                    "send_alert",
                    {
                        "alert_severity": severity,
                        "alert_title": source,
                        "alert_message": message,
                    },
                    blocking=True,
                )
        elif error_mode == "stop":
            await self.hass.services.async_call(
                "system_log",
                "write",
                {
                    "level": "error",
                    "message": f"{source}: {message}",
                },
                blocking=True,
            )

    # ------------------------------------------------------------------
    # Custom events
    # ------------------------------------------------------------------

    async def async_fire_labeled_feature_set(
        self,
        target_feature: str,
        scope: str,
        scope_id: str,
        enabled: bool,
    ) -> None:
        """Fire a labeled_feature_set event (manual override)."""
        ts = dt_util.now().timestamp()
        self.hass.bus.fire(
            EVENT_LABELED_FEATURE_SET,
            {
                "target_feature": target_feature,
                "scope": scope,
                "scope_id": scope_id,
                "enabled": enabled,
                "timestamp": ts,
            },
        )

    async def async_fire_labeled_feature_snapshot_set(
        self,
        snapshot_name: str,
        payload: dict[str, Any],
    ) -> None:
        """Fire a labeled_feature_snapshot_set event."""
        ts = dt_util.now().timestamp()
        self.hass.bus.fire(
            EVENT_LABELED_FEATURE_SNAPSHOT_SET,
            {
                "snapshot_name": snapshot_name,
                "payload": payload,
                "timestamp": ts,
            },
        )

    # ------------------------------------------------------------------
    # Sensor notification
    # ------------------------------------------------------------------

    def register_state_sensor_update_callback(
        self, callback_fn: Callable[[], None]
    ) -> None:
        """Register a callback for state sensor updates."""
        self._state_sensor_callbacks.append(callback_fn)

    def register_areas_sensor_update_callback(
        self, callback_fn: Callable[[], None]
    ) -> None:
        """Register a callback for areas sensor updates."""
        self._areas_sensor_callbacks.append(callback_fn)

    @callback
    def _notify_state_sensors(self) -> None:
        """Notify state sensor that data has changed."""
        for cb in self._state_sensor_callbacks:
            try:
                cb()
            except Exception:
                _LOGGER.error(
                    "Error notifying state sensor callback", exc_info=True
                )

    @callback
    def _notify_areas_sensors(self) -> None:
        """Notify areas sensor that data has changed."""
        for cb in self._areas_sensor_callbacks:
            try:
                cb()
            except Exception:
                _LOGGER.error(
                    "Error notifying areas sensor callback", exc_info=True
                )


PLATFORMS: list[str] = ["sensor"]

type LabeledFeaturesConfigEntry = ConfigEntry[LabeledFeaturesManager]


async def async_setup_entry(hass, entry: LabeledFeaturesConfigEntry) -> bool:
    """Set up labeled_features from a config entry."""
    manager = LabeledFeaturesManager(hass, entry)
    await manager.async_setup()
    entry.runtime_data = manager
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    entry.async_on_unload(entry.add_update_listener(_async_update_listener))
    return True


async def async_unload_entry(hass, entry: LabeledFeaturesConfigEntry) -> bool:
    """Unload a config entry."""
    manager = entry.runtime_data
    await manager.async_will_remove_from_hass()
    ok = await hass.config_entries.async_unload_platforms(entry, PLATFORMS)
    if ok:
        entry.runtime_data = None
    return ok


async def _async_update_listener(hass, entry):
    """Handle options update — reload to apply changes."""
    await hass.config_entries.async_reload(entry.entry_id)
