"""Config flow for the labeled_features integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import Any

import voluptuous as vol

from homeassistant import config_entries
from homeassistant.const import CONF_NAME
from homeassistant.core import callback
from homeassistant.data_entry_flow import FlowResult
from homeassistant.helpers import config_validation as cv
from homeassistant.helpers.selector import (
    SelectSelector,
    SelectSelectorConfig,
    SelectSelectorMode,
)

from .const import (
    CONF_ALERT_SCRIPT,
    CONF_ERROR_MODE_DEFAULT,
    DEFAULT_ERROR_MODE,
    DOMAIN,
    ENTRY_DATA_ALERT_SCRIPT,
    ENTRY_DATA_ERROR_MODE_DEFAULT,
    SUPPORTED_ERROR_MODES,
)

STEP_USER_DATA_SCHEMA = vol.Schema(
    {
        vol.Optional(
            CONF_ERROR_MODE_DEFAULT,
            default=DEFAULT_ERROR_MODE,
        ): SelectSelector(
            SelectSelectorConfig(
                options=SUPPORTED_ERROR_MODES,
                mode=SelectSelectorMode.DROPDOWN,
                translation_key="error_mode",
            )
        ),
        vol.Optional(CONF_ALERT_SCRIPT, default=""): cv.string,
    }
)


class LabeledFeaturesConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
    """Handle a config flow for labeled_features."""

    VERSION = 1

    @staticmethod
    @callback
    def async_get_options_flow(
        config_entry: config_entries.ConfigEntry,
    ) -> LabeledFeaturesOptionsFlow:
        """Get the options flow."""
        return LabeledFeaturesOptionsFlow(config_entry)

    async def async_step_user(
        self, user_input: dict[str, Any] | None = None
    ) -> FlowResult:
        """Handle the initial step."""
        if user_input is not None:
            return self.async_create_entry(
                title="Labeled Features",
                data=user_input,
            )

        return self.async_show_form(
            step_id="user",
            data_schema=STEP_USER_DATA_SCHEMA,
        )


class LabeledFeaturesOptionsFlow(config_entries.OptionsFlow):
    """Handle options flow."""

    def __init__(self, config_entry: config_entries.ConfigEntry) -> None:
        """Initialize."""
        self.config_entry = config_entry

    async def async_step_init(
        self, user_input: dict[str, Any] | None = None
    ) -> FlowResult:
        """Manage options."""
        if user_input is not None:
            return self.async_create_entry(
                title="",
                data=user_input,
            )

        options = self.config_entry.options
        data = self.config_entry.data

        return self.async_show_form(
            step_id="init",
            data_schema=vol.Schema(
                {
                    vol.Optional(
                        CONF_ERROR_MODE_DEFAULT,
                        default=options.get(
                            CONF_ERROR_MODE_DEFAULT,
                            data.get(
                                ENTRY_DATA_ERROR_MODE_DEFAULT,
                                DEFAULT_ERROR_MODE,
                            ),
                        ),
                    ): SelectSelector(
                        SelectSelectorConfig(
                            options=SUPPORTED_ERROR_MODES,
                            mode=SelectSelectorMode.DROPDOWN,
                            translation_key="error_mode",
                        )
                    ),
                    vol.Optional(
                        CONF_ALERT_SCRIPT,
                        default=options.get(
                            CONF_ALERT_SCRIPT,
                            data.get(ENTRY_DATA_ALERT_SCRIPT, ""),
                        ),
                    ): cv.string,
                }
            ),
        )
