"""Config flow for the Labeled Features integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import re
from typing import Any

import voluptuous as vol
from homeassistant import config_entries
from homeassistant.config_entries import ConfigEntry, ConfigFlowResult
from homeassistant.core import callback
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers.selector import (
    SelectSelector,
    SelectSelectorConfig,
    SelectSelectorMode,
)

from .const import (
    CONF_ALERT_ACTION,
    CONF_AREAS_ENTITY_ID,
    CONF_ERROR_MODE,
    CONF_FEATURES_ENTITY_ID,
    CONF_INSTANCE_NAME,
    CONF_LEADER_LABEL,
    CONF_SCRIPT_CALL_MODE,
    DEFAULT_ALERT_ACTION,
    DEFAULT_AREAS_ENTITY_ID,
    DEFAULT_ERROR_MODE,
    DEFAULT_FEATURES_ENTITY_ID,
    DEFAULT_INSTANCE_NAME,
    DEFAULT_LEADER_LABEL,
    DEFAULT_SCRIPT_CALL_MODE,
    DOMAIN,
    ERROR_MODES,
    SCRIPT_CALL_MODES,
)

# Mirror homeassistant.core._VALID_ENTITY_ID:
# lowercase / digits / underscores per segment, no leading or trailing '_',
# and no double underscores anywhere.
_ENTITY_ID_RE = re.compile(
    r"^sensor\.(?!_)(?!.*_$)(?!.*__)[a-z0-9_]+$"
)
_ACTION_RE = re.compile(r"^[a-z0-9_]+\.[a-z0-9_]+$")


def _base_schema(defaults: dict[str, Any]) -> vol.Schema:
    return vol.Schema(
        {
            vol.Required(
                CONF_INSTANCE_NAME,
                default=defaults.get(CONF_INSTANCE_NAME, DEFAULT_INSTANCE_NAME),
            ): str,
            vol.Required(
                CONF_FEATURES_ENTITY_ID,
                default=defaults.get(CONF_FEATURES_ENTITY_ID, DEFAULT_FEATURES_ENTITY_ID),
            ): str,
            vol.Required(
                CONF_AREAS_ENTITY_ID,
                default=defaults.get(CONF_AREAS_ENTITY_ID, DEFAULT_AREAS_ENTITY_ID),
            ): str,
            vol.Required(
                CONF_LEADER_LABEL,
                default=defaults.get(CONF_LEADER_LABEL, DEFAULT_LEADER_LABEL),
            ): str,
            vol.Required(
                CONF_ERROR_MODE,
                default=defaults.get(CONF_ERROR_MODE, DEFAULT_ERROR_MODE),
            ): SelectSelector(
                SelectSelectorConfig(
                    options=list(ERROR_MODES), mode=SelectSelectorMode.DROPDOWN
                )
            ),
            vol.Required(
                CONF_ALERT_ACTION,
                default=defaults.get(CONF_ALERT_ACTION, DEFAULT_ALERT_ACTION),
            ): str,
            vol.Required(
                CONF_SCRIPT_CALL_MODE,
                default=defaults.get(CONF_SCRIPT_CALL_MODE, DEFAULT_SCRIPT_CALL_MODE),
            ): SelectSelector(
                SelectSelectorConfig(
                    options=list(SCRIPT_CALL_MODES), mode=SelectSelectorMode.DROPDOWN
                )
            ),
        }
    )


def _validate(
    user_input: dict[str, Any],
    hass_entity_registry: er.EntityRegistry,
    hass,
    ignore_entry_id: str | None = None,
) -> dict[str, str]:
    """Validate user input; return a dict of {field: error_key} (empty = OK)."""
    errors: dict[str, str] = {}
    features_id = user_input.get(CONF_FEATURES_ENTITY_ID, "").strip()
    areas_id = user_input.get(CONF_AREAS_ENTITY_ID, "").strip()
    alert = user_input.get(CONF_ALERT_ACTION, "").strip()
    leader_label = user_input.get(CONF_LEADER_LABEL, "").strip()

    if not _ENTITY_ID_RE.match(features_id):
        errors[CONF_FEATURES_ENTITY_ID] = "entity_id_invalid"
    if not _ENTITY_ID_RE.match(areas_id):
        errors[CONF_AREAS_ENTITY_ID] = "entity_id_invalid"
    if features_id and features_id == areas_id:
        errors[CONF_AREAS_ENTITY_ID] = "entity_id_duplicate"
    if not _ACTION_RE.match(alert):
        errors[CONF_ALERT_ACTION] = "alert_action_invalid"
    if not leader_label:
        errors[CONF_LEADER_LABEL] = "leader_label_required"

    # Collision check: fail if a foreign entity already owns either target ID.
    for field, target_id in (
        (CONF_FEATURES_ENTITY_ID, features_id),
        (CONF_AREAS_ENTITY_ID, areas_id),
    ):
        if field in errors:
            continue
        existing = hass_entity_registry.async_get(target_id)
        if existing is not None and existing.config_entry_id not in (None, ignore_entry_id):
            errors[field] = "entity_id_taken"
            continue
        state = hass.states.get(target_id)
        # If a state exists but no matching registry entry, a YAML template
        # sensor almost certainly owns it. Refuse.
        if state is not None and existing is None:
            errors[field] = "entity_id_taken"

    return errors


class LabeledFeaturesConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
    """Handle a config flow for Labeled Features."""

    VERSION = 1

    async def async_step_user(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        errors: dict[str, str] = {}
        if user_input is not None:
            ent_reg = er.async_get(self.hass)
            errors = _validate(user_input, ent_reg, self.hass)
            if not errors:
                # Assign a unique_id per (leader_label, features_id) to
                # discourage identical duplicate instances.
                unique_id = (
                    f"{user_input[CONF_LEADER_LABEL]}|"
                    f"{user_input[CONF_FEATURES_ENTITY_ID]}"
                )
                await self.async_set_unique_id(unique_id)
                self._abort_if_unique_id_configured()
                return self.async_create_entry(
                    title=user_input[CONF_INSTANCE_NAME],
                    data=user_input,
                )
        return self.async_show_form(
            step_id="user",
            data_schema=_base_schema(user_input or {}),
            errors=errors,
        )

    async def async_step_reconfigure(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        entry = self._get_reconfigure_entry()
        errors: dict[str, str] = {}
        if user_input is not None:
            ent_reg = er.async_get(self.hass)
            errors = _validate(user_input, ent_reg, self.hass, ignore_entry_id=entry.entry_id)
            if not errors:
                return self.async_update_reload_and_abort(
                    entry,
                    data=user_input,
                    title=user_input[CONF_INSTANCE_NAME],
                )
        return self.async_show_form(
            step_id="reconfigure",
            data_schema=_base_schema(user_input or {**entry.data, **entry.options}),
            errors=errors,
        )

    @staticmethod
    @callback
    def async_get_options_flow(
        config_entry: ConfigEntry,
    ) -> "LabeledFeaturesOptionsFlow":
        # HA passes the entry; the OptionsFlow base class stores it on
        # self.config_entry automatically.
        return LabeledFeaturesOptionsFlow()


class LabeledFeaturesOptionsFlow(config_entries.OptionsFlow):
    """Handle options-flow updates (subset of fields).

    HA auto-populates `self.config_entry`; no custom `__init__` needed
    (positional-arg init is deprecated in current HA releases).
    """

    async def async_step_init(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        merged = {**self.config_entry.data, **self.config_entry.options}
        errors: dict[str, str] = {}
        if user_input is not None:
            # Options flow only lets the user tweak non-entity-ID fields.
            leader_label = user_input.get(CONF_LEADER_LABEL, "").strip()
            alert = user_input.get(CONF_ALERT_ACTION, "").strip()
            if not leader_label:
                errors[CONF_LEADER_LABEL] = "leader_label_required"
            if not _ACTION_RE.match(alert):
                errors[CONF_ALERT_ACTION] = "alert_action_invalid"
            if not errors:
                return self.async_create_entry(title="", data=user_input)

        schema = vol.Schema(
            {
                vol.Required(
                    CONF_LEADER_LABEL,
                    default=merged.get(CONF_LEADER_LABEL, DEFAULT_LEADER_LABEL),
                ): str,
                vol.Required(
                    CONF_ERROR_MODE,
                    default=merged.get(CONF_ERROR_MODE, DEFAULT_ERROR_MODE),
                ): SelectSelector(
                    SelectSelectorConfig(
                        options=list(ERROR_MODES), mode=SelectSelectorMode.DROPDOWN
                    )
                ),
                vol.Required(
                    CONF_ALERT_ACTION,
                    default=merged.get(CONF_ALERT_ACTION, DEFAULT_ALERT_ACTION),
                ): str,
                vol.Required(
                    CONF_SCRIPT_CALL_MODE,
                    default=merged.get(CONF_SCRIPT_CALL_MODE, DEFAULT_SCRIPT_CALL_MODE),
                ): SelectSelector(
                    SelectSelectorConfig(
                        options=list(SCRIPT_CALL_MODES), mode=SelectSelectorMode.DROPDOWN
                    )
                ),
            }
        )
        return self.async_show_form(step_id="init", data_schema=schema, errors=errors)
