"""Config flow for Labeled Features.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import Any

import voluptuous as vol
from homeassistant import config_entries
from homeassistant.core import HomeAssistant, callback
from homeassistant.data_entry_flow import FlowResult
from homeassistant.helpers import selector

from .const import (
    CONF_ALERT_ACTION,
    CONF_DEFAULT_ERROR_MODE,
    CONF_ENTITY_ID_SUFFIX,
    CONF_FEATURE_LEADER_LABEL,
    DEFAULT_ALERT_ACTION,
    DEFAULT_ERROR_MODE,
    DEFAULT_FEATURE_LEADER_LABEL,
    DOMAIN,
    ERROR_MODES,
)


class LabeledFeaturesConfigFlow(
    config_entries.ConfigFlow, domain=DOMAIN
):
    """Config flow for Labeled Features."""

    VERSION = 1

    @staticmethod
    @callback
    def async_get_options_flow(
        config_entry: config_entries.ConfigEntry,
    ) -> config_entries.OptionsFlow:
        """Get the options flow."""
        return OptionsFlowHandler(config_entry)

    async def async_step_user(
        self, user_input: dict[str, Any] | None = None
    ) -> FlowResult:
        """Handle a user config entry."""
        if user_input is not None:
            suffix = user_input.get(CONF_ENTITY_ID_SUFFIX, "").strip()
            if suffix:
                self._async_abort_entries_match(
                    {CONF_ENTITY_ID_SUFFIX: suffix}
                )
            else:
                for existing in self._async_current_entries():
                    ex_suffix = existing.data.get(
                        CONF_ENTITY_ID_SUFFIX, ""
                    ).strip()
                    if not ex_suffix:
                        return self.async_abort(
                            reason="already_configured"
                        )

            title = f"Labeled Features{f' ({suffix})' if suffix else ''}"
            return self.async_create_entry(title=title, data=user_input)

        return self.async_show_form(
            step_id="user",
            data_schema=vol.Schema(
                {
                    vol.Optional(
                        CONF_FEATURE_LEADER_LABEL,
                        default=DEFAULT_FEATURE_LEADER_LABEL,
                    ): str,
                    vol.Optional(
                        CONF_DEFAULT_ERROR_MODE,
                        default=DEFAULT_ERROR_MODE,
                    ): selector.SelectSelector(
                        selector.SelectSelectorConfig(
                            options=list(ERROR_MODES),
                            mode=selector.SelectSelectorMode.DROPDOWN,
                            translation_key="error_mode",
                        )
                    ),
                    vol.Optional(
                        CONF_ALERT_ACTION,
                        default=DEFAULT_ALERT_ACTION,
                    ): str,
                    vol.Optional(
                        CONF_ENTITY_ID_SUFFIX,
                        default="",
                    ): str,
                }
            ),
        )


class OptionsFlowHandler(config_entries.OptionsFlow):
    """Handle options flow."""

    def __init__(
        self, config_entry: config_entries.ConfigEntry
    ) -> None:
        """Initialize."""
        self._config_entry = config_entry

    async def async_step_init(
        self, user_input: dict[str, Any] | None = None
    ) -> FlowResult:
        """Handle options flow."""
        if user_input is not None:
            return self.async_create_entry(data=user_input)

        return self.async_show_form(
            step_id="init",
            data_schema=vol.Schema(
                {
                    vol.Optional(
                        CONF_FEATURE_LEADER_LABEL,
                        default=self._config_entry.data.get(
                            CONF_FEATURE_LEADER_LABEL, DEFAULT_FEATURE_LEADER_LABEL
                        ),
                    ): str,
                    vol.Optional(
                        CONF_DEFAULT_ERROR_MODE,
                        default=self._config_entry.data.get(
                            CONF_DEFAULT_ERROR_MODE, DEFAULT_ERROR_MODE
                        ),
                    ): selector.SelectSelector(
                        selector.SelectSelectorConfig(
                            options=list(ERROR_MODES),
                            mode=selector.SelectSelectorMode.DROPDOWN,
                            translation_key="error_mode",
                        )
                    ),
                    vol.Optional(
                        CONF_ALERT_ACTION,
                        default=self._config_entry.data.get(
                            CONF_ALERT_ACTION, DEFAULT_ALERT_ACTION
                        ),
                    ): str,
                }
            ),
        )