"""Constants for the Labeled Features integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

DOMAIN = "labeled_features"

PLATFORMS: list[str] = ["sensor"]

# Sensor stems (default instance keeps the legacy entity ids / unique ids).
FEATURES_SENSOR_STEM = "labeled_features_state"
AREAS_SENSOR_STEM = "labeled_feature_areas_state"

# Labels
LABEL_FEATURE_LEADER = "feature_leader"

# Compat events (fired by the legacy YAML stack, e.g. labeled_feature_generics).
EVENT_LABELED_FEATURE_SET = "labeled_feature_set"
EVENT_LABELED_FEATURE_SNAPSHOT_SET = "labeled_feature_snapshot_set"

# Services
SERVICE_SET_FEATURE = "set_feature"
SERVICE_SET_SNAPSHOT = "set_snapshot"
SERVICE_HANDLE_ERROR = "handle_error"

# Error modes
ERROR_SILENT = "silent"
ERROR_LOG = "log"
ERROR_ALERT = "alert"
ERROR_STOP = "stop"
ERROR_MODES = [ERROR_SILENT, ERROR_LOG, ERROR_ALERT, ERROR_STOP]

# Alert severities
SEVERITIES = ["low", "medium", "high"]

# Config entry data keys
CONF_SUFFIX = "entity_id_suffix"

# Options keys
CONF_ERROR_MODE = "error_mode"
CONF_ALERT_ACTION = "alert_action"
CONF_ALERT_SEVERITY = "alert_severity"

DEFAULT_ERROR_MODE = ERROR_LOG
DEFAULT_ALERT_ACTION = "script.send_alert"
DEFAULT_ALERT_SEVERITY = "medium"

# Subentry types
SUBENTRY_TYPE_LEADER = "leader"
SUBENTRY_TYPE_PROVIDES = "provides"
SUBENTRY_TYPE_MODE = "mode"

# Leader subentry fields
SUBCONF_ENTITY_ID = "entity_id"
SUBCONF_FEATURE = "feature"
SUBCONF_SCOPE = "scope"
SUBCONF_ENABLE_VALUE = "enable_value"
SUBCONF_DISABLE_VALUE = "disable_value"
SUBCONF_DIRECTION = "direction"
SUBCONF_INVERT = "invert"

# Provides subentry fields
SUBCONF_AREA_ID = "area_id"
SUBCONF_COMPONENT = "component"

# Mode subentry fields
SUBCONF_MODE = "mode"

# Scopes
SCOPE_AREA = "area"
SCOPE_FLOOR = "floor"
SCOPE_GLOBAL = "global"
SCOPE_NONE = "none"  # areas stack only (bare Provides: prefix)
LEADER_SCOPES = [SCOPE_AREA, SCOPE_FLOOR, SCOPE_GLOBAL]
PROVIDES_SCOPES = [SCOPE_AREA, SCOPE_FLOOR, SCOPE_NONE]

# Direction values (leader subentry)
DIRECTION_NONE = "none"
DIRECTION_INCREASING = "increasing"
DIRECTION_DECREASING = "decreasing"
DIRECTION_BOTH = "both"
DIRECTIONS = [DIRECTION_NONE, DIRECTION_INCREASING, DIRECTION_DECREASING, DIRECTION_BOTH]

# Fold modes
MODE_LEADER = "leader"
MODE_ANY = "any"
MODE_ALL = "all"
FOLD_MODES = [MODE_LEADER, MODE_ANY, MODE_ALL]

# Default-truth set (case-insensitive comparison), per the docs.
TRUTHY_STATES = {"on", "true", "home", "open", "detected", "active", "unlocked"}

# Domains whose every accepted change is a "fire" (button presses).
MOMENTARY_DOMAINS = {"event", "button"}

# Skip values: carried through without updating the leaders entry.
SKIP_STATES = {"unknown", "unavailable", "none"}
SKIP_SUFFIX = "_initial_press"

# Generic-feature catalog. Single source of truth, ported verbatim from
# configuration.yaml's feature_meta attribute:
#   domain       — fallback target pool domain ('' = no fallback)
#   kind         — internal action key consumed by labeled_feature_generics
#   domain_label — provider grouping for `Provides: <DomainLabel>` shorthand
FEATURE_META: dict[str, dict[str, str]] = {
    "Media Toggle": {"domain": "media_player", "kind": "media_toggle", "domain_label": "Media Player"},
    "Media Play": {"domain": "media_player", "kind": "media_play", "domain_label": "Media Player"},
    "Media Pause": {"domain": "media_player", "kind": "media_pause", "domain_label": "Media Player"},
    "Media Next": {"domain": "media_player", "kind": "media_next", "domain_label": "Media Player"},
    "Media Previous": {"domain": "media_player", "kind": "media_previous", "domain_label": "Media Player"},
    "Media Seek Back": {"domain": "media_player", "kind": "media_seek_back", "domain_label": "Media Player"},
    "Media Seek Forward": {"domain": "media_player", "kind": "media_seek_forward", "domain_label": "Media Player"},
    "Volume Up": {"domain": "media_player", "kind": "volume_up", "domain_label": "Media Player"},
    "Volume Down": {"domain": "media_player", "kind": "volume_down", "domain_label": "Media Player"},
    "Lights On": {"domain": "light", "kind": "light_on", "domain_label": "Light"},
    "Lights Off": {"domain": "light", "kind": "light_off", "domain_label": "Light"},
    "Lights Up": {"domain": "light", "kind": "light_up", "domain_label": "Light"},
    "Lights Down": {"domain": "light", "kind": "light_down", "domain_label": "Light"},
    "Fan On": {"domain": "fan", "kind": "fan_on", "domain_label": "Fan"},
    "Fan Off": {"domain": "fan", "kind": "fan_off", "domain_label": "Fan"},
    "Fan Up": {"domain": "fan", "kind": "fan_up", "domain_label": "Fan"},
    "Fan Down": {"domain": "fan", "kind": "fan_down", "domain_label": "Fan"},
}

# Modifier-label keywords filtered out of the areas label_map (they are
# modifiers of a Provides declaration, not features in their own right).
PROVIDES_MODIFIER_KEYWORDS = (
    "Component", "Min", "Max", "Step", "Unit", "Icon", "Initial", "Static",
    "Mode", "Device Class",
)

# Repair issue keys
ISSUE_LEADER_NO_AREA = "leader_no_area"
ISSUE_LEADER_NO_FLOOR = "leader_no_floor"
ISSUE_PROVIDES_NO_FLOOR = "provides_no_floor"
ISSUE_INVALID_SUBENTRY = "invalid_subentry"
ISSUE_ALERT_ACTION_FAILED = "alert_action_failed"
