"""Constants for Labeled Features integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import Final

# Domain
DOMAIN: Final = "labeled_features"

# Config entry keys
CONF_DEFAULT_ERROR_MODE: Final = "default_error_mode"
CONF_ALERT_ACTION: Final = "alert_action"
CONF_ENTITY_ID_SUFFIX: Final = "entity_id_suffix"

# Error mode tiers
ERROR_MODE_SILENT: Final = "silent"
ERROR_MODE_LOG: Final = "log"
ERROR_MODE_ALERT: Final = "alert"
ERROR_MODE_STOP: Final = "stop"
ERROR_MODES: Final = (ERROR_MODE_SILENT, ERROR_MODE_LOG, ERROR_MODE_ALERT, ERROR_MODE_STOP)
DEFAULT_ERROR_MODE: Final = ERROR_MODE_LOG
DEFAULT_ALERT_ACTION: Final = "script.send_alert"

# Feature catalog (byte-compatible with template sensor)
FEATURE_META: Final = {
    "Media Toggle": {
        "domain": "media_player",
        "kind": "media_toggle",
        "domain_label": "Media Player",
    },
    "Media Play": {
        "domain": "media_player",
        "kind": "media_play",
        "domain_label": "Media Player",
    },
    "Media Pause": {
        "domain": "media_player",
        "kind": "media_pause",
        "domain_label": "Media Player",
    },
    "Media Next": {
        "domain": "media_player",
        "kind": "media_next",
        "domain_label": "Media Player",
    },
    "Media Previous": {
        "domain": "media_player",
        "kind": "media_previous",
        "domain_label": "Media Player",
    },
    "Media Seek Back": {
        "domain": "media_player",
        "kind": "media_seek_back",
        "domain_label": "Media Player",
    },
    "Media Seek Forward": {
        "domain": "media_player",
        "kind": "media_seek_forward",
        "domain_label": "Media Player",
    },
    "Volume Up": {
        "domain": "media_player",
        "kind": "volume_up",
        "domain_label": "Media Player",
    },
    "Volume Down": {
        "domain": "media_player",
        "kind": "volume_down",
        "domain_label": "Media Player",
    },
    "Lights On": {
        "domain": "light",
        "kind": "light_on",
        "domain_label": "Light",
    },
    "Lights Off": {
        "domain": "light",
        "kind": "light_off",
        "domain_label": "Light",
    },
    "Lights Up": {
        "domain": "light",
        "kind": "light_up",
        "domain_label": "Light",
    },
    "Lights Down": {
        "domain": "light",
        "kind": "light_down",
        "domain_label": "Light",
    },
    "Fan On": {
        "domain": "fan",
        "kind": "fan_on",
        "domain_label": "Fan",
    },
    "Fan Off": {
        "domain": "fan",
        "kind": "fan_off",
        "domain_label": "Fan",
    },
    "Fan Up": {
        "domain": "fan",
        "kind": "fan_up",
        "domain_label": "Fan",
    },
    "Fan Down": {
        "domain": "fan",
        "kind": "fan_down",
        "domain_label": "Fan",
    },
}

# Leader label
LABEL_FEATURE_LEADER: Final = "Feature Leader"

# Label name patterns for modifier labels (should be filtered from feature list)
MODIFIER_LABEL_KEYWORDS: Final = (
    "Component:", "Min:", "Max:", "Step:", "Unit:", "Icon:",
    "Initial:", "Static:", "Mode:", "Device Class:",
)

# Event types
EVENT_LABELED_FEATURE_SET: Final = "labeled_feature_set"
EVENT_LABELED_FEATURE_SNAPSHOT_SET: Final = "labeled_feature_snapshot_set"

# State change gate values
STATE_UNAVAILABLE: Final = ("unknown", "unavailable", "none")
STATE_TRUTHY: Final = ("on", "true", "home", "open", "detected", "active", "unlocked")
BUTTON_DOMAINS: Final = ("event", "button")

# Feature modes
MODE_LEADER: Final = "leader"
MODE_ANY: Final = "any"
MODE_ALL: Final = "all"
FEATURE_MODES: Final = (MODE_LEADER, MODE_ANY, MODE_ALL)

# Scope values
SCOPE_AREA: Final = "area"
SCOPE_FLOOR: Final = "floor"
SCOPE_GLOBAL: Final = "global"

# Component defaults
COMPONENT_DEFAULT: Final = "select"

# Label map key separator
LABEL_MAP_SEPARATOR: Final = "||"