"""Constants for the Labeled Features integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import Final

DOMAIN: Final = "labeled_features"

# ── Config-entry option keys ─────────────────────────────────────────────
CONF_INSTANCE_NAME: Final = "instance_name"
CONF_FEATURES_ENTITY_ID: Final = "features_entity_id"
CONF_AREAS_ENTITY_ID: Final = "areas_entity_id"
CONF_LEADER_LABEL: Final = "leader_label"
CONF_ERROR_MODE: Final = "error_mode"
CONF_ALERT_ACTION: Final = "alert_action"
CONF_SCRIPT_CALL_MODE: Final = "script_call_mode"

# ── Defaults ─────────────────────────────────────────────────────────────
DEFAULT_INSTANCE_NAME: Final = "Labeled Features"
DEFAULT_FEATURES_ENTITY_ID: Final = "sensor.labeled_features_state"
DEFAULT_AREAS_ENTITY_ID: Final = "sensor.labeled_feature_areas_state"
DEFAULT_LEADER_LABEL: Final = "Feature Leader"
DEFAULT_ERROR_MODE: Final = "log"
DEFAULT_ALERT_ACTION: Final = "script.send_alert"
DEFAULT_SCRIPT_CALL_MODE: Final = "Blocking"

# ── Error tiers ──────────────────────────────────────────────────────────
ERROR_MODES: Final = ("silent", "log", "alert", "stop")
SCRIPT_CALL_MODES: Final = ("Blocking", "NonBlocking")

# ── Compat event names (kept identical to legacy YAML template sensors) ──
EVENT_FEATURE_SET: Final = "labeled_feature_set"
EVENT_SNAPSHOT_SET: Final = "labeled_feature_snapshot_set"

# ── New services (write to the same internal path as the events) ────────
SERVICE_SET_FEATURE: Final = "set_feature"
SERVICE_SET_SNAPSHOT: Final = "set_snapshot"

# ── Truthy state values for the default per-leader truth function ────────
TRUTHY_STATES: Final = frozenset(
    {"on", "true", "home", "open", "detected", "active", "unlocked"}
)

# ── Skip values that don't update the leader's current_value ─────────────
UNKNOWN_STATES: Final = frozenset({"unknown", "unavailable", "none"})

# ── The generic-feature catalog. Byte-identical to the current YAML. ────
# Adding a new domain grouping is a one-line edit here.
FEATURE_META: Final[dict[str, dict[str, str]]] = {
    "Media Toggle": {"domain": "media_player", "kind": "media_toggle", "domain_label": "Media Player"},
    "Media Play": {"domain": "media_player", "kind": "media_play", "domain_label": "Media Player"},
    "Media Pause": {"domain": "media_player", "kind": "media_pause", "domain_label": "Media Player"},
    "Media Next": {"domain": "media_player", "kind": "media_next", "domain_label": "Media Player"},
    "Media Previous": {"domain": "media_player", "kind": "media_previous", "domain_label": "Media Player"},
    "Media Seek Back": {"domain": "media_player", "kind": "media_seek_back", "domain_label": "Media Player"},
    "Media Seek Forward": {"domain": "media_player", "kind": "media_seek_forward", "domain_label": "Media Player"},
    "Volume Up": {"domain": "media_player", "kind": "volume_up", "domain_label": "Media Player"},
    "Volume Down": {"domain": "media_player", "kind": "volume_down", "domain_label": "Media Player"},
    "Lights On": {"domain": "light", "kind": "light_on", "domain_label": "Light"},
    "Lights Off": {"domain": "light", "kind": "light_off", "domain_label": "Light"},
    "Lights Up": {"domain": "light", "kind": "light_up", "domain_label": "Light"},
    "Lights Down": {"domain": "light", "kind": "light_down", "domain_label": "Light"},
    "Fan On": {"domain": "fan", "kind": "fan_on", "domain_label": "Fan"},
    "Fan Off": {"domain": "fan", "kind": "fan_off", "domain_label": "Fan"},
    "Fan Up": {"domain": "fan", "kind": "fan_up", "domain_label": "Fan"},
    "Fan Down": {"domain": "fan", "kind": "fan_down", "domain_label": "Fan"},
}

# ── Scope prefixes ───────────────────────────────────────────────────────
SCOPE_AREA: Final = "area"
SCOPE_FLOOR: Final = "floor"
SCOPE_GLOBAL: Final = "global"
SCOPE_NONE: Final = "none"

# Set of area-features modifier keywords used to skip labels that aren't
# themselves feature declarations (mirrors the YAML regex in
# `sensor.labeled_feature_areas_state.label_map`).
PROVIDES_MODIFIER_KEYWORDS: Final = frozenset(
    {"Component", "Min", "Max", "Step", "Unit", "Icon", "Initial", "Static", "Mode", "Device Class"}
)

# Storage keys for RestoreEntity extra data
STORAGE_KEY_LEADERS: Final = "leaders"
STORAGE_KEY_FEATURES: Final = "features"
STORAGE_KEY_SNAPSHOTS: Final = "snapshots"
STORAGE_KEY_LABEL_MAP: Final = "label_map"
