"""DataUpdateCoordinator for Labeled Features.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging
import re
from collections.abc import Callable
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import Event, HomeAssistant, State, callback
from homeassistant.helpers import area_registry as ar
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers import label_registry as label_helper
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator

from .const import (
    BUTTON_DOMAINS,
    COMPONENT_DEFAULT,
    CONF_ENTITY_ID_SUFFIX,
    DEFAULT_FEATURE_LEADER_LABEL,
    EVENT_LABELED_FEATURE_SET,
    EVENT_LABELED_FEATURE_SNAPSHOT_SET,
    FEATURE_META,
    FEATURE_MODES,
    LABEL_MAP_SEPARATOR,
    MODE_ALL,
    MODE_ANY,
    MODE_LEADER,
    MODIFIER_LABEL_KEYWORDS,
    SCOPE_AREA,
    SCOPE_FLOOR,
    SCOPE_GLOBAL,
    STATE_TRUTHY,
    STATE_UNAVAILABLE,
)

_LOGGER = logging.getLogger(__name__)


class LabeledFeaturesCoordinator(DataUpdateCoordinator[dict]):
    """Coordinator for Labeled Features sensors."""

    config_entry: ConfigEntry

    def __init__(
        self,
        hass: HomeAssistant,
        entry: ConfigEntry,
    ) -> None:
        """Initialize coordinator."""
        super().__init__(
            hass,
            _LOGGER,
            name="labeled_features",
            config_entry=entry,
        )
        self._entry = entry
        self._bus_listeners: list[Callable[[], None]] = []
        self._features: dict[str, Any] = {}
        self._label_map: dict[str, Any] = {}
        self._snapshots: dict[str, Any] = {}
        self._leaders: dict[str, Any] = {}

    @property
    def feature_leader_label(self) -> str:
        """Return the configured feature leader label name."""
        from .const import CONF_FEATURE_LEADER_LABEL, DEFAULT_FEATURE_LEADER_LABEL
        return self._entry.data.get(
            CONF_FEATURE_LEADER_LABEL, DEFAULT_FEATURE_LEADER_LABEL
        )

    def _build_coordinator_data(self) -> dict:
        """Build coordinator data dict for sensors."""
        return {
            "feature_meta": self.feature_meta,
            "leaders": self._leaders,
            "features": self._features,
            "snapshots": self._snapshots,
            "label_map": self._label_map,
        }

    @property
    def feature_meta(self) -> dict:
        """Return the feature catalog."""
        return FEATURE_META

    @property
    def features(self) -> dict:
        """Return current features state."""
        return self._features

    @property
    def label_map(self) -> dict:
        """Return current label map."""
        return self._label_map

    @property
    def snapshots(self) -> dict:
        """Return current snapshots."""
        return self._snapshots

    @property
    def leaders(self) -> dict:
        """Return current leaders state."""
        return self._leaders

    # ------------------------------------------------------------------
    # Setup / teardown
    # ------------------------------------------------------------------

    async def async_setup(self) -> None:
        """Set up event listeners and perform initial build."""
        self._bus_listeners.append(
            self.hass.bus.async_listen(
                "label_registry_updated", self._on_registry_changed
            )
        )
        self._bus_listeners.append(
            self.hass.bus.async_listen(
                "area_registry_updated", self._on_registry_changed
            )
        )
        self._bus_listeners.append(
            self.hass.bus.async_listen(
                "floor_registry_updated", self._on_registry_changed
            )
        )
        self._bus_listeners.append(
            self.hass.bus.async_listen(
                "entity_registry_updated", self._on_registry_changed
            )
        )
        self._bus_listeners.append(
            self.hass.bus.async_listen(
                "state_changed", self._on_state_changed
            )
        )
        self._bus_listeners.append(
            self.hass.bus.async_listen(
                EVENT_LABELED_FEATURE_SET, self._on_labeled_feature_set
            )
        )
        self._bus_listeners.append(
            self.hass.bus.async_listen(
                EVENT_LABELED_FEATURE_SNAPSHOT_SET,
                self._on_labeled_feature_snapshot_set,
            )
        )
        self._bus_listeners.append(
            self.hass.bus.async_listen(
                "homeassistant_start", self._on_homeassistant_start
            )
        )
        self._build_all()
        self.async_set_updated_data(self._build_coordinator_data())

    @callback
    def async_unload(self) -> None:
        """Clean up listeners."""
        for listener in self._bus_listeners:
            listener()
        self._bus_listeners.clear()

    # ------------------------------------------------------------------
    # Event handlers
    # ------------------------------------------------------------------

    @callback
    def _on_registry_changed(self, _event: Event) -> None:
        """Handle registry change events."""
        self._build_all()
        self.async_set_updated_data(self._build_coordinator_data())

    @callback
    def _on_state_changed(self, event: Event) -> None:
        """Handle state change events for feature leaders (gated)."""
        eid = event.data.get("entity_id", "")
        if not eid:
            return

        old_state = event.data.get("old_state")

        # Gate: reject if entity is not a feature leader AND not a known
        # stale leader (label was removed).
        if not self._is_feature_leader(eid):
            if eid not in self._leaders:
                return
            # Stale leader: label was removed, clean up
            self._leaders.pop(eid, None)
            self._features = self._carry_through(
                self._features,
                self._build_triple_map(
                    self._resolve_label_entities(self.feature_leader_label)
                ),
            )
            self.async_set_updated_data(self._build_coordinator_data())
            return

        # Gate: reject boot-restore noise (no old state or old state was
        # unavailable).
        if old_state is None:
            return
        old_str = str(getattr(old_state, "state", "")).lower()
        if old_str in STATE_UNAVAILABLE:
            return

        new_state = event.data.get("new_state")
        self._update_leader_state(eid, new_state)
        self._process_state_changed(eid, new_state)
        self.async_set_updated_data(self._build_coordinator_data())

    @callback
    def _on_labeled_feature_set(self, event: Event) -> None:
        """Handle manual feature set events."""
        self._features = self._handle_manual_override(
            self._features, event.data
        )
        self.async_set_updated_data(self._build_coordinator_data())

    @callback
    def _on_labeled_feature_snapshot_set(self, event: Event) -> None:
        """Handle snapshot set events."""
        self._handle_snapshot_set(event.data)
        self.async_set_updated_data(self._build_coordinator_data())

    @callback
    def _on_homeassistant_start(self, _event: Event) -> None:
        """Reconcile all state against live registries on boot."""
        self._build_all()
        self.async_set_updated_data(self._build_coordinator_data())

    # ------------------------------------------------------------------
    # Label / registry helpers
    # ------------------------------------------------------------------

    def _is_feature_leader(self, entity_id: str) -> bool:
        """Check if entity carries the feature_leader label."""
        try:
            reg = er.async_get(self.hass)
            entry = reg.async_get(entity_id)
            if entry and entry.labels:
                return self.feature_leader_label in entry.labels
        except Exception:
            pass
        return False

    def _get_entity_label_names(self, entity_id: str) -> list[str]:
        """Get label names for an entity."""
        try:
            reg = er.async_get(self.hass)
            entry = reg.async_get(entity_id)
            if not entry or not entry.labels:
                return []
            return self._resolve_label_ids(entry.labels)
        except Exception:
            return []

    def _get_area_label_names(self, area_id: str) -> list[str]:
        """Get label names attached directly to an area."""
        try:
            areg = ar.async_get(self.hass)
            area = areg.async_get(area_id)
            if not area or not area.labels:
                return []
            return self._resolve_label_ids(area.labels)
        except Exception:
            return []

    def _resolve_label_ids(self, label_ids: set[str]) -> list[str]:
        """Resolve label IDs to their names."""
        try:
            lr = label_helper.async_get(self.hass)
        except Exception:
            return []
        result: list[str] = []
        for lid in label_ids:
            try:
                lbl = lr.async_get(lid)
                if lbl:
                    result.append(lbl.name)
            except Exception:
                continue
        return result

    def _get_area_id(self, entity_id: str) -> str:
        """Get area ID for an entity."""
        try:
            reg = er.async_get(self.hass)
            entry = reg.async_get(entity_id)
            if entry and entry.area_id:
                return entry.area_id
        except Exception:
            pass
        return ""

    def _get_floor_id_for_area(self, area_id: str) -> str:
        """Get floor ID for an area."""
        try:
            areg = ar.async_get(self.hass)
            area = areg.async_get(area_id)
            if area and area.floor_id:
                return area.floor_id
        except Exception:
            pass
        return ""

    def _resolve_label_entities(self, label_name: str) -> list[str]:
        """Resolve entity IDs for a label name."""
        try:
            reg = er.async_get(self.hass)
            lr = label_helper.async_get(self.hass)
        except Exception:
            return []
        result: list[str] = []
        for entry in reg.entities.values():
            if entry.labels:
                for lid in entry.labels:
                    try:
                        lbl = lr.async_get(lid)
                        if lbl and lbl.name == label_name:
                            result.append(entry.entity_id)
                            break
                    except Exception:
                        continue
        return result

    def _resolve_label_areas(self, label_name: str) -> list[str]:
        """Resolve area IDs that have the label directly attached."""
        try:
            areg = ar.async_get(self.hass)
            lr = label_helper.async_get(self.hass)
        except Exception:
            return []
        result: list[str] = []
        for area in areg.async_list_areas():
            if area.labels:
                for lid in area.labels:
                    try:
                        lbl = lr.async_get(lid)
                        if lbl and lbl.name == label_name:
                            result.append(area.id)
                            break
                    except Exception:
                        continue
        return result

    # ------------------------------------------------------------------
    # Build routines
    # ------------------------------------------------------------------

    def _build_all(self) -> None:
        """Rebuild all state from scratch."""
        self._rebuild_leaders()
        self._rebuild_features(None)
        self._rebuild_label_map()

    def _rebuild_leaders(self) -> None:
        """Rebuild leader states from current registry."""
        leader_entities = self._resolve_label_entities(self.feature_leader_label)
        new_leaders: dict[str, Any] = {}
        for eid in leader_entities:
            state_obj = self.hass.states.get(eid)
            if state_obj is None:
                continue
            state_str = state_obj.state
            if state_str.lower() in STATE_UNAVAILABLE:
                continue
            ts = (
                state_obj.last_changed.timestamp()
                if state_obj.last_changed
                else 0
            )
            prev_value = self._leaders.get(eid, {}).get("current_value", "")
            new_leaders[eid] = {
                "current_value": state_str,
                "previous_value": prev_value,
                "last_changed_timestamp": ts,
            }
        self._leaders = new_leaders

    def _update_leader_state(self, entity_id: str, new_state: State | None) -> None:
        """Update a single leader's state."""
        if new_state is None:
            return
        state_str = new_state.state
        prev_data = self._leaders.get(entity_id, {})
        prev_value = prev_data.get("current_value", "")
        ts = (
            new_state.last_changed.timestamp()
            if new_state.last_changed
            else 0
        )
        self._leaders[entity_id] = {
            "current_value": state_str,
            "previous_value": prev_value,
            "last_changed_timestamp": ts,
        }

    # ------------------------------------------------------------------
    # Leader evaluation
    # ------------------------------------------------------------------

    def _eval_leader(
        self,
        eid: str,
        fname: str,
        scope_pfx: str,
        cv: str,
        prev_cv: str,
    ) -> bool:
        """Evaluate whether a leader enables a feature.

        Matches the template sensor's eval_leader macro:
        1. Direction (Increasing/Decreasing) takes precedence
        2. Enable/Disable labels
        3. Default truth (state == feature_name or truthy)
        4. event/button domains always True
        5. Invert applied last
        """
        label_names = self._get_entity_label_names(eid)
        state_obj = self.hass.states.get(eid)
        state_str = state_obj.state if state_obj else ""
        dom = eid.split(".")[0]

        inc_lbl = f"{scope_pfx}{fname} Increasing: True" in label_names
        dec_lbl = f"{scope_pfx}{fname} Decreasing: True" in label_names

        if inc_lbl or dec_lbl:
            cur_n = float(cv) if cv else None
            prev_n = float(prev_cv) if prev_cv else None
            if cur_n is not None and prev_n is not None:
                is_inc = cur_n > prev_n
                is_dec = cur_n < prev_n
                base = (inc_lbl and is_inc) or (dec_lbl and is_dec)
            else:
                base = False
        else:
            en_lbl = ""
            dis_lbl = ""
            for lbl in label_names:
                if lbl.startswith(f"{scope_pfx}{fname} Enable: "):
                    en_lbl = lbl[len(f"{scope_pfx}{fname} Enable: "):].strip()
                if lbl.startswith(f"{scope_pfx}{fname} Disable: "):
                    dis_lbl = lbl[len(f"{scope_pfx}{fname} Disable: "):].strip()
            if en_lbl or dis_lbl:
                by_en = en_lbl and state_str == en_lbl
                by_dis = dis_lbl and state_str == dis_lbl
                if en_lbl and dis_lbl:
                    base = by_en and not by_dis
                elif en_lbl:
                    base = by_en
                else:
                    base = not by_dis
            else:
                if dom in BUTTON_DOMAINS:
                    base = True
                else:
                    base = (state_str == fname) or (
                        state_str.lower() in STATE_TRUTHY
                    )

        inverted = f"{scope_pfx}{fname} Invert: True" in label_names
        return (not base) if inverted else base

    # ------------------------------------------------------------------
    # Feature rebuild
    # ------------------------------------------------------------------

    def _rebuild_features(self, _event_data: dict | None) -> None:
        """Rebuild features state from scratch (full rebuild)."""
        all_leaders = self._resolve_label_entities(self.feature_leader_label)
        triples = self._build_triple_map(all_leaders)
        modes = self._resolve_modes(all_leaders, triples)
        prev_features = self._features

        result: dict[str, Any] = {}
        for key, leaders_list in triples.items():
            parts = key.split(LABEL_MAP_SEPARATOR)
            if len(parts) != 3:
                continue
            fname, scope_val, scope_id_val = parts
            scope_pfx = (
                "Area " if scope_val == SCOPE_AREA
                else ("Floor " if scope_val == SCOPE_FLOOR else "")
            )
            mode = modes.get(key, MODE_LEADER)

            values: list[bool] = []
            triggering_eid = ""
            for eid in leaders_list:
                state_obj = self.hass.states.get(eid)
                if state_obj is None:
                    values.append(False)
                    continue
                cv = state_obj.state
                prev_cv = self._leaders.get(eid, {}).get("previous_value", "")
                truth = self._eval_leader(
                    eid, fname, scope_pfx, cv, prev_cv
                )
                values.append(truth)
                if truth:
                    triggering_eid = eid

            if mode == MODE_LEADER:
                new_enabled = any(values)
            elif mode == MODE_ALL:
                new_enabled = min(values) if values else False
            else:
                new_enabled = max(values) if values else False

            prev_entry = (
                prev_features.get(fname, {})
                .get(scope_val, {})
                .get(scope_id_val, {})
                if isinstance(
                    prev_features.get(fname, {}).get(scope_val, {}), dict
                )
                else {}
            )
            prev_ts = (
                prev_entry.get("last_changed_timestamp", 0)
                if isinstance(prev_entry, dict)
                else 0
            )

            new_entry = {
                "enabled": new_enabled,
                "mode": mode,
                "last_changed_timestamp": prev_ts,
                "triggering_leader": triggering_eid,
            }

            result.setdefault(fname, {}).setdefault(
                scope_val, {}
            )[scope_id_val] = new_entry

        # Carry through manual overrides
        for fname, scopes_map in prev_features.items():
            if not isinstance(scopes_map, dict):
                continue
            for scope_val, sids in scopes_map.items():
                if not isinstance(sids, dict):
                    continue
                for scope_id_val, entry in sids.items():
                    if not isinstance(entry, dict):
                        continue
                    if entry.get("triggering_leader", "") != "":
                        continue
                    key = f"{fname}{LABEL_MAP_SEPARATOR}{scope_val}{LABEL_MAP_SEPARATOR}{scope_id_val}"
                    if key not in triples:
                        result.setdefault(fname, {}).setdefault(
                            scope_val, {}
                        )[scope_id_val] = entry

        self._features = result

    def _process_state_changed(
        self, changed_eid: str, new_state: State | None
    ) -> None:
        """Process a state change for a single leader entity."""
        if new_state is None:
            return

        all_leaders = self._resolve_label_entities(self.feature_leader_label)
        if changed_eid not in all_leaders:
            return

        triples = self._build_triple_map(all_leaders)
        modes = self._resolve_modes(all_leaders, triples)
        prev_features = self._features

        dom = new_state.entity_id.split(".")[0]
        cv_raw = (
            new_state.attributes.get("event_type", new_state.state)
            if dom in ("event", "button")
            else new_state.state
        )
        is_skip = (
            "_initial_press" in cv_raw
            or cv_raw.lower() in STATE_UNAVAILABLE
        )
        if is_skip:
            self._features = self._carry_through(prev_features, triples)
            return

        ts = (
            new_state.last_changed.timestamp()
            if new_state.last_changed
            else 0
        )
        prev_l = self._leaders.get(changed_eid, {})
        prev_cv = prev_l.get("current_value", "")

        result = self._carry_through(prev_features, triples)

        for key, leaders_list in triples.items():
            if changed_eid not in leaders_list:
                continue
            parts = key.split(LABEL_MAP_SEPARATOR)
            if len(parts) != 3:
                continue
            fname, scope_val, scope_id_val = parts
            scope_pfx = (
                "Area " if scope_val == SCOPE_AREA
                else ("Floor " if scope_val == SCOPE_FLOOR else "")
            )
            mode = modes.get(key, MODE_LEADER)

            this_truth = self._eval_leader(
                changed_eid, fname, scope_pfx, cv_raw, prev_cv
            )

            if mode == MODE_LEADER:
                new_enabled = this_truth
            else:
                values: list[bool] = []
                for other_eid in leaders_list:
                    if other_eid == changed_eid:
                        values.append(this_truth)
                    else:
                        other_state = self.hass.states.get(other_eid)
                        other_cv = other_state.state if other_state else ""
                        other_prev = self._leaders.get(
                            other_eid, {}
                        ).get("previous_value", "")
                        other_truth = self._eval_leader(
                            other_eid, fname, scope_pfx, other_cv, other_prev
                        )
                        values.append(other_truth)
                new_enabled = (
                    min(values) if mode == MODE_ALL else max(values)
                )

            existing_f = result.get(fname, {})
            existing_s = existing_f.get(scope_val, {})
            prev_entry = (
                existing_s.get(scope_id_val, {})
                if isinstance(existing_s, dict)
                else {}
            )
            prev_enabled = (
                prev_entry.get("enabled")
                if isinstance(prev_entry, dict)
                else None
            )
            prev_ts = (
                prev_entry.get("last_changed_timestamp", ts)
                if isinstance(prev_entry, dict)
                else ts
            )

            is_button = dom in BUTTON_DOMAINS
            flipped = (
                (prev_enabled is None)
                or (prev_enabled != new_enabled)
                or is_button
            )
            new_ts = ts if flipped else prev_ts

            new_entry = {
                "enabled": new_enabled,
                "mode": mode,
                "last_changed_timestamp": new_ts,
                "triggering_leader": changed_eid,
            }

            result.setdefault(fname, {}).setdefault(
                scope_val, {}
            )[scope_id_val] = new_entry

        self._features = result

    def _build_triple_map(
        self, all_leaders: list[str]
    ) -> dict[str, list[str]]:
        """Build mapping of (feature, scope, scope_id) -> [leader_entity_ids]."""
        triples: dict[str, list[str]] = {}
        for eid in all_leaders:
            label_names = self._get_entity_label_names(eid)
            aid = self._get_area_id(eid)
            fid = self._get_floor_id_for_area(aid) if aid else ""
            for lbl in label_names:
                matched = False
                for prefix, scope_val, scope_id_fn in (
                    ("Area Leader: ", SCOPE_AREA, lambda: aid),
                    ("Floor Leader: ", SCOPE_FLOOR, lambda: fid),
                ):
                    if lbl.startswith(prefix):
                        fname = lbl[len(prefix):].strip()
                        if not fname:
                            continue
                        scope_id_val = scope_id_fn()
                        if not scope_id_val:
                            continue
                        key = f"{fname}{LABEL_MAP_SEPARATOR}{scope_val}{LABEL_MAP_SEPARATOR}{scope_id_val}"
                        triples.setdefault(key, [])
                        if eid not in triples[key]:
                            triples[key].append(eid)
                        matched = True
                        break
                if not matched and lbl.startswith("Leader: "):
                    fname = lbl[len("Leader: "):].strip()
                    if fname:
                        key = f"{fname}{LABEL_MAP_SEPARATOR}{SCOPE_GLOBAL}{LABEL_MAP_SEPARATOR}"
                        triples.setdefault(key, [])
                        if eid not in triples[key]:
                            triples[key].append(eid)
        return triples

    def _resolve_modes(
        self, _all_leaders: list[str], triples: dict[str, list[str]]
    ) -> dict[str, str]:
        """Resolve mode for each (feature, scope, scope_id) triple."""
        modes: dict[str, str] = {}
        for key in triples:
            parts = key.split(LABEL_MAP_SEPARATOR)
            if len(parts) != 3:
                continue
            fname, scope_val, _scope_id_val = parts
            scope_pfx = (
                "Area " if scope_val == SCOPE_AREA
                else ("Floor " if scope_val == SCOPE_FLOOR else "")
            )
            mode_val = MODE_LEADER
            for lbl in self._get_sensor_label_names():
                expected = f"{scope_pfx}{fname} Mode: "
                if lbl.startswith(expected):
                    mv = lbl[len(expected):].strip().lower()
                    if mv in FEATURE_MODES:
                        mode_val = mv
                        break
            modes[key] = mode_val
        return modes

    def _get_sensor_label_names(self) -> list[str]:
        """Get labels on the sensor entity itself."""
        try:
            reg = er.async_get(self.hass)
            suffix = self._entry.data.get(CONF_ENTITY_ID_SUFFIX, "")
            uid = f"labeled_features_state{suffix}"
            entry = reg.async_get_entity_id("sensor", "labeled_features", uid)
            if entry:
                er_entry = reg.async_get(entry)
                if er_entry and er_entry.labels:
                    return self._resolve_label_ids(er_entry.labels)
        except Exception:
            pass
        return []

    def _handle_manual_override(
        self, prev_features: dict, event_data: dict
    ) -> dict:
        """Handle a manual feature set event."""
        tgt = event_data.get("target_feature", "").strip()
        scp = event_data.get("scope", "").lower().strip()
        sid = str(event_data.get("scope_id", ""))
        ena = bool(event_data.get("enabled", False))
        ts = float(event_data.get("timestamp", 0)) or 0

        result = dict(prev_features)
        if tgt and scp in (SCOPE_AREA, SCOPE_FLOOR, SCOPE_GLOBAL):
            existing_f = result.get(tgt, {})
            existing_s = existing_f.get(scp, {})
            prev_entry = (
                existing_s.get(sid, {})
                if isinstance(existing_s, dict)
                else {}
            )
            _mode = (
                prev_entry.get("mode", MODE_LEADER)
                if isinstance(prev_entry, dict)
                else MODE_LEADER
            )
            new_entry = {
                "enabled": ena,
                "mode": _mode,
                "last_changed_timestamp": ts or 0,
                "triggering_leader": "",
            }
            result.setdefault(tgt, {}).setdefault(scp, {})[
                sid
            ] = new_entry
        return result

    def _carry_through(
        self, prev_features: dict, triples: dict[str, list[str]]
    ) -> dict:
        """Carry through existing features, dropping orphans."""
        result: dict[str, Any] = {}
        for fname, scopes_map in prev_features.items():
            if not isinstance(scopes_map, dict):
                continue
            for scope_val, sids in scopes_map.items():
                if not isinstance(sids, dict):
                    continue
                for scope_id_val, entry in sids.items():
                    if not isinstance(entry, dict):
                        continue
                    key = f"{fname}{LABEL_MAP_SEPARATOR}{scope_val}{LABEL_MAP_SEPARATOR}{scope_id_val}"
                    has_leader = key in triples
                    is_manual = entry.get("triggering_leader", "") == ""
                    if has_leader or is_manual:
                        result.setdefault(fname, {}).setdefault(
                            scope_val, {}
                        )[scope_id_val] = entry
        return result

    # ------------------------------------------------------------------
    # Label map
    # ------------------------------------------------------------------

    def _rebuild_label_map(self) -> None:
        """Rebuild the label_map for area-based features."""
        leader_areas = self._resolve_label_areas(self.feature_leader_label)

        scopes: dict[str, dict] = {}
        for aid in leader_areas:
            floor_id = ""
            try:
                areg = ar.async_get(self.hass)
                area = areg.async_get(aid)
                if area and area.floor_id:
                    floor_id = area.floor_id
            except Exception:
                pass
            scopes[aid] = {
                "kind": "area",
                "floor_id": floor_id,
                "labels": {},
            }

        for aid in leader_areas:
            area_lbl_names = self._get_area_label_names(aid)
            floor_id = scopes[aid]["floor_id"]

            for lbl in area_lbl_names:
                m = re.match(
                    r"^(Area|Floor|)Provides:\s*(.+)$", lbl
                )
                if not m:
                    continue

                prefix = m.group(1)
                lname = m.group(2).strip()
                if not lname:
                    continue

                is_modifier = any(
                    lname.endswith(kw) or (
                        f" {kw}" in lname
                    )
                    for kw in MODIFIER_LABEL_KEYWORDS
                )
                if is_modifier:
                    continue

                scope_val = (
                    SCOPE_AREA if prefix == "Area"
                    else (SCOPE_FLOOR if prefix == "Floor" else "none")
                )
                scope_id_val = (
                    aid
                    if scope_val in (SCOPE_AREA, "none")
                    else floor_id
                )
                if not scope_id_val:
                    continue

                scope_prefix = (
                    "Area " if scope_val == SCOPE_AREA
                    else ("Floor " if scope_val == SCOPE_FLOOR else "")
                )
                comp_override = ""
                comp_pat = (
                    f"{scope_prefix}Provides {lname} Component: "
                )
                for lbl2 in area_lbl_names:
                    if lbl2.startswith(comp_pat):
                        comp_override = lbl2[len(comp_pat):].strip()
                        break

                component = comp_override or COMPONENT_DEFAULT

                lentry = {
                    "scope": scope_val,
                    "scope_id": scope_id_val,
                    "component": component,
                    "declaring_area_id": aid,
                }

                if scope_id_val not in scopes:
                    scopes[scope_id_val] = {
                        "kind": "floor",
                        "floor_id": scope_id_val,
                        "labels": {},
                    }

                if lname not in scopes[scope_id_val].get("labels", {}):
                    scopes[scope_id_val]["labels"][lname] = lentry

        label_map: dict[str, Any] = {}
        for sid, sdat in scopes.items():
            for lname, ldat in sdat.get("labels", {}).items():
                key = f"{sid}{LABEL_MAP_SEPARATOR}{lname}"
                label_map[key] = {
                    "scope_id": sid,
                    "label": lname,
                    "scope": ldat.get("scope", SCOPE_AREA),
                    "component": ldat.get("component"),
                    "declaring_area_id": ldat.get("declaring_area_id"),
                    "label_data": ldat,
                }

        self._label_map = label_map

    # ------------------------------------------------------------------
    # Snapshots
    # ------------------------------------------------------------------

    def _handle_snapshot_set(self, event_data: dict) -> None:
        """Handle a snapshot set event."""
        sname = event_data.get("snapshot_name", "").strip()
        payload_raw = event_data.get("payload")
        if not sname:
            return
        if payload_raw is None or (
            isinstance(payload_raw, dict) and len(payload_raw) == 0
        ):
            self._snapshots.pop(sname, None)
        elif isinstance(payload_raw, dict):
            self._snapshots[sname] = payload_raw