"""Coordinators for the Labeled Features integration.

Event-driven (push) coordinators holding the two sensors' state. They listen
to the same event surface the legacy trigger-based template sensors used:

  FeaturesCoordinator — state_changed (feature_leader ∪ subentry leaders,
    with the legacy boot-noise gate), labeled_feature_set,
    labeled_feature_snapshot_set; registry events refresh the leader cache.
  AreasCoordinator — label/area/floor registry updates + homeassistant.start.

Recomputation runs through the pure functions in engine.py; errors route
through error_handler (self-clearing Repair issues).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

from homeassistant.core import Event, HomeAssistant
from homeassistant.helpers import (
    area_registry as ar,
    device_registry as dr,
    entity_registry as er,
    floor_registry as fr,  # noqa: F401  (kept for parity w/ registry surface)
    label_registry as lr,
)
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator
from homeassistant.util import dt as dt_util

from . import engine
from .const import (
    AREAS_SENSOR_STEM,
    DOMAIN,
    EVENT_LABELED_FEATURE_SET,
    EVENT_LABELED_FEATURE_SNAPSHOT_SET,
    FEATURES_SENSOR_STEM,
    LABEL_FEATURE_LEADER,
    SKIP_STATES,
    SUBCONF_AREA_ID,
    SUBCONF_ENTITY_ID,
    SUBENTRY_TYPE_LEADER,
    SUBENTRY_TYPE_MODE,
    SUBENTRY_TYPE_PROVIDES,
)
from .error_handler import async_clear_issue, async_route_error

if TYPE_CHECKING:
    from homeassistant.config_entries import ConfigEntry

_LOGGER = logging.getLogger(__name__)

EVENT_STATE_CHANGED = "state_changed"
EVENT_HOMEASSISTANT_START = "homeassistant_start"
REGISTRY_EVENTS = (
    "label_registry_updated",
    "entity_registry_updated",
    "device_registry_updated",
    "area_registry_updated",
    "floor_registry_updated",
)
AREAS_REGISTRY_EVENTS = (
    "label_registry_updated",
    "area_registry_updated",
    "floor_registry_updated",
)


def _resolve_label_id(hass: HomeAssistant, name_or_id: str) -> str | None:
    """Resolve a label name or id to its label_id."""
    registry = lr.async_get(hass)
    if registry.async_get_label(name_or_id):
        return name_or_id
    for label in registry.async_list_labels():
        if label.name == name_or_id:
            return label.label_id
    return None


def _labeled_entity_ids(hass: HomeAssistant, label_name: str) -> list[str]:
    """Entities carrying the given label."""
    label_id = _resolve_label_id(hass, label_name)
    if label_id is None:
        return []
    return [
        entry.entity_id
        for entry in er.async_entries_for_label(er.async_get(hass), label_id)
    ]


def _label_names(hass: HomeAssistant, label_ids: Any) -> list[str]:
    """Resolve label ids to label names (skipping missing)."""
    registry = lr.async_get(hass)
    names: list[str] = []
    for label_id in label_ids or ():
        label = registry.async_get_label(label_id)
        if label is not None and label.name:
            names.append(label.name)
    return names


def _entity_label_names(hass: HomeAssistant, entity_id: str) -> list[str]:
    """Label names on an entity registry entry."""
    entity_entry = er.async_get(hass).async_get(entity_id)
    if entity_entry is None:
        return []
    return _label_names(hass, entity_entry.labels)


def _entity_area_floor(hass: HomeAssistant, entity_id: str) -> tuple[str, str]:
    """Resolve an entity's (area_id, floor_id) with device fallback."""
    entity_entry = er.async_get(hass).async_get(entity_id)
    area_id = ""
    if entity_entry is not None:
        if entity_entry.area_id:
            area_id = entity_entry.area_id
        elif entity_entry.device_id:
            device = dr.async_get(hass).async_get(entity_entry.device_id)
            if device is not None and device.area_id:
                area_id = device.area_id
    floor_id = ""
    if area_id:
        area = ar.async_get(hass).async_get_area(area_id)
        if area is not None and area.floor_id:
            floor_id = area.floor_id
    return area_id, floor_id


def _leader_value_from_state(state: Any) -> str:
    """Leader value accessor: event.* entities use the event_type attribute."""
    if state is None:
        return ""
    if state.entity_id.split(".")[0] == "event":
        event_type = state.attributes.get("event_type")
        if event_type is not None:
            return str(event_type)
    return str(state.state)


def _state_timestamp(state: Any) -> float:
    """last_changed timestamp with dt_util fallback (Iron Law #1)."""
    if state is not None and state.last_changed is not None:
        return state.last_changed.timestamp()
    return dt_util.utcnow().timestamp()


class FeaturesCoordinator(DataUpdateCoordinator[None]):
    """Coordinator for the Labeled Features State sensor."""

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry, suffix: str) -> None:
        """Initialize the coordinator."""
        super().__init__(
            hass,
            _LOGGER,
            name=f"{DOMAIN}_{entry.entry_id}_features",
            config_entry=entry,
        )
        self.entry = entry
        self.suffix = suffix
        self.sensor_entity_id = f"sensor.{FEATURES_SENSOR_STEM}{suffix}"
        self.leaders: dict[str, Any] = {}
        self.features: dict[str, Any] = {}
        self.snapshots: dict[str, Any] = {}
        self.leader_set: set[str] = set()
        self._active_issue_keys: set[str] = set()

    # ── setup / listeners ───────────────────────────────────────────────────

    async def async_setup(self) -> None:
        """Register event listeners (auto-removed on unload)."""
        entry = self.entry
        self._refresh_leader_set()
        entry.async_on_unload(
            self.hass.bus.async_listen(EVENT_STATE_CHANGED, self._on_state_changed)
        )
        entry.async_on_unload(
            self.hass.bus.async_listen(
                EVENT_LABELED_FEATURE_SET, self._on_labeled_feature_set
            )
        )
        entry.async_on_unload(
            self.hass.bus.async_listen(
                EVENT_LABELED_FEATURE_SNAPSHOT_SET, self._on_snapshot_set
            )
        )
        for event_type in REGISTRY_EVENTS:
            entry.async_on_unload(
                self.hass.bus.async_listen(event_type, self._on_registry_updated)
            )

    def _subentries(self, subentry_type: str) -> list[dict[str, Any]]:
        """Data dicts of this entry's subentries of the given type."""
        return [
            dict(sub.data)
            for sub in self.entry.subentries.values()
            if sub.subentry_type == subentry_type
        ]

    def _refresh_leader_set(self) -> None:
        """Leader set = feature_leader label entities ∪ subentry entities."""
        leaders = set(_labeled_entity_ids(self.hass, LABEL_FEATURE_LEADER))
        for data in self._subentries(SUBENTRY_TYPE_LEADER):
            if eid := str(data.get(SUBCONF_ENTITY_ID, "") or "").strip():
                leaders.add(eid)
        self.leader_set = leaders

    # ── event handlers ──────────────────────────────────────────────────────

    async def _on_state_changed(self, event: Event) -> None:
        """Handle state_changed for leader entities (legacy boot-noise gate)."""
        entity_id = str(event.data.get("entity_id", ""))
        if entity_id not in self.leader_set:
            return
        old_state = event.data.get("old_state")
        if old_state is None:
            return
        if str(old_state.state).lower() in SKIP_STATES:
            return
        new_state = event.data.get("new_state")
        self._recompute(
            changed_eid=entity_id,
            cv_raw=_leader_value_from_state(new_state),
            changed_ts=_state_timestamp(new_state),
            new_state_str=str(new_state.state) if new_state is not None else None,
        )

    async def _on_labeled_feature_set(self, event: Event) -> None:
        """Handle the compat manual-override event."""
        data = event.data
        timestamp = dt_util.utcnow().timestamp()
        try:
            timestamp = float(data.get("timestamp", timestamp))
        except (TypeError, ValueError):
            pass
        self._recompute(
            manual={
                "target_feature": str(data.get("target_feature", "") or "").strip(),
                "scope": str(data.get("scope", "") or "").strip().lower(),
                "scope_id": str(data.get("scope_id", "") or ""),
                "enabled": data.get("enabled", False),
                "timestamp": timestamp,
            }
        )

    async def _on_snapshot_set(self, event: Event) -> None:
        """Handle the compat snapshot event."""
        self._recompute(
            snapshot_name=str(event.data.get("snapshot_name", "") or ""),
            snapshot_payload=event.data.get("payload"),
        )

    async def _on_registry_updated(self, event: Event) -> None:
        """Registry change: refresh the leader cache (no feature recompute).

        Legacy parity: orphan entries drop on the next leader-driven tick,
        not immediately.
        """
        self._refresh_leader_set()

    # ── recompute ───────────────────────────────────────────────────────────

    def _get_live_state(self, entity_id: str) -> str:
        """Live state for an entity ('unknown' when missing)."""
        state = self.hass.states.get(entity_id)
        return state.state if state is not None else "unknown"

    def _seed_info(self, entity_id: str) -> tuple[str, float]:
        """Seed value + timestamp for a newly-seen leader."""
        state = self.hass.states.get(entity_id)
        if state is None:
            return "unknown", 0.0
        return state.state, _state_timestamp(state)

    def _recompute(
        self,
        *,
        changed_eid: str | None = None,
        cv_raw: str | None = None,
        changed_ts: float | None = None,
        new_state_str: str | None = None,
        manual: dict[str, Any] | None = None,
        snapshot_name: str | None = None,
        snapshot_payload: Any = None,
    ) -> None:
        """Recompute leaders/features/snapshots via the engine."""
        hass = self.hass
        self._refresh_leader_set()
        all_leader_ids = sorted(self.leader_set)

        labeled_leaders = {
            eid: _entity_label_names(hass, eid) for eid in all_leader_ids
        }
        entity_ctx = {
            eid: dict(zip(("area_id", "floor_id"), _entity_area_floor(hass, eid)))
            for eid in all_leader_ids
        }

        defs, def_errors = engine.build_leader_defs(
            labeled_leaders=labeled_leaders,
            leader_subentries=self._subentries(SUBENTRY_TYPE_LEADER),
            entity_ctx=entity_ctx,
        )
        triples = engine.build_triples(defs)
        modes = engine.resolve_modes(
            triple_keys=list(triples.keys()),
            mode_subentries=self._subentries(SUBENTRY_TYPE_MODE),
            sensor_label_names=_entity_label_names(hass, self.sensor_entity_id),
        )

        new_leaders = engine.update_leaders(
            prev=self.leaders,
            all_leader_ids=all_leader_ids,
            changed_eid=changed_eid,
            cv_raw=cv_raw,
            changed_ts=changed_ts,
            seed_fn=self._seed_info,
        )
        new_features = engine.update_features(
            prev_features=self.features,
            prev_leaders=self.leaders,
            defs=defs,
            triples=triples,
            modes=modes,
            get_state=self._get_live_state,
            changed_eid=changed_eid,
            cv_raw=cv_raw,
            new_state_str=new_state_str,
            changed_ts=changed_ts,
            manual=manual,
        )
        new_snapshots = engine.update_snapshots(
            prev=self.snapshots,
            snapshot_name=snapshot_name,
            payload=snapshot_payload,
        )

        self.leaders = new_leaders
        self.features = new_features
        self.snapshots = new_snapshots

        self._route_errors(def_errors)
        self.async_set_updated_data(None)

    def apply_manual(self, manual: dict[str, Any]) -> None:
        """Apply a validated manual override (set_feature action)."""
        self._recompute(manual=manual)

    def apply_snapshot(self, snapshot_name: str, payload: Any) -> None:
        """Apply a snapshot write (set_snapshot action)."""
        self._recompute(snapshot_name=snapshot_name, snapshot_payload=payload)

    def seed_from_restore(
        self,
        *,
        leaders: Any,
        features: Any,
        snapshots: Any,
    ) -> None:
        """Seed state from restored attributes (only when empty)."""
        if not self.leaders and isinstance(leaders, dict):
            self.leaders = leaders
        if not self.features and isinstance(features, dict):
            self.features = features
        if not self.snapshots and isinstance(snapshots, dict):
            self.snapshots = snapshots

    def _route_errors(self, errors: list[engine.EngineError]) -> None:
        """Route engine errors through the error handler (self-clearing)."""
        new_keys = {err.key for err in errors}
        for key in self._active_issue_keys - new_keys:
            async_clear_issue(self.hass, self.entry, key)
        self._active_issue_keys = new_keys
        for err in errors:
            self.entry.async_create_background_task(
                self.hass,
                async_route_error(
                    self.hass,
                    self.entry,
                    key=err.key,
                    message=err.message,
                    source="Labeled Features State",
                ),
                name=f"{DOMAIN}_route_error",
            )


class AreasCoordinator(DataUpdateCoordinator[None]):
    """Coordinator for the Labeled Feature Areas State sensor."""

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry, suffix: str) -> None:
        """Initialize the coordinator."""
        super().__init__(
            hass,
            _LOGGER,
            name=f"{DOMAIN}_{entry.entry_id}_areas",
            config_entry=entry,
        )
        self.entry = entry
        self.suffix = suffix
        self.sensor_entity_id = f"sensor.{AREAS_SENSOR_STEM}{suffix}"
        self.label_map: dict[str, Any] = {}
        self.gated_area_count: int = 0
        self._active_issue_keys: set[str] = set()

    async def async_setup(self) -> None:
        """Register listeners and build the initial label_map."""
        entry = self.entry
        for event_type in AREAS_REGISTRY_EVENTS:
            entry.async_on_unload(
                self.hass.bus.async_listen(event_type, self._on_registry_updated)
            )
        entry.async_on_unload(
            self.hass.bus.async_listen(EVENT_HOMEASSISTANT_START, self._on_start)
        )
        self._recompute()

    def _subentries(self, subentry_type: str) -> list[dict[str, Any]]:
        """Data dicts of this entry's subentries of the given type."""
        return [
            dict(sub.data)
            for sub in self.entry.subentries.values()
            if sub.subentry_type == subentry_type
        ]

    async def _on_registry_updated(self, event: Event) -> None:
        """Registry change rebuilds the label_map (legacy trigger parity)."""
        self._recompute()

    async def _on_start(self, event: Event) -> None:
        """homeassistant.start rebuild (restart resilience)."""
        self._recompute()

    def _gated_areas(self) -> list[dict[str, Any]]:
        """Areas carrying feature_leader ∪ provides-subentry areas."""
        hass = self.hass
        area_registry = ar.async_get(hass)
        gated: dict[str, dict[str, Any]] = {}
        if (label_id := _resolve_label_id(hass, LABEL_FEATURE_LEADER)) is not None:
            for area in ar.async_entries_for_label(area_registry, label_id):
                gated[area.id] = {
                    "area_id": area.id,
                    "floor_id": area.floor_id or "",
                    "labels": _label_names(hass, area.labels),
                }
        for data in self._subentries(SUBENTRY_TYPE_PROVIDES):
            aid = str(data.get(SUBCONF_AREA_ID, "") or "").strip()
            if not aid or aid in gated:
                continue
            area = area_registry.async_get_area(aid)
            if area is None:
                continue
            gated[aid] = {
                "area_id": area.id,
                "floor_id": area.floor_id or "",
                "labels": _label_names(hass, area.labels),
            }
        return list(gated.values())

    def _recompute(self) -> None:
        """Rebuild label_map via the engine."""
        gated = self._gated_areas()
        area_registry = ar.async_get(self.hass)
        provides_subs: list[dict[str, Any]] = []
        for data in self._subentries(SUBENTRY_TYPE_PROVIDES):
            aid = str(data.get(SUBCONF_AREA_ID, "") or "").strip()
            floor_id = ""
            if aid and (area := area_registry.async_get_area(aid)) is not None:
                floor_id = area.floor_id or ""
            provides_subs.append({**data, "_floor_id": floor_id})

        label_map, errors = engine.build_label_map(
            gated_areas=gated,
            provides_subentries=provides_subs,
        )
        self.label_map = label_map
        self.gated_area_count = len(gated)

        new_keys = {err.key for err in errors}
        for key in self._active_issue_keys - new_keys:
            async_clear_issue(self.hass, self.entry, key)
        self._active_issue_keys = new_keys
        for err in errors:
            self.entry.async_create_background_task(
                self.hass,
                async_route_error(
                    self.hass,
                    self.entry,
                    key=err.key,
                    message=err.message,
                    source="Labeled Feature Areas State",
                ),
                name=f"{DOMAIN}_route_error",
            )

        self.async_set_updated_data(None)

    def seed_label_map(self, label_map: Any) -> None:
        """Seed the label_map from restored attributes (only when empty)."""
        if not self.label_map and isinstance(label_map, dict):
            self.label_map = label_map
