"""Pure evaluation engine for the Labeled Features integration.

This module is a 1:1 Python port of the Jinja logic that lived in the two
legacy trigger-based template sensors (configuration.yaml). It is deliberately
hass-free: every function takes plain data structures and callbacks so the
behavior is reviewable and testable in isolation.

Parity reference:
  - sensor.labeled_features_state   (configuration.yaml lines 214-693)
  - sensor.labeled_feature_areas_state (configuration.yaml lines 67-187)
  - docs: CuratedForest.com/content/tech/home-assistant/label-based-features/

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import re
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from typing import Any

from .const import (
    DIRECTION_BOTH,
    DIRECTION_DECREASING,
    DIRECTION_INCREASING,
    DIRECTION_NONE,
    FOLD_MODES,
    ISSUE_LEADER_NO_AREA,
    ISSUE_LEADER_NO_FLOOR,
    ISSUE_PROVIDES_NO_FLOOR,
    MODE_ALL,
    MODE_LEADER,
    MOMENTARY_DOMAINS,
    PROVIDES_MODIFIER_KEYWORDS,
    SCOPE_AREA,
    SCOPE_FLOOR,
    SCOPE_GLOBAL,
    SCOPE_NONE,
    SKIP_STATES,
    SKIP_SUFFIX,
    SUBCONF_AREA_ID,
    SUBCONF_COMPONENT,
    SUBCONF_DIRECTION,
    SUBCONF_DISABLE_VALUE,
    SUBCONF_ENABLE_VALUE,
    SUBCONF_ENTITY_ID,
    SUBCONF_FEATURE,
    SUBCONF_INVERT,
    SUBCONF_MODE,
    SUBCONF_SCOPE,
    TRUTHY_STATES,
)

# ── Label grammar ────────────────────────────────────────────────────────────

LEADER_LABEL_RE = re.compile(r"^(Area |Floor |)Leader: (.+)$")
PROVIDES_LABEL_RE = re.compile(r"^(Area |Floor |)Provides: (.+)$")
MODE_LABEL_RE = re.compile(r"^(Area |Floor |)(.+) Mode: (Leader|Any|All)$")
# Modifier labels must not register as features in the label_map. Mirrors the
# legacy regex: ^[^:]+ (Component|Min|Max|Step|Unit|Icon|Initial|Static|Mode|Device Class): _
_PROVIDES_MODIFIER_RE = re.compile(
    r"^[^:]+ (" + "|".join(PROVIDES_MODIFIER_KEYWORDS) + r"): "
)

SCOPE_PREFIXES = {SCOPE_AREA: "Area ", SCOPE_FLOOR: "Floor ", SCOPE_GLOBAL: ""}


def scope_prefix(scope: str) -> str:
    """Return the label prefix for a scope ('Area ' / 'Floor ' / '')."""
    return SCOPE_PREFIXES.get(scope, "")


def _value_after_last_colon(label: str) -> str:
    """Replicate the legacy `regex_replace('^.+: ', '')` greedy behavior.

    The legacy pattern `.+: ` is greedy, so it consumes up to the LAST ': '
    in the label. For ordinary labels this is the value after the single
    colon; for values containing ': ' it keeps only the trailing segment.
    """
    return label.rsplit(": ", 1)[-1].strip()


def _is_skip_value(value: str) -> bool:
    """Skip-values: *_initial_press, unknown/unavailable/none."""
    return value.endswith(SKIP_SUFFIX) or value.lower() in SKIP_STATES


def _to_float(value: Any) -> float | None:
    """Best-effort float conversion (None when not numeric)."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def as_bool(value: Any, default: bool = False) -> bool:
    """Replicate HA's `| bool(default)` Jinja filter.

    Strings go through strtobool semantics ('true/on/yes/1' vs
    'false/off/no/0'); unrecognized values fall back to the default. This
    matters because the legacy labeled_feature_set event carries the enabled
    flag as a rendered string ('True' / 'False').
    """
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return value != 0
    if isinstance(value, str):
        lowered = value.strip().lower()
        if lowered in ("true", "on", "yes", "1", "enable", "enabled"):
            return True
        if lowered in ("false", "off", "no", "0", "disable", "disabled"):
            return False
    return default


# ── Leader definitions ───────────────────────────────────────────────────────


@dataclass(frozen=True)
class LeaderDef:
    """A resolved (entity, feature, scope) leader definition.

    Combines the triple location with the modifier configuration used by
    eval_leader. `source` records whether the definition came from labels or
    from a config subentry (subentries win on conflict).
    """

    entity_id: str
    feature: str
    scope: str  # area | floor | global
    scope_id: str  # area_id / floor_id / '' for global
    source: str  # 'label' | 'subentry'
    increasing: bool = False
    decreasing: bool = False
    enable: str | None = None
    disable: str | None = None
    invert: bool = False

    @property
    def triple_key(self) -> str:
        """The (feature, scope, scope_id) triple key."""
        return f"{self.feature}||{self.scope}||{self.scope_id}"


@dataclass
class EngineError:
    """A routable error produced by the engine."""

    key: str
    message: str
    context: dict[str, Any] = field(default_factory=dict)


def extract_label_modifiers(
    label_names: list[str], feature: str, scope: str
) -> dict[str, Any]:
    """Extract eval modifiers for (feature, scope) from an entity's labels.

    Mirrors the legacy label shapes (all case-sensitive):
      <pfx><F> Increasing: True   <pfx><F> Decreasing: True
      <pfx><F> Enable: <v>        <pfx><F> Disable: <v>
      <pfx><F> Invert: True
    """
    pfx = scope_prefix(scope)
    head = f"{pfx}{feature}"
    enable: str | None = None
    disable: str | None = None
    for lbl in label_names:
        if lbl.startswith(f"{head} Enable: ") and len(lbl) > len(f"{head} Enable: "):
            if enable is None:  # legacy takes the FIRST match
                enable = _value_after_last_colon(lbl)
        elif lbl.startswith(f"{head} Disable: ") and len(lbl) > len(
            f"{head} Disable: "
        ):
            if disable is None:
                disable = _value_after_last_colon(lbl)
    return {
        "increasing": f"{head} Increasing: True" in label_names,
        "decreasing": f"{head} Decreasing: True" in label_names,
        "enable": enable,
        "disable": disable,
        "invert": f"{head} Invert: True" in label_names,
    }


def subentry_modifiers(data: Mapping[str, Any]) -> dict[str, Any]:
    """Normalize a leader subentry's data into eval modifiers."""
    direction = data.get(SUBCONF_DIRECTION, DIRECTION_NONE)
    enable = (data.get(SUBCONF_ENABLE_VALUE) or "").strip()
    disable = (data.get(SUBCONF_DISABLE_VALUE) or "").strip()
    return {
        "increasing": direction in (DIRECTION_INCREASING, DIRECTION_BOTH),
        "decreasing": direction in (DIRECTION_DECREASING, DIRECTION_BOTH),
        "enable": enable or None,
        "disable": disable or None,
        "invert": bool(data.get(SUBCONF_INVERT, False)),
    }


def eval_leader(
    *,
    feature: str,
    domain: str,
    state: str,
    current: str,
    previous: str,
    increasing: bool,
    decreasing: bool,
    enable: str | None,
    disable: str | None,
    invert: bool,
) -> bool:
    """Evaluate one leader's truth for one feature (post-Invert).

    Parity with the legacy eval_leader macro:
      1. Direction labels take precedence (numeric current vs previous;
         non-numeric / first update -> False; Increasing and Decreasing OR'd).
      2. Else Enable/Disable state-equality values.
      3. Else default truth: state == feature (case-sensitive) OR state in the
         truthy set (case-insensitive); event/button domains are always True.
      4. Invert applies last.

    `state` is the raw current state string (used by Enable/Disable/default).
    `current`/`previous` feed Direction (for event-domain leaders `current`
    carries the event_type, matching the legacy leaders-attribute semantics).
    """
    if increasing or decreasing:
        cur_n = _to_float(current)
        prev_n = _to_float(previous)
        has_mov = cur_n is not None and prev_n is not None
        is_inc = has_mov and cur_n > prev_n  # type: ignore[operator]
        is_dec = has_mov and cur_n < prev_n  # type: ignore[operator]
        base = (increasing and is_inc) or (decreasing and is_dec)
    elif enable is not None or disable is not None:
        by_en = enable is not None and state == enable
        by_dis = disable is not None and state == disable
        if enable is not None and disable is not None:
            base = by_en and not by_dis
        elif enable is not None:
            base = by_en
        else:
            base = not by_dis
    elif domain in MOMENTARY_DOMAINS:
        base = True
    else:
        base = state == feature or state.lower() in TRUTHY_STATES
    return (not base) if invert else base


def build_leader_defs(
    *,
    labeled_leaders: Mapping[str, list[str]],
    leader_subentries: list[Mapping[str, Any]],
    entity_ctx: Mapping[str, Mapping[str, str]],
) -> tuple[dict[tuple[str, str, str], LeaderDef], list[EngineError]]:
    """Build resolved leader definitions from labels + subentries.

    `labeled_leaders` maps entity_id -> label names for every leader entity
    (the `feature_leader` label set UNION the subentry-referenced entities).
    `entity_ctx` maps entity_id -> {'area_id': ..., 'floor_id': ...}.

    Returns (defs, errors) where defs is keyed by (entity_id, feature, scope).
    Subentry definitions win over a label definition for the same key.
    Leaders whose scope cannot be resolved are skipped with an error.
    """
    defs: dict[tuple[str, str, str], LeaderDef] = {}
    errors: list[EngineError] = []

    def _resolve_scope(
        eid: str, feature: str, scope: str, source: str
    ) -> str | None:
        ctx = entity_ctx.get(eid, {})
        area_id = ctx.get("area_id", "")
        floor_id = ctx.get("floor_id", "")
        if scope == SCOPE_AREA:
            if area_id == "":
                errors.append(
                    EngineError(
                        ISSUE_LEADER_NO_AREA,
                        f"Leader '{eid}' leads '{feature}' at area scope but has no area.",
                        {"entity_id": eid, "feature": feature, "source": source},
                    )
                )
                return None
            return area_id
        if scope == SCOPE_FLOOR:
            if floor_id == "":
                errors.append(
                    EngineError(
                        ISSUE_LEADER_NO_FLOOR,
                        f"Leader '{eid}' leads '{feature}' at floor scope but its area has no floor.",
                        {"entity_id": eid, "feature": feature, "source": source},
                    )
                )
                return None
            return floor_id
        return ""  # global

    # Pass 1 — label definitions.
    for eid, label_names in labeled_leaders.items():
        for lbl in label_names:
            if not (m := LEADER_LABEL_RE.match(lbl)):
                continue
            prefix, feature = m.group(1).strip(), m.group(2).strip()
            scope = (
                SCOPE_AREA
                if prefix == "Area"
                else SCOPE_FLOOR
                if prefix == "Floor"
                else SCOPE_GLOBAL
            )
            if (scope_id := _resolve_scope(eid, feature, scope, "label")) is None:
                continue
            mods = extract_label_modifiers(label_names, feature, scope)
            defs[(eid, feature, scope)] = LeaderDef(
                entity_id=eid,
                feature=feature,
                scope=scope,
                scope_id=scope_id,
                source="label",
                **mods,
            )

    # Pass 2 — subentry definitions (win on conflict).
    for data in leader_subentries:
        eid = str(data.get(SUBCONF_ENTITY_ID, "") or "").strip()
        feature = str(data.get(SUBCONF_FEATURE, "") or "").strip()
        scope = str(data.get(SUBCONF_SCOPE, "") or "").strip()
        if eid == "" or feature == "" or scope not in SCOPE_PREFIXES:
            continue
        if (scope_id := _resolve_scope(eid, feature, scope, "subentry")) is None:
            continue
        mods = subentry_modifiers(data)
        defs[(eid, feature, scope)] = LeaderDef(
            entity_id=eid,
            feature=feature,
            scope=scope,
            scope_id=scope_id,
            source="subentry",
            **mods,
        )

    return defs, errors


def build_triples(
    defs: Mapping[tuple[str, str, str], LeaderDef],
) -> dict[str, list[str]]:
    """Map triple keys ('feature||scope||scope_id') to leader entity_ids."""
    triples: dict[str, list[str]] = {}
    for leader_def in defs.values():
        leaders = triples.setdefault(leader_def.triple_key, [])
        if leader_def.entity_id not in leaders:
            leaders.append(leader_def.entity_id)
    return triples


def resolve_modes(
    *,
    triple_keys: list[str],
    mode_subentries: list[Mapping[str, Any]],
    sensor_label_names: list[str],
) -> dict[str, str]:
    """Resolve the fold mode per triple.

    Priority: Mode subentry for (feature, scope) -> '<Scoped F> Mode:' label
    on the instance's sensor entity -> 'leader'.
    """
    sub_modes: dict[tuple[str, str], str] = {}
    for data in mode_subentries:
        feature = str(data.get(SUBCONF_FEATURE, "") or "").strip()
        scope = str(data.get(SUBCONF_SCOPE, "") or "").strip()
        mode = str(data.get(SUBCONF_MODE, "") or "").strip().lower()
        if feature and scope and mode in FOLD_MODES:
            sub_modes[(feature, scope)] = mode

    modes: dict[str, str] = {}
    for key in triple_keys:
        parts = key.split("||")
        feature, scope = parts[0], parts[1]
        if (mode := sub_modes.get((feature, scope))) is not None:
            modes[key] = mode
            continue
        # Label lookup (case-sensitive, full-string match, value lowercased).
        found = "leader"
        pfx = scope_prefix(scope)
        for lbl in sensor_label_names:
            if m := MODE_LABEL_RE.match(lbl):
                if m.group(2) == feature and (m.group(1).strip() == pfx.strip()):
                    found = m.group(3).lower()
                    break
        modes[key] = found
    return modes


# ── Attribute updaters ───────────────────────────────────────────────────────


def update_leaders(
    *,
    prev: Mapping[str, Any],
    all_leader_ids: list[str],
    changed_eid: str | None,
    cv_raw: str | None,
    changed_ts: float | None,
    seed_fn: Callable[[str], tuple[str, float]],
) -> dict[str, dict[str, Any]]:
    """Update the leaders attribute (legacy lines 323-373).

    Carry non-orphans through, seed newly-labeled leaders, and rebuild the
    changed leader's entry (skip-values carry the previous entry through).
    `seed_fn(entity_id) -> (current_state, last_changed_timestamp)` is used
    for newly-seen leaders only.
    """
    prev_map = prev if isinstance(prev, Mapping) else {}
    result: dict[str, dict[str, Any]] = {}

    for eid, ldat in prev_map.items():
        if eid in all_leader_ids and eid != changed_eid:
            result[eid] = dict(ldat) if isinstance(ldat, Mapping) else {}

    for eid in all_leader_ids:
        if eid not in result and eid != changed_eid:
            state, ts = seed_fn(eid)
            result[eid] = {
                "current_value": state,
                "previous_value": "",
                "last_changed_timestamp": ts,
            }

    if changed_eid is not None and changed_eid in all_leader_ids:
        value = cv_raw if cv_raw is not None else ""
        ts = changed_ts if changed_ts is not None else 0.0
        is_skip = _is_skip_value(value)
        prev_l = prev_map.get(changed_eid, {})
        prev_l = prev_l if isinstance(prev_l, Mapping) else {}
        if is_skip:
            cv = prev_l.get("current_value", value)
            cv_ts = prev_l.get("last_changed_timestamp", ts)
        else:
            cv = value
            cv_ts = ts
        old_cv = prev_l.get("current_value", "")
        old_pv = prev_l.get("previous_value", "")
        prev_cv_raw = old_cv if cv != old_cv else old_pv
        prev_cv = "" if _is_skip_value(str(prev_cv_raw)) else prev_cv_raw
        result[changed_eid] = {
            "current_value": cv,
            "previous_value": prev_cv,
            "last_changed_timestamp": cv_ts,
        }

    return result


def update_features(
    *,
    prev_features: Mapping[str, Any],
    prev_leaders: Mapping[str, Any],
    defs: Mapping[tuple[str, str, str], LeaderDef],
    triples: Mapping[str, list[str]],
    modes: Mapping[str, str],
    get_state: Callable[[str], str],
    changed_eid: str | None = None,
    cv_raw: str | None = None,
    new_state_str: str | None = None,
    changed_ts: float | None = None,
    manual: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Update the features attribute (legacy lines 410-653).

    Carry phase: keep every previous triple that is still leader-mapped or is
    a manual override (triggering_leader == ''); drop the rest.
    Manual phase: write the override entry when `manual` is provided.
    State phase: re-evaluate every triple the changed leader contributes to.
    """
    prev_map = prev_features if isinstance(prev_features, Mapping) else {}
    prev_leaders_map = prev_leaders if isinstance(prev_leaders, Mapping) else {}
    result: dict[str, Any] = {}

    # ── Carry phase ─────────────────────────────────────────────────────────
    for fname, scopes_map in prev_map.items():
        if not isinstance(scopes_map, Mapping):
            continue
        for scope_val, sids in scopes_map.items():
            if not isinstance(sids, Mapping):
                continue
            for scope_id_val, entry in sids.items():
                entry = entry if isinstance(entry, Mapping) else {}
                key = f"{fname}||{scope_val}||{scope_id_val}"
                has_leader = key in triples
                is_manual = entry.get("triggering_leader", "") == ""
                if has_leader or is_manual:
                    result.setdefault(fname, {}).setdefault(scope_val, {})[
                        scope_id_val
                    ] = dict(entry)

    # ── Manual override phase (labeled_feature_set event / set_feature action)
    if manual is not None:
        tgt = str(manual.get("target_feature", "") or "").strip()
        scp = str(manual.get("scope", "") or "").strip().lower()
        sid = str(manual.get("scope_id", "") or "")
        ena = as_bool(manual.get("enabled", False))
        ts = float(manual.get("timestamp", 0.0) or 0.0)
        if tgt != "" and scp in (SCOPE_AREA, SCOPE_FLOOR, SCOPE_GLOBAL):
            prev_entry = (
                result.get(tgt, {}).get(scp, {}).get(sid, {})
                if isinstance(result.get(tgt, {}).get(scp, {}), Mapping)
                else {}
            )
            mode = prev_entry.get("mode", MODE_LEADER)
            result.setdefault(tgt, {}).setdefault(scp, {})[sid] = {
                "enabled": ena,
                "mode": mode,
                "last_changed_timestamp": ts,
                "triggering_leader": "",
            }

    # ── State phase (leader-driven tick) ────────────────────────────────────
    if changed_eid is not None:
        value = cv_raw if cv_raw is not None else ""
        if not _is_skip_value(value):
            ts = changed_ts if changed_ts is not None else 0.0
            prev_l = prev_leaders_map.get(changed_eid, {})
            prev_l = prev_l if isinstance(prev_l, Mapping) else {}
            prev_cv = str(prev_l.get("current_value", ""))
            # Legacy compares Enable/Disable/default-truth against states(eid)
            # at render time ('unknown' for a removed entity).
            state_str = (
                new_state_str
                if new_state_str is not None
                else get_state(changed_eid)
            )
            changed_domain = changed_eid.split(".")[0]

            for key, leaders_list in triples.items():
                if changed_eid not in leaders_list:
                    continue
                parts = key.split("||")
                fname, scope_val, scope_id_val = parts[0], parts[1], parts[2]
                mode = modes.get(key, MODE_LEADER)
                leader_def = defs.get((changed_eid, fname, scope_val))
                if leader_def is None:
                    continue
                this_truth = eval_leader(
                    feature=fname,
                    domain=changed_domain,
                    state=state_str,
                    current=value,
                    previous=prev_cv,
                    increasing=leader_def.increasing,
                    decreasing=leader_def.decreasing,
                    enable=leader_def.enable,
                    disable=leader_def.disable,
                    invert=leader_def.invert,
                )
                if mode == MODE_LEADER:
                    new_enabled = this_truth
                else:
                    values: list[bool] = []
                    for other_eid in leaders_list:
                        if other_eid == changed_eid:
                            values.append(this_truth)
                            continue
                        other_def = defs.get((other_eid, fname, scope_val))
                        if other_def is None:
                            continue
                        other_l = prev_leaders_map.get(other_eid, {})
                        other_l = other_l if isinstance(other_l, Mapping) else {}
                        other_prev = str(other_l.get("previous_value", ""))
                        other_state = get_state(other_eid)
                        values.append(
                            eval_leader(
                                feature=fname,
                                domain=other_eid.split(".")[0],
                                state=other_state,
                                current=other_state,
                                previous=other_prev,
                                increasing=other_def.increasing,
                                decreasing=other_def.decreasing,
                                enable=other_def.enable,
                                disable=other_def.disable,
                                invert=other_def.invert,
                            )
                        )
                    new_enabled = min(values) if mode == MODE_ALL else max(values)

                prev_entry = (
                    result.get(fname, {}).get(scope_val, {}).get(scope_id_val, {})
                )
                prev_entry = prev_entry if isinstance(prev_entry, Mapping) else {}
                prev_enabled = prev_entry.get("enabled")
                prev_ts = prev_entry.get("last_changed_timestamp", ts)
                flipped = (
                    prev_enabled is None
                    or prev_enabled != new_enabled
                    or changed_domain in MOMENTARY_DOMAINS
                )
                new_ts = ts if flipped else prev_ts
                result.setdefault(fname, {}).setdefault(scope_val, {})[
                    scope_id_val
                ] = {
                    "enabled": new_enabled,
                    "mode": mode,
                    "last_changed_timestamp": new_ts,
                    "triggering_leader": changed_eid,
                }

    return result


def update_snapshots(
    *,
    prev: Mapping[str, Any],
    snapshot_name: str | None,
    payload: Any,
) -> dict[str, Any]:
    """Update the snapshots attribute (legacy lines 668-693).

    Non-snapshot ticks (snapshot_name None) carry the dict through unchanged.
    An empty name, or an empty/non-mapping payload, removes the entry.
    """
    prev_map = prev if isinstance(prev, Mapping) else {}
    if snapshot_name is None:
        return dict(prev_map)
    name = snapshot_name.strip()
    if name == "":
        return dict(prev_map)
    out = {k: v for k, v in prev_map.items() if k != name}
    if isinstance(payload, Mapping) and len(payload) > 0:
        out[name] = dict(payload)
    return out


# ── Areas label_map ──────────────────────────────────────────────────────────


def build_label_map(
    *,
    gated_areas: list[Mapping[str, Any]],
    provides_subentries: list[Mapping[str, Any]],
) -> tuple[dict[str, Any], list[EngineError]]:
    """Build the label_map attribute (legacy lines 90-187).

    `gated_areas` items: {'area_id', 'floor_id', 'labels': [label names]}.
    `provides_subentries` items: subentry data dicts, each augmented by the
    coordinator with the declaring area's floor under key '_floor_id'.

    Returns (label_map, errors). Subentry declarations win over label-derived
    entries for the same (scope_id, label).
    """
    errors: list[EngineError] = []
    # scope_id -> {'labels': {label_name: entry}}
    scopes: dict[str, dict[str, Any]] = {}

    def _add_entry(scope_id: str, lname: str, lentry: dict[str, Any], overwrite: bool) -> None:
        bucket = scopes.setdefault(scope_id, {"labels": {}})
        if overwrite or lname not in bucket["labels"]:
            bucket["labels"][lname] = lentry

    # Pass 1 — label declarations on gated areas.
    for area in gated_areas:
        aid = str(area.get("area_id", ""))
        floor_id = str(area.get("floor_id", "") or "")
        area_labels = [l for l in area.get("labels", []) if isinstance(l, str)]
        for lbl in area_labels:
            if not (m := PROVIDES_LABEL_RE.match(lbl)):
                continue
            prefix, lname = m.group(1).strip(), m.group(2).strip()
            if lname == "" or _PROVIDES_MODIFIER_RE.search(lname):
                continue
            scope_val = (
                SCOPE_AREA
                if prefix == "Area"
                else SCOPE_FLOOR
                if prefix == "Floor"
                else SCOPE_NONE
            )
            scope_id_val = aid if scope_val in (SCOPE_AREA, SCOPE_NONE) else floor_id
            if scope_id_val == "":
                errors.append(
                    EngineError(
                        ISSUE_PROVIDES_NO_FLOOR,
                        f"Area '{aid}' declares 'Floor Provides: {lname}' but has no floor.",
                        {"area_id": aid, "label": lname, "source": "label"},
                    )
                )
                continue
            comp_prefix = (
                "Area "
                if scope_val == SCOPE_AREA
                else "Floor "
                if scope_val == SCOPE_FLOOR
                else ""
            )
            comp_override = ""
            comp_head = f"{comp_prefix}Provides {lname} Component: "
            for other in area_labels:
                if other.startswith(comp_head) and len(other) > len(comp_head):
                    comp_override = _value_after_last_colon(other)
                    break
            component = comp_override if comp_override != "" else "select"
            _add_entry(
                scope_id_val,
                lname,
                {
                    "scope": scope_val,
                    "scope_id": scope_id_val,
                    "component": component,
                    "declaring_area_id": aid,
                },
                overwrite=False,
            )

    # Pass 2 — subentry declarations (win on conflict).
    for data in provides_subentries:
        aid = str(data.get(SUBCONF_AREA_ID, "") or "").strip()
        lname = str(data.get(SUBCONF_FEATURE, "") or "").strip()
        scope_val = str(data.get(SUBCONF_SCOPE, "") or "").strip()
        component = str(data.get(SUBCONF_COMPONENT, "") or "select").strip() or "select"
        if aid == "" or lname == "" or scope_val not in (
            SCOPE_AREA,
            SCOPE_FLOOR,
            SCOPE_NONE,
        ):
            continue
        floor_id = str(data.get("_floor_id", "") or "")
        scope_id_val = aid if scope_val in (SCOPE_AREA, SCOPE_NONE) else floor_id
        if scope_id_val == "":
            errors.append(
                EngineError(
                    ISSUE_PROVIDES_NO_FLOOR,
                    f"Provides subentry for area '{aid}' declares floor-scoped '{lname}' but the area has no floor.",
                    {"area_id": aid, "label": lname, "source": "subentry"},
                )
            )
            continue
        _add_entry(
            scope_id_val,
            lname,
            {
                "scope": scope_val,
                "scope_id": scope_id_val,
                "component": component,
                "declaring_area_id": aid,
            },
            overwrite=True,
        )

    # Flatten into the public <scope_id>||<label> map (exact legacy shape).
    label_map: dict[str, Any] = {}
    for sid, sdat in scopes.items():
        for lname, ldat in sdat["labels"].items():
            label_map[f"{sid}||{lname}"] = {
                "scope_id": sid,
                "label": lname,
                "scope": ldat["scope"],
                "component": ldat["component"],
                "declaring_area_id": ldat["declaring_area_id"],
                "label_data": {
                    "scope": ldat["scope"],
                    "scope_id": ldat["scope_id"],
                    "component": ldat["component"],
                    "declaring_area_id": ldat["declaring_area_id"],
                },
            }
    return label_map, errors
