"""Error mode handling for Labeled Features.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging
from typing import Any

import voluptuous as vol
from homeassistant.core import HomeAssistant, ServiceCall
from homeassistant.helpers import config_validation as cv

from .const import (
    DEFAULT_ALERT_ACTION,
    DEFAULT_ERROR_MODE,
    DOMAIN,
    ERROR_MODE_ALERT,
    ERROR_MODE_LOG,
    ERROR_MODE_SILENT,
    ERROR_MODE_STOP,
    ERROR_MODES,
)

_LOGGER = logging.getLogger(__name__)


class ErrorModeHandler:
    """Handles error mode tiers for the labeled features system."""

    def __init__(
        self,
        hass: HomeAssistant,
        default_mode: str = DEFAULT_ERROR_MODE,
        alert_action: str = DEFAULT_ALERT_ACTION,
    ) -> None:
        """Initialize handler."""
        self._hass = hass
        self._default_mode = default_mode
        self._alert_action = alert_action

    async def handle(
        self,
        message: str,
        mode: str | None = None,
        source: str = "Labeled Feature",
        severity: str = "medium",
    ) -> str | None:
        """Handle an error. Returns 'stop' if mode is STOP, else None."""
        effective_mode = (mode or self._default_mode).lower()

        if effective_mode == ERROR_MODE_SILENT:
            return None

        if effective_mode == ERROR_MODE_LOG:
            _LOGGER.warning("[%s] %s", source, message)
            return None

        if effective_mode == ERROR_MODE_ALERT:
            await self._send_alert(message, source, severity)
            return None

        if effective_mode == ERROR_MODE_STOP:
            _LOGGER.error("[%s] %s", source, message)
            return ERROR_MODE_STOP

        return None

    async def handle_service_call(self, call: ServiceCall) -> None:
        """Handle the error_mode service call."""
        await self.handle(
            message=call.data["message"],
            mode=call.data.get("error_mode"),
            source=call.data.get("source", "Labeled Feature"),
            severity=call.data.get("severity", "medium"),
        )

    async def _send_alert(
        self, message: str, source: str, severity: str
    ) -> None:
        """Send an alert notification."""
        try:
            await self._hass.services.async_call(
                self._alert_action,
                None,
                {
                    "alert_severity": severity,
                    "alert_title": source,
                    "alert_message": message,
                },
                blocking=False,
            )
        except Exception:
            try:
                await self._hass.services.async_call(
                    "persistent_notification",
                    "create",
                    {
                        "message": f"[{source}] {message}",
                        "title": f"{source} Alert",
                    },
                    blocking=False,
                )
            except Exception:
                _LOGGER.error(
                    "[%s] Failed to send alert: %s", source, message
                )


def _build_error_mode_schema() -> vol.Schema:
    """Return the service call schema for error_mode."""
    return vol.Schema(
        {
            vol.Required("error_mode"): vol.In(ERROR_MODES),
            vol.Required("message"): cv.string,
            vol.Optional("source", default="Labeled Feature"): cv.string,
            vol.Optional("severity", default="medium"): vol.In(
                ["low", "medium", "high"]
            ),
        }
    )


async def async_register_error_mode_service(
    hass: HomeAssistant, handler: ErrorModeHandler
) -> None:
    """Register the error_mode service."""
    hass.services.async_register(
        DOMAIN,
        "error_mode",
        handler.handle_service_call,
        schema=_build_error_mode_schema(),
    )


async def async_unregister_error_mode_service(hass: HomeAssistant) -> None:
    """Unregister the error_mode service."""
    if hass.services.has_service(DOMAIN, "error_mode"):
        hass.services.async_remove(DOMAIN, "error_mode")