"""Error handling framework for the Labeled Features integration.

Mirrors the legacy Error Mode tiers (silent / log / alert / stop) for the
component's internal errors:

  silent — no-op
  log    — _LOGGER.warning
  alert  — call the configured alert action (default script.send_alert) with
           the same field names the legacy script consumes
  stop   — _LOGGER.error plus a self-clearing Repair issue

The `labeled_features.handle_error` action exposes the same routing to
scripts/automations (field-compatible with script.labeled_feature_error_mode).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from homeassistant.core import HomeAssistant
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers import issue_registry as ir

from .const import (
    CONF_ALERT_ACTION,
    CONF_ALERT_SEVERITY,
    CONF_ERROR_MODE,
    DEFAULT_ALERT_ACTION,
    DEFAULT_ALERT_SEVERITY,
    DEFAULT_ERROR_MODE,
    DOMAIN,
    ERROR_ALERT,
    ERROR_LOG,
    ERROR_SILENT,
    ERROR_STOP,
    ISSUE_ALERT_ACTION_FAILED,
)

if TYPE_CHECKING:
    from homeassistant.config_entries import ConfigEntry

_LOGGER = logging.getLogger(__name__)


def _issue_id(entry: ConfigEntry, key: str) -> str:
    """Issue ids are namespaced per config entry."""
    return f"{entry.entry_id}_{key}"


async def async_route_error(
    hass: HomeAssistant,
    entry: ConfigEntry,
    *,
    key: str,
    message: str,
    source: str = "Labeled Features",
    severity: str | None = None,
    mode: str | None = None,
) -> None:
    """Route an error through the configured tier.

    `mode` overrides the entry's configured error mode (used by the
    handle_error action, where the caller picks the tier explicitly).
    """
    resolved = (mode or entry.options.get(CONF_ERROR_MODE, DEFAULT_ERROR_MODE)).lower()

    if resolved == ERROR_SILENT:
        return

    if resolved == ERROR_ALERT:
        action = entry.options.get(CONF_ALERT_ACTION, DEFAULT_ALERT_ACTION)
        sev = severity or entry.options.get(
            CONF_ALERT_SEVERITY, DEFAULT_ALERT_SEVERITY
        )
        try:
            service_domain, service_name = action.split(".", 1)
            if not service_domain or not service_name:
                raise ValueError(f"Malformed alert action '{action}'")
            await hass.services.async_call(
                service_domain,
                service_name,
                {
                    "alert_severity": sev,
                    "alert_title": source,
                    "alert_message": message,
                },
                blocking=True,
            )
        except (ValueError, HomeAssistantError) as err:
            _LOGGER.error(
                "%s: alert action '%s' failed (%s); original error: %s",
                source,
                action,
                err,
                message,
            )
            ir.async_create_issue(
                hass,
                DOMAIN,
                _issue_id(entry, ISSUE_ALERT_ACTION_FAILED),
                is_fixable=False,
                issue_domain=DOMAIN,
                severity=ir.IssueSeverity.ERROR,
                translation_key=ISSUE_ALERT_ACTION_FAILED,
                translation_placeholders={
                    "source": source,
                    "message": f"Alert action '{action}' failed: {err}",
                },
            )
        else:
            async_clear_issue(hass, entry, ISSUE_ALERT_ACTION_FAILED)
        return

    if resolved == ERROR_STOP:
        _LOGGER.error("%s: %s", source, message)
        ir.async_create_issue(
            hass,
            DOMAIN,
            _issue_id(entry, key),
            is_fixable=False,
            issue_domain=DOMAIN,
            severity=ir.IssueSeverity.ERROR,
            translation_key=key if key in _KNOWN_ISSUE_KEYS else "generic_error",
            translation_placeholders={"source": source, "message": message},
        )
        return

    # ERROR_LOG (and unknown values — the legacy default tier is 'log').
    _LOGGER.warning("%s: %s", source, message)


_KNOWN_ISSUE_KEYS = {
    "leader_no_area",
    "leader_no_floor",
    "provides_no_floor",
    "invalid_subentry",
    "alert_action_failed",
}


def async_clear_issue(hass: HomeAssistant, entry: ConfigEntry, key: str) -> None:
    """Clear a previously-raised Repair issue (self-clearing on success)."""
    ir.async_delete_issue(hass, DOMAIN, _issue_id(entry, key))
