"""Tiered error handling for the Labeled Features integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import hashlib
import logging
from typing import TYPE_CHECKING

from homeassistant.core import HomeAssistant
from homeassistant.helpers import issue_registry as ir

from .const import DOMAIN

if TYPE_CHECKING:
    from homeassistant.config_entries import ConfigEntry

_LOGGER = logging.getLogger(__name__)

_ISSUE_PREFIX = "component_error_"


def _issue_id(source: str, message: str) -> str:
    """Compute a stable Repair issue_id from source + message."""
    h = hashlib.sha1(f"{source}||{message}".encode(), usedforsecurity=False).hexdigest()[:16]
    return f"{_ISSUE_PREFIX}{h}"


def handle_error(
    hass: HomeAssistant,
    entry: ConfigEntry | None,
    source: str,
    message: str,
    exc: BaseException | None = None,
) -> None:
    """Route an error through the configured tier.

    Tiers:
      * silent → no-op
      * log    → _LOGGER.warning
      * alert  → fire-and-forget call to the configured alert action
      * stop   → _LOGGER.error + create a Repair issue

    Never raises. Errors are always isolated to the failing unit of work.
    """
    from .const import (
        CONF_ALERT_ACTION,
        CONF_ERROR_MODE,
        DEFAULT_ALERT_ACTION,
        DEFAULT_ERROR_MODE,
    )

    # Read runtime options; fall back to defaults if entry is unavailable.
    if entry is not None:
        opts = {**(entry.data or {}), **(entry.options or {})}
        tier = opts.get(CONF_ERROR_MODE, DEFAULT_ERROR_MODE)
        alert_action = opts.get(CONF_ALERT_ACTION, DEFAULT_ALERT_ACTION)
    else:
        tier = DEFAULT_ERROR_MODE
        alert_action = DEFAULT_ALERT_ACTION

    if tier == "silent":
        return

    if tier == "log":
        _LOGGER.warning("%s: %s", source, message, exc_info=exc)
        return

    if tier == "alert":
        _LOGGER.warning("%s: %s", source, message, exc_info=exc)
        try:
            domain, service = alert_action.split(".", 1)
        except ValueError:
            _LOGGER.error(
                "Labeled Features: invalid alert action %r; falling back to log tier",
                alert_action,
            )
            return

        async def _dispatch_alert() -> None:
            try:
                await hass.services.async_call(
                    domain,
                    service,
                    {
                        "alert_severity": "medium",
                        "alert_title": source,
                        "alert_message": message,
                    },
                    blocking=False,
                )
            except Exception as alert_exc:  # noqa: BLE001
                # Never let an alert-dispatch failure surface as an unhandled
                # task exception. Log once at ERROR and move on; this tends
                # to happen when the configured alert action doesn't exist.
                _LOGGER.error(
                    "Labeled Features: alert dispatch to %s failed: %s",
                    alert_action,
                    alert_exc,
                )

        hass.async_create_task(_dispatch_alert())
        return

    if tier == "stop":
        _LOGGER.error("%s: %s", source, message, exc_info=exc)
        try:
            ir.async_create_issue(
                hass,
                DOMAIN,
                _issue_id(source, message),
                is_fixable=False,
                severity=ir.IssueSeverity.ERROR,
                translation_key="component_error",
                translation_placeholders={"source": source, "message": message},
            )
        except Exception:  # noqa: BLE001 — Repair failures never surface
            _LOGGER.exception("Labeled Features: failed to create repair issue")
        return

    # Unknown tier: default to log so misconfiguration is visible.
    _LOGGER.warning("%s: %s (unknown error tier %r)", source, message, tier, exc_info=exc)


def clear_error(hass: HomeAssistant, source: str, message: str) -> None:
    """Clear a previously-raised Repair issue for the given source/message.

    Safe to call even if no issue exists.
    """
    try:
        ir.async_delete_issue(hass, DOMAIN, _issue_id(source, message))
    except Exception:  # noqa: BLE001
        _LOGGER.debug("Labeled Features: clear_error no-op", exc_info=True)
