"""Per-leader truth evaluation and triple resolution.

Ports the algorithm currently encoded in the trigger-based template sensor
`sensor.labeled_features_state.features` (see configuration.yaml).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from .const import TRUTHY_STATES
from .label_parser import (
    has_decreasing,
    has_increasing,
    has_invert,
    match_disable,
    match_enable,
    scope_prefix as scope_to_prefix,
)

if TYPE_CHECKING:
    pass


def _to_float(value: object) -> float | None:
    try:
        return float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return None


def eval_leader_truth(
    labels: list[str],
    domain: str,
    current_value: object,
    previous_value: object,
    feature: str,
    scope: str,
) -> bool:
    """Compute the per-leader `enabled` value for one (feature, scope) triple.

    Precedence:
      1. Direction (`Increasing`/`Decreasing`) — takes priority over Enable/Disable.
      2. Enable/Disable value match.
      3. Default truth — `event`/`button` domains always true; otherwise
         state equals the feature name (case-sensitive) OR is one of the
         truthy strings (case-insensitively).
      4. Invert is applied last.
    """
    pfx = scope_to_prefix(scope)
    inc = has_increasing(labels, feature, pfx)
    dec = has_decreasing(labels, feature, pfx)

    if inc or dec:
        cur_n = _to_float(current_value)
        prev_n = _to_float(previous_value)
        has_mov = cur_n is not None and prev_n is not None
        is_inc = has_mov and cur_n > prev_n  # type: ignore[operator]
        is_dec = has_mov and cur_n < prev_n  # type: ignore[operator]
        base = (inc and is_inc) or (dec and is_dec)
    else:
        en_val: str | None = None
        dis_val: str | None = None
        for lbl in labels:
            if en_val is None:
                en_val = match_enable(lbl, feature, pfx)
            if dis_val is None:
                dis_val = match_disable(lbl, feature, pfx)
            if en_val is not None and dis_val is not None:
                break

        cv_str = "" if current_value is None else str(current_value)

        if en_val is not None or dis_val is not None:
            by_en = en_val is not None and cv_str == en_val
            by_dis = dis_val is not None and cv_str == dis_val
            if en_val is not None and dis_val is not None:
                base = by_en and not by_dis
            elif en_val is not None:
                base = by_en
            else:
                # Only Disable declared: enabled when NOT matching disable
                base = not by_dis
        else:
            if domain in ("event", "button"):
                base = True
            else:
                base = (cv_str == feature) or (cv_str.lower() in TRUTHY_STATES)

    if has_invert(labels, feature, pfx):
        return not base
    return bool(base)


def fold_triple(mode: str, per_leader_truths: list[bool]) -> bool:
    """Fold a list of per-leader truths per the triple's mode.

    * `leader` — the caller is expected to pass a single-element list
      containing the changed leader's truth.
    * `any`    — OR over every leader's truth.
    * `all`    — AND over every leader's truth (empty list → False).
    """
    if not per_leader_truths:
        return False
    if mode == "all":
        return all(per_leader_truths)
    if mode == "any":
        return any(per_leader_truths)
    # leader (default)
    return bool(per_leader_truths[0])


def resolve_mode(sensor_labels: list[str], feature: str, scope: str) -> str:
    """Resolve `<pfx><F> Mode: Leader|Any|All` from labels on the sensor entity.

    Default `leader`. The prefix must match the triple's scope.
    """
    pfx = scope_to_prefix(scope)
    target_prefix = f"{pfx}{feature} Mode: "
    for lbl in sensor_labels:
        if lbl.startswith(target_prefix):
            val = lbl[len(target_prefix):].strip().lower()
            if val in ("leader", "any", "all"):
                return val
    return "leader"
