"""Label parsers for the Labeled Features integration.

All matching is case-sensitive per the design documentation
(feature names capitalized; `True` / `False` capitalized; keywords like
`Leader`, `Follower`, `Provides`, `Enable`, `Disable`, `Increasing`,
`Decreasing`, `Invert`, `Mode`, `Component` all capitalized).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import re
from typing import Final

from .const import (
    PROVIDES_MODIFIER_KEYWORDS,
    SCOPE_AREA,
    SCOPE_FLOOR,
    SCOPE_GLOBAL,
    SCOPE_NONE,
)

# ── Regexes ──────────────────────────────────────────────────────────────
_LEADER_RE: Final = re.compile(r"^(Area |Floor |)Leader: (.+)$")
_PROVIDES_RE: Final = re.compile(r"^(Area |Floor |)Provides: (.+)$")
_MODE_RE: Final = re.compile(
    r"^(Area |Floor |)(.+) Mode: (Leader|Any|All)$"
)
_ENABLE_RE: Final = re.compile(r"^(?P<pfx>Area |Floor |)(?P<f>.+) Enable: (?P<v>.+)$")
_DISABLE_RE: Final = re.compile(r"^(?P<pfx>Area |Floor |)(?P<f>.+) Disable: (?P<v>.+)$")
_INVERT_RE: Final = re.compile(r"^(?P<pfx>Area |Floor |)(?P<f>.+) Invert: True$")
_INCREASING_RE: Final = re.compile(r"^(?P<pfx>Area |Floor |)(?P<f>.+) Increasing: True$")
_DECREASING_RE: Final = re.compile(r"^(?P<pfx>Area |Floor |)(?P<f>.+) Decreasing: True$")
_COMPONENT_RE: Final = re.compile(
    r"^(?P<pfx>Area |Floor |)Provides (?P<f>.+) Component: (?P<v>.+)$"
)
# Matches the modifier form of a Provides label. Used to reject
# `Provides <F> Component: <v>` from being registered as its own feature.
_PROVIDES_MODIFIER_TAIL_RE: Final = re.compile(
    r"^(?P<name>.+?) (?P<kw>"
    + "|".join(re.escape(k) for k in PROVIDES_MODIFIER_KEYWORDS)
    + r"): "
)


def _prefix_to_scope(prefix: str, *, area_default: str = SCOPE_AREA) -> str:
    """Convert an `Area `/`Floor `/bare label prefix into a scope name."""
    if prefix == "Area ":
        return SCOPE_AREA
    if prefix == "Floor ":
        return SCOPE_FLOOR
    return area_default


def parse_leader_label(label: str) -> tuple[str, str] | None:
    """Return (scope, feature) if `label` is a valid Leader label.

    Bare `Leader: <F>` returns scope=`global`.
    """
    m = _LEADER_RE.match(label)
    if not m:
        return None
    feature = m.group(2).strip()
    if not feature:
        return None
    scope = _prefix_to_scope(m.group(1), area_default=SCOPE_GLOBAL)
    return scope, feature


def parse_provides_label(label: str) -> tuple[str, str] | None:
    """Return (scope, feature) if `label` is a *feature-declaring* Provides label.

    Modifier labels (`Provides <F> Component: <v>`, `… Min: …`, `… Icon: …`, …)
    are filtered out — they don't declare a feature in their own right.
    Bare `Provides: <F>` returns scope=`none`.
    """
    m = _PROVIDES_RE.match(label)
    if not m:
        return None
    tail = m.group(2).strip()
    if not tail:
        return None
    # Filter modifier tails: `<Feature> Component: …`, `<Feature> Min: …`, etc.
    if _PROVIDES_MODIFIER_TAIL_RE.match(tail):
        return None
    scope = _prefix_to_scope(m.group(1), area_default=SCOPE_NONE)
    return scope, tail


def parse_mode_label(label: str) -> tuple[str, str, str] | None:
    """Return (scope, feature, mode) for a `<pfx><F> Mode: Leader|Any|All`.

    The scope of a Mode label reflects the prefix: bare (`Foo Mode: All`)
    resolves to `global`; `Area Foo Mode: All` → `area`; `Floor Foo Mode: All`
    → `floor`.
    """
    m = _MODE_RE.match(label)
    if not m:
        return None
    feature = m.group(2).strip()
    mode = m.group(3).lower()
    if not feature:
        return None
    scope = _prefix_to_scope(m.group(1), area_default=SCOPE_GLOBAL)
    return scope, feature, mode


def parse_component_override(label: str, feature: str, scope_prefix: str) -> str | None:
    """Return the `<pfx>Provides <feature> Component: <v>` value, if any.

    `scope_prefix` is `"Area "`, `"Floor "`, or `""` and must match the
    Provides label's prefix.
    """
    m = _COMPONENT_RE.match(label)
    if not m:
        return None
    if m.group("pfx") != scope_prefix:
        return None
    if m.group("f").strip() != feature:
        return None
    return m.group("v").strip()


def match_enable(label: str, feature: str, scope_prefix: str) -> str | None:
    """Return the value from `<pfx><F> Enable: <v>` if it matches; else None."""
    m = _ENABLE_RE.match(label)
    if not m:
        return None
    if m.group("pfx") != scope_prefix:
        return None
    if m.group("f").strip() != feature:
        return None
    return m.group("v").strip()


def match_disable(label: str, feature: str, scope_prefix: str) -> str | None:
    """Return the value from `<pfx><F> Disable: <v>` if it matches; else None."""
    m = _DISABLE_RE.match(label)
    if not m:
        return None
    if m.group("pfx") != scope_prefix:
        return None
    if m.group("f").strip() != feature:
        return None
    return m.group("v").strip()


def has_invert(labels: list[str], feature: str, scope_prefix: str) -> bool:
    """True when the label list contains `<pfx><F> Invert: True`."""
    target = f"{scope_prefix}{feature} Invert: True"
    return target in labels


def has_increasing(labels: list[str], feature: str, scope_prefix: str) -> bool:
    """True when the label list contains `<pfx><F> Increasing: True`."""
    target = f"{scope_prefix}{feature} Increasing: True"
    return target in labels


def has_decreasing(labels: list[str], feature: str, scope_prefix: str) -> bool:
    """True when the label list contains `<pfx><F> Decreasing: True`."""
    target = f"{scope_prefix}{feature} Decreasing: True"
    return target in labels


def scope_prefix(scope: str) -> str:
    """Convert a scope name into its label prefix (with trailing space)."""
    if scope == SCOPE_AREA:
        return "Area "
    if scope == SCOPE_FLOOR:
        return "Floor "
    return ""
