"""Sensor platform for Labeled Features.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.components.sensor import (
    SensorEntity,
    SensorStateClass,
)
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .const import (
    CONF_ENTITY_ID_SUFFIX,
)
from .coordinator import LabeledFeaturesCoordinator


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up sensor entities."""
    coordinator: LabeledFeaturesCoordinator = entry.runtime_data
    suffix = entry.data.get(CONF_ENTITY_ID_SUFFIX, "")
    async_add_entities(
        [
            LabeledFeaturesStateSensor(coordinator, entry, suffix),
            LabeledFeatureAreasStateSensor(coordinator, entry, suffix),
        ]
    )


class LabeledFeaturesStateSensor(SensorEntity):
    """Sensor entity for labeled features state."""

    _attr_has_entity_name = True
    _attr_name = "Labeled Features State"
    _attr_state_class = SensorStateClass.MEASUREMENT
    _attr_native_unit_of_measurement = "leaders"

    def __init__(
        self,
        coordinator: LabeledFeaturesCoordinator,
        entry: ConfigEntry,
        suffix: str,
    ) -> None:
        """Initialize sensor."""
        self._coordinator = coordinator
        self._entry = entry
        uid = f"labeled_features_state{suffix}"
        self._attr_unique_id = uid
        if suffix:
            self._attr_name = f"Labeled Features State{suffix}"

    @property
    def native_value(self) -> int | None:
        """Return the state."""
        return len(self._coordinator.data.get("leaders", {}))

    @property
    def extra_state_attributes(self) -> dict | None:
        """Return extra attributes."""
        return {
            "feature_meta": self._coordinator.data.get("feature_meta", {}),
            "leaders": self._coordinator.data.get("leaders", {}),
            "features": self._coordinator.data.get("features", {}),
            "snapshots": self._coordinator.data.get("snapshots", {}),
        }

    @property
    def available(self) -> bool:
        """Return entity availability."""
        return self._coordinator.last_update_success


class LabeledFeatureAreasStateSensor(SensorEntity):
    """Sensor entity for labeled feature areas state."""

    _attr_has_entity_name = True
    _attr_name = "Labeled Feature Areas State"
    _attr_state_class = SensorStateClass.MEASUREMENT
    _attr_native_unit_of_measurement = "areas"

    def __init__(
        self,
        coordinator: LabeledFeaturesCoordinator,
        entry: ConfigEntry,
        suffix: str,
    ) -> None:
        """Initialize sensor."""
        self._coordinator = coordinator
        self._entry = entry
        uid = f"labeled_feature_areas_state{suffix}"
        self._attr_unique_id = uid
        if suffix:
            self._attr_name = f"Labeled Feature Areas State{suffix}"

    @property
    def native_value(self) -> int | None:
        """Return the state."""
        area_ids: set[str] = set()
        for entry_data in self._coordinator.data.get("label_map", {}).values():
            if isinstance(entry_data, dict):
                sid = entry_data.get("scope_id")
                if sid:
                    area_ids.add(sid)
        return len(area_ids)

    @property
    def extra_state_attributes(self) -> dict | None:
        """Return extra attributes."""
        return {
            "label_map": self._coordinator.data.get("label_map", {}),
        }

    @property
    def available(self) -> bool:
        """Return entity availability."""
        return self._coordinator.last_update_success