"""Sensor entities for the Labeled Features integration.

Byte-compatible replacements for the two legacy trigger-based template
sensors:

  sensor.labeled_features_state      (leaders / features / snapshots / feature_meta)
  sensor.labeled_feature_areas_state (label_map)

Both restore their attribute payloads across restarts; the areas sensor
additionally rebuilds label_map from the live registries on start.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from homeassistant.components.sensor import SensorEntity, SensorStateClass
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.restore_state import RestoreEntity
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import (
    AREAS_SENSOR_STEM,
    FEATURE_META,
    FEATURES_SENSOR_STEM,
)
from .coordinator import AreasCoordinator, FeaturesCoordinator

if TYPE_CHECKING:
    from homeassistant.config_entries import ConfigEntry


async def async_setup_entry(
    hass: HomeAssistant,
    config_entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the Labeled Features sensors."""
    runtime_data = config_entry.runtime_data
    async_add_entities(
        [
            LabeledFeaturesStateSensor(runtime_data.features_coordinator),
            LabeledFeatureAreasStateSensor(runtime_data.areas_coordinator),
        ]
    )


class LabeledFeaturesStateSensor(
    CoordinatorEntity[FeaturesCoordinator], RestoreEntity, SensorEntity
):
    """Replacement for sensor.labeled_features_state.

    State = count of leader entities. Attributes = feature_meta, leaders,
    features, snapshots (legacy shapes, JSON-serializable).
    """

    _attr_should_poll = False
    _attr_state_class = SensorStateClass.MEASUREMENT
    _attr_native_unit_of_measurement = "leaders"
    _attr_has_entity_name = False

    def __init__(self, coordinator: FeaturesCoordinator) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator)
        suffix = coordinator.suffix
        self._attr_unique_id = f"{FEATURES_SENSOR_STEM}{suffix}"
        self._attr_name = f"Labeled Features State{suffix}"
        self.entity_id = f"sensor.{FEATURES_SENSOR_STEM}{suffix}"

    async def async_added_to_hass(self) -> None:
        """Seed the coordinator from the restored state."""
        await super().async_added_to_hass()
        if (last_state := await self.async_get_last_state()) is not None:
            self.coordinator.seed_from_restore(
                leaders=last_state.attributes.get("leaders"),
                features=last_state.attributes.get("features"),
                snapshots=last_state.attributes.get("snapshots"),
            )
        self.async_write_ha_state()

    @property
    def native_value(self) -> int:
        """State = count of leader entities."""
        return len(self.coordinator.leader_set)

    @property
    def extra_state_attributes(self) -> dict[str, Any]:
        """Legacy attribute surface."""
        return {
            "feature_meta": FEATURE_META,
            "leaders": self.coordinator.leaders,
            "features": self.coordinator.features,
            "snapshots": self.coordinator.snapshots,
        }


class LabeledFeatureAreasStateSensor(
    CoordinatorEntity[AreasCoordinator], RestoreEntity, SensorEntity
):
    """Replacement for sensor.labeled_feature_areas_state.

    State = count of gated areas. Attribute = label_map (legacy shape).
    """

    _attr_should_poll = False
    _attr_state_class = SensorStateClass.MEASUREMENT
    _attr_native_unit_of_measurement = "areas"
    _attr_has_entity_name = False

    def __init__(self, coordinator: AreasCoordinator) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator)
        suffix = coordinator.suffix
        self._attr_unique_id = f"{AREAS_SENSOR_STEM}{suffix}"
        self._attr_name = f"Labeled Feature Areas State{suffix}"
        self.entity_id = f"sensor.{AREAS_SENSOR_STEM}{suffix}"

    async def async_added_to_hass(self) -> None:
        """Seed the coordinator from the restored state."""
        await super().async_added_to_hass()
        if (last_state := await self.async_get_last_state()) is not None:
            self.coordinator.seed_label_map(last_state.attributes.get("label_map"))
        self.async_write_ha_state()

    @property
    def native_value(self) -> int:
        """State = count of gated areas."""
        return self.coordinator.gated_area_count

    @property
    def extra_state_attributes(self) -> dict[str, Any]:
        """Legacy attribute surface."""
        return {"label_map": self.coordinator.label_map}
