"""Labeled Features sensors.

Two RestoreEntity sensors ported from the legacy trigger-based template
sensors `sensor.labeled_features_state` and `sensor.labeled_feature_areas_state`.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import copy
import logging
import re
from typing import Any

from homeassistant.components.sensor import SensorEntity, SensorStateClass
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import EVENT_HOMEASSISTANT_START
from homeassistant.core import Event, HomeAssistant, State, callback
from homeassistant.helpers import (
    area_registry as ar,
    device_registry as dr,
    entity_registry as er,
    floor_registry as fr,
    label_registry as lr,
)
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.restore_state import RestoreEntity
from homeassistant.util import dt as dt_util

from .const import (
    CONF_AREAS_ENTITY_ID,
    CONF_FEATURES_ENTITY_ID,
    CONF_INSTANCE_NAME,
    CONF_LEADER_LABEL,
    DEFAULT_AREAS_ENTITY_ID,
    DEFAULT_FEATURES_ENTITY_ID,
    DEFAULT_INSTANCE_NAME,
    DEFAULT_LEADER_LABEL,
    DOMAIN,
    EVENT_FEATURE_SET,
    EVENT_SNAPSHOT_SET,
    FEATURE_META,
    PROVIDES_MODIFIER_KEYWORDS,
    SCOPE_AREA,
    SCOPE_FLOOR,
    SCOPE_GLOBAL,
    SCOPE_NONE,
    STORAGE_KEY_FEATURES,
    STORAGE_KEY_LABEL_MAP,
    STORAGE_KEY_LEADERS,
    STORAGE_KEY_SNAPSHOTS,
    UNKNOWN_STATES,
)
from .error_handler import clear_error, handle_error
from .evaluator import eval_leader_truth, fold_triple, resolve_mode
from .label_parser import (
    parse_component_override,
    parse_leader_label,
    parse_provides_label,
    scope_prefix as scope_to_prefix,
)

_LOGGER = logging.getLogger(__name__)

_INITIAL_PRESS_RE = re.compile(r"_initial_press$")


def _entry_option(entry: ConfigEntry, key: str, default: Any) -> Any:
    merged = {**(entry.data or {}), **(entry.options or {})}
    return merged.get(key, default)


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Create the two Labeled Features sensors for this config entry."""
    features_entity_id = _entry_option(entry, CONF_FEATURES_ENTITY_ID, DEFAULT_FEATURES_ENTITY_ID)
    areas_entity_id = _entry_option(entry, CONF_AREAS_ENTITY_ID, DEFAULT_AREAS_ENTITY_ID)
    instance_name = _entry_option(entry, CONF_INSTANCE_NAME, DEFAULT_INSTANCE_NAME)

    features_sensor = LabeledFeaturesStateSensor(entry, features_entity_id, instance_name)
    areas_sensor = LabeledFeatureAreasStateSensor(entry, areas_entity_id, instance_name)

    async_add_entities([features_sensor, areas_sensor])


# ─────────────────────────────────────────────────────────────────────────
# Helpers shared by both sensors
# ─────────────────────────────────────────────────────────────────────────


def _resolve_label_id(hass: HomeAssistant, label_name_or_id: str) -> str | None:
    """Return the label_id matching either the label's id or its display name.

    HA's built-in template functions `label_entities()` / `label_areas()`
    accept either form; users may enter the slug (`feature_leader`) or the
    display name (`Feature Leader`). We follow the same convention.
    """
    if not label_name_or_id:
        return None
    label_reg = lr.async_get(hass)
    # Fast path: direct label_id lookup.
    direct = label_reg.async_get_label(label_name_or_id)
    if direct is not None:
        return direct.label_id
    # Fallback: match by display name.
    for lbl in label_reg.async_list_labels():
        if lbl.name == label_name_or_id:
            return lbl.label_id
    return None


def _labels_of(hass: HomeAssistant, *, entity_id: str | None = None,
                area_id: str | None = None) -> list[str]:
    """Return the list of label names attached to an entity or area.

    Returns display names because label parsers match against the
    documented case-sensitive label names (`Area Leader: Screen`, etc).
    """
    label_reg = lr.async_get(hass)
    if entity_id is not None:
        ent_reg = er.async_get(hass)
        ent = ent_reg.async_get(entity_id)
        if ent is None:
            return []
        label_ids = ent.labels or set()
    elif area_id is not None:
        area_reg = ar.async_get(hass)
        area = area_reg.async_get_area(area_id)
        if area is None:
            return []
        label_ids = area.labels or set()
    else:
        return []
    out: list[str] = []
    for lid in label_ids:
        lbl = label_reg.async_get_label(lid)
        if lbl is not None and lbl.name:
            out.append(lbl.name)
    return out


def _entities_with_label(hass: HomeAssistant, label_name_or_id: str) -> list[str]:
    """Return entity_ids carrying the label (matched by id or name)."""
    label_id = _resolve_label_id(hass, label_name_or_id)
    if label_id is None:
        return []
    ent_reg = er.async_get(hass)
    return [
        ent.entity_id
        for ent in ent_reg.entities.values()
        if ent.labels and label_id in ent.labels
    ]


def _areas_with_label(hass: HomeAssistant, label_name_or_id: str) -> list[str]:
    """Return area_ids carrying the label (matched by id or name)."""
    label_id = _resolve_label_id(hass, label_name_or_id)
    if label_id is None:
        return []
    area_reg = ar.async_get(hass)
    return [
        a.id
        for a in area_reg.async_list_areas()
        if a.labels and label_id in a.labels
    ]


def _floor_id_for_area(hass: HomeAssistant, area_id: str) -> str:
    """Return the floor_id for a given area, or '' if none."""
    area_reg = ar.async_get(hass)
    area = area_reg.async_get_area(area_id)
    if area is None or area.floor_id is None:
        return ""
    return area.floor_id


def _current_value_for_state(new_state: State | None) -> str:
    """Extract the raw current value from a state, honoring the event-domain shortcut."""
    if new_state is None:
        return ""
    if new_state.entity_id.split(".", 1)[0] == "event":
        et = new_state.attributes.get("event_type")
        if et:
            return str(et)
    return new_state.state if new_state.state is not None else ""


def _is_skip_value(cv_raw: str) -> bool:
    if _INITIAL_PRESS_RE.search(cv_raw):
        return True
    return cv_raw.lower() in UNKNOWN_STATES


# ─────────────────────────────────────────────────────────────────────────
# sensor.labeled_features_state
# ─────────────────────────────────────────────────────────────────────────


class LabeledFeaturesStateSensor(RestoreEntity, SensorEntity):
    """Native replacement for `sensor.labeled_features_state`."""

    _attr_should_poll = False
    _attr_state_class = SensorStateClass.MEASUREMENT
    _attr_native_unit_of_measurement = "leaders"

    def __init__(
        self,
        entry: ConfigEntry,
        entity_id: str,
        instance_name: str,
    ) -> None:
        self._entry = entry
        self._attr_unique_id = f"{entry.entry_id}_features_state"
        # Force the desired entity_id regardless of registry suggestion.
        self.entity_id = entity_id
        self._attr_name = f"{instance_name} State"
        # Attribute state (mutated in place, then snapshotted on write).
        self._leaders: dict[str, dict[str, Any]] = {}
        self._features: dict[str, dict[str, dict[str, dict[str, Any]]]] = {}
        self._snapshots: dict[str, dict[str, Any]] = {}
        self._unsub_state: Any = None
        self._unsub_feature_set: Any = None
        self._unsub_snapshot_set: Any = None
        self._unsub_label_reg: Any = None
        self._unsub_entity_reg: Any = None
        # Cached leader-entity set (invalidated on registry events).
        self._leader_entities_cache: set[str] | None = None

    # ---- Entity lifecycle -----------------------------------------------

    async def async_added_to_hass(self) -> None:
        await super().async_added_to_hass()
        # Restore attributes.
        last = await self.async_get_last_extra_data()
        if last is not None:
            raw = last.as_dict() or {}
            self._leaders = _coerce_mapping(raw.get(STORAGE_KEY_LEADERS))
            self._features = _coerce_mapping(raw.get(STORAGE_KEY_FEATURES))
            self._snapshots = _coerce_mapping(raw.get(STORAGE_KEY_SNAPSHOTS))
        # Subscribe events.
        bus = self.hass.bus
        self._unsub_state = bus.async_listen("state_changed", self._handle_state_changed)
        self._unsub_feature_set = bus.async_listen(EVENT_FEATURE_SET, self._handle_manual_set)
        self._unsub_snapshot_set = bus.async_listen(EVENT_SNAPSHOT_SET, self._handle_snapshot_set)
        # Registry-invalidation listeners: any change to labels or entities
        # invalidates our cached leader-entity set (recomputed lazily).
        self._unsub_label_reg = bus.async_listen(
            "label_registry_updated", self._handle_registry_invalidation
        )
        self._unsub_entity_reg = bus.async_listen(
            "entity_registry_updated", self._handle_registry_invalidation
        )
        # Initial seed: make sure leaders dict has an entry for every current
        # labeled leader (state carried from current state).
        self._seed_missing_leaders()
        self.async_write_ha_state()
        self.async_on_remove(self._teardown_listeners)

    @callback
    def _teardown_listeners(self) -> None:
        for un in (
            self._unsub_state,
            self._unsub_feature_set,
            self._unsub_snapshot_set,
            self._unsub_label_reg,
            self._unsub_entity_reg,
        ):
            if un is not None:
                un()
        self._unsub_state = self._unsub_feature_set = self._unsub_snapshot_set = None
        self._unsub_label_reg = self._unsub_entity_reg = None

    @callback
    def _handle_registry_invalidation(self, event: Event) -> None:
        """Drop the cached leader-entity set on any label/entity registry change."""
        self._leader_entities_cache = None

    # ---- Public HA properties -------------------------------------------

    @property
    def native_value(self) -> int:
        return len(self._current_leader_entities())

    @property
    def extra_state_attributes(self) -> dict[str, Any]:
        return {
            "feature_meta": copy.deepcopy(FEATURE_META),
            "leaders": copy.deepcopy(self._leaders),
            "features": copy.deepcopy(self._features),
            "snapshots": copy.deepcopy(self._snapshots),
        }

    @property
    def extra_restore_state_data(self) -> Any:
        from homeassistant.helpers.restore_state import ExtraStoredData

        payload = {
            STORAGE_KEY_LEADERS: self._leaders,
            STORAGE_KEY_FEATURES: self._features,
            STORAGE_KEY_SNAPSHOTS: self._snapshots,
        }

        class _Data(ExtraStoredData):
            def as_dict(self_inner) -> dict[str, Any]:  # noqa: N805
                return copy.deepcopy(payload)

        return _Data()

    # ---- Config access --------------------------------------------------

    def _leader_label(self) -> str:
        return _entry_option(self._entry, CONF_LEADER_LABEL, DEFAULT_LEADER_LABEL)

    def _current_leader_entities(self) -> list[str]:
        # Fast-path: return the cached set if valid.
        if self._leader_entities_cache is not None:
            return list(self._leader_entities_cache)
        entities = _entities_with_label(self.hass, self._leader_label())
        self._leader_entities_cache = set(entities)
        return entities

    def _sensor_labels(self) -> list[str]:
        return _labels_of(self.hass, entity_id=self.entity_id)

    def _seed_missing_leaders(self) -> None:
        leaders_now = set(self._current_leader_entities())
        for eid in leaders_now:
            if eid not in self._leaders:
                st = self.hass.states.get(eid)
                cv = _current_value_for_state(st)
                self._leaders[eid] = {
                    "current_value": cv,
                    "previous_value": "",
                    "last_changed_timestamp": (
                        st.last_changed.timestamp()
                        if st is not None and st.last_changed is not None
                        else dt_util.utcnow().timestamp()
                    ),
                }
        # Drop orphans.
        for eid in list(self._leaders.keys()):
            if eid not in leaders_now:
                del self._leaders[eid]

    # ---- Event handlers -------------------------------------------------

    @callback
    def _handle_state_changed(self, event: Event) -> None:
        try:
            eid = event.data.get("entity_id") or ""
            # Cheap membership check using the cached set.
            if self._leader_entities_cache is None:
                self._current_leader_entities()  # populate cache
            leader_set = self._leader_entities_cache or set()
            if eid not in leader_set:
                return
            old_state: State | None = event.data.get("old_state")
            new_state: State | None = event.data.get("new_state")
            # Boot-noise gate: no prior state or prior was unknown/unavailable/none.
            if old_state is None or old_state.state.lower() in UNKNOWN_STATES:
                return
            self._process_state_changed(eid, new_state, list(leader_set))
            clear_error(self.hass, "Labeled Features State", f"state_changed for {eid}")
            self.async_write_ha_state()
        except Exception as exc:  # noqa: BLE001
            handle_error(
                self.hass,
                self._entry,
                "Labeled Features State",
                f"state_changed handler failed: {exc}",
                exc,
            )

    @callback
    def _handle_manual_set(self, event: Event) -> None:
        try:
            data = event.data or {}
            tgt = str(data.get("target_feature") or "").strip()
            scp = str(data.get("scope") or "").strip().lower()
            sid = "" if data.get("scope_id") is None else str(data.get("scope_id"))
            ena = bool(data.get("enabled"))
            ts = data.get("timestamp")
            try:
                ts_f = float(ts) if ts is not None else dt_util.utcnow().timestamp()
            except (TypeError, ValueError):
                ts_f = dt_util.utcnow().timestamp()

            if not tgt or scp not in (SCOPE_AREA, SCOPE_FLOOR, SCOPE_GLOBAL):
                handle_error(
                    self.hass,
                    self._entry,
                    "Labeled Features State",
                    f"invalid {EVENT_FEATURE_SET} payload: {data!r}",
                )
                return

            self._apply_manual_override(tgt, scp, sid, ena, ts_f)
            clear_error(
                self.hass,
                "Labeled Features State",
                f"invalid {EVENT_FEATURE_SET} payload",
            )
            self.async_write_ha_state()
        except Exception as exc:  # noqa: BLE001
            handle_error(
                self.hass,
                self._entry,
                "Labeled Features State",
                f"{EVENT_FEATURE_SET} handler failed: {exc}",
                exc,
            )

    @callback
    def _handle_snapshot_set(self, event: Event) -> None:
        try:
            data = event.data or {}
            sname = str(data.get("snapshot_name") or "").strip()
            payload = data.get("payload")
            if not sname:
                handle_error(
                    self.hass,
                    self._entry,
                    "Labeled Features State",
                    f"invalid {EVENT_SNAPSHOT_SET} payload: {data!r}",
                )
                return
            if isinstance(payload, dict) and len(payload) > 0:
                self._snapshots[sname] = copy.deepcopy(payload)
            else:
                # Delete on empty/missing payload.
                self._snapshots.pop(sname, None)
            self.async_write_ha_state()
        except Exception as exc:  # noqa: BLE001
            handle_error(
                self.hass,
                self._entry,
                "Labeled Features State",
                f"{EVENT_SNAPSHOT_SET} handler failed: {exc}",
                exc,
            )

    # ---- Core rebuild logic --------------------------------------------

    def _process_state_changed(
        self, changed_eid: str, new_state: State | None, leader_entities: list[str]
    ) -> None:
        """Rebuild the leader entry and touched feature triples."""
        # 1. Update the leader entry (with skip-value carry-through).
        cv_raw = _current_value_for_state(new_state)
        prev_l = self._leaders.get(changed_eid, {})
        old_cv = prev_l.get("current_value", "")
        old_pv = prev_l.get("previous_value", "")
        if _is_skip_value(cv_raw):
            cv = old_cv or cv_raw
            cv_ts = prev_l.get(
                "last_changed_timestamp",
                new_state.last_changed.timestamp()
                if new_state is not None and new_state.last_changed is not None
                else dt_util.utcnow().timestamp(),
            )
            prev_cv_raw = old_pv
        else:
            cv = cv_raw
            cv_ts = (
                new_state.last_changed.timestamp()
                if new_state is not None and new_state.last_changed is not None
                else dt_util.utcnow().timestamp()
            )
            prev_cv_raw = old_cv if cv != old_cv else old_pv
        # Sanitize prev
        if _is_skip_value(str(prev_cv_raw or "")):
            prev_cv_final = ""
        else:
            prev_cv_final = prev_cv_raw
        self._leaders[changed_eid] = {
            "current_value": cv,
            "previous_value": prev_cv_final,
            "last_changed_timestamp": cv_ts,
        }

        # 2. Carry through / drop other leaders (orphan drop).
        for eid in list(self._leaders.keys()):
            if eid == changed_eid:
                continue
            if eid not in leader_entities:
                del self._leaders[eid]

        # 3. Compute the triples map from every leader's labels. This runs
        # regardless of whether the current tick is a skip-value tick so
        # orphan feature entries drop on every event, not just non-skip
        # ticks (matching the legacy YAML template's unconditional triples
        # build + carry-through loop).
        triples = self._compute_triples(leader_entities)

        # 4. Prune orphaned triples (no leader mapped AND not a manual override).
        self._prune_orphan_triples(triples)

        # If the changed value was skipped, don't rebuild triples for it.
        if _is_skip_value(cv_raw):
            return

        # 5. Recompute per-triple enabled for triples the changed leader contributes to.
        sensor_labels = self._sensor_labels()
        changed_labels = _labels_of(self.hass, entity_id=changed_eid)
        changed_domain = changed_eid.split(".", 1)[0]

        for key, leader_list in triples.items():
            if changed_eid not in leader_list:
                continue
            fname, scope_val, scope_id_val = key.split("||", 2)
            mode = resolve_mode(sensor_labels, fname, scope_val)

            try:
                this_truth = eval_leader_truth(
                    changed_labels,
                    changed_domain,
                    cv,
                    prev_cv_final,
                    fname,
                    scope_val,
                )
            except Exception as exc:  # noqa: BLE001
                handle_error(
                    self.hass,
                    self._entry,
                    "Labeled Features State",
                    f"eval failed for {changed_eid}/{fname}/{scope_val}: {exc}",
                    exc,
                )
                continue

            if mode == "leader":
                new_enabled = this_truth
            else:
                values: list[bool] = []
                for other_eid in leader_list:
                    if other_eid == changed_eid:
                        values.append(this_truth)
                        continue
                    other_labels = _labels_of(self.hass, entity_id=other_eid)
                    other_st = self.hass.states.get(other_eid)
                    other_cv = _current_value_for_state(other_st)
                    other_prev = self._leaders.get(other_eid, {}).get(
                        "previous_value", ""
                    )
                    try:
                        ot = eval_leader_truth(
                            other_labels,
                            other_eid.split(".", 1)[0],
                            other_cv,
                            other_prev,
                            fname,
                            scope_val,
                        )
                    except Exception as exc:  # noqa: BLE001
                        handle_error(
                            self.hass,
                            self._entry,
                            "Labeled Features State",
                            f"eval failed for {other_eid}/{fname}/{scope_val}: {exc}",
                            exc,
                        )
                        ot = False
                    values.append(ot)
                new_enabled = fold_triple(mode, values)

            prev_entry = (
                self._features.get(fname, {}).get(scope_val, {}).get(scope_id_val, {})
            )
            prev_enabled = prev_entry.get("enabled")
            prev_ts = prev_entry.get("last_changed_timestamp", cv_ts)
            is_button_leader = changed_domain in ("event", "button")
            flipped = (prev_enabled is None) or (prev_enabled != new_enabled) or is_button_leader
            new_ts = cv_ts if flipped else prev_ts

            self._features.setdefault(fname, {}).setdefault(scope_val, {})[scope_id_val] = {
                "enabled": bool(new_enabled),
                "mode": mode,
                "last_changed_timestamp": new_ts,
                "triggering_leader": changed_eid,
            }

    def _compute_triples(self, leader_entities: list[str]) -> dict[str, list[str]]:
        """Return `{fname||scope||scope_id: [leader_entity_ids]}`."""
        ent_reg = er.async_get(self.hass)
        out: dict[str, list[str]] = {}
        for eid in leader_entities:
            ent = ent_reg.async_get(eid)
            if ent is None:
                continue
            aid = ent.area_id or ""
            if not aid:
                dev_reg = dr.async_get(self.hass)
                if ent.device_id:
                    dev = dev_reg.async_get(ent.device_id)
                    if dev is not None and dev.area_id:
                        aid = dev.area_id
            fid = _floor_id_for_area(self.hass, aid) if aid else ""
            for lbl in _labels_of(self.hass, entity_id=eid):
                parsed = parse_leader_label(lbl)
                if parsed is None:
                    continue
                scope_val, fname = parsed
                if scope_val == SCOPE_AREA:
                    scope_id_val = aid
                    if not scope_id_val:
                        continue
                elif scope_val == SCOPE_FLOOR:
                    scope_id_val = fid
                    if not scope_id_val:
                        continue
                else:
                    # global scope uses '' scope_id
                    scope_id_val = ""
                key = f"{fname}||{scope_val}||{scope_id_val}"
                lst = out.setdefault(key, [])
                if eid not in lst:
                    lst.append(eid)
        return out

    def _prune_orphan_triples(self, triples: dict[str, list[str]]) -> None:
        """Drop feature entries that have no leader AND aren't manual overrides."""
        for fname in list(self._features.keys()):
            scopes_map = self._features[fname]
            if not isinstance(scopes_map, dict):
                del self._features[fname]
                continue
            for scope_val in list(scopes_map.keys()):
                sids = scopes_map[scope_val]
                if not isinstance(sids, dict):
                    del scopes_map[scope_val]
                    continue
                for sid_val in list(sids.keys()):
                    entry = sids[sid_val]
                    if not isinstance(entry, dict):
                        del sids[sid_val]
                        continue
                    key = f"{fname}||{scope_val}||{sid_val}"
                    has_leader = key in triples
                    is_manual = entry.get("triggering_leader", "") == ""
                    if not has_leader and not is_manual:
                        del sids[sid_val]
                if not sids:
                    del scopes_map[scope_val]
            if not scopes_map:
                del self._features[fname]

    def _apply_manual_override(
        self, feature: str, scope: str, scope_id: str, enabled: bool, ts: float
    ) -> None:
        scope_map = self._features.setdefault(feature, {})
        sids = scope_map.setdefault(scope, {})
        prev_entry = sids.get(scope_id, {}) if isinstance(sids.get(scope_id), dict) else {}
        mode = prev_entry.get("mode", "leader")
        sids[scope_id] = {
            "enabled": bool(enabled),
            "mode": mode,
            "last_changed_timestamp": float(ts),
            "triggering_leader": "",
        }


# ─────────────────────────────────────────────────────────────────────────
# sensor.labeled_feature_areas_state
# ─────────────────────────────────────────────────────────────────────────


class LabeledFeatureAreasStateSensor(RestoreEntity, SensorEntity):
    """Native replacement for `sensor.labeled_feature_areas_state`."""

    _attr_should_poll = False
    _attr_state_class = SensorStateClass.MEASUREMENT
    _attr_native_unit_of_measurement = "areas"

    def __init__(
        self,
        entry: ConfigEntry,
        entity_id: str,
        instance_name: str,
    ) -> None:
        self._entry = entry
        self._attr_unique_id = f"{entry.entry_id}_areas_state"
        self.entity_id = entity_id
        self._attr_name = f"{instance_name} Areas State"
        self._label_map: dict[str, dict[str, Any]] = {}
        self._unsubs: list[Any] = []
        # Cached set of areas with the leader label (invalidated on registry events).
        self._area_leader_cache: set[str] | None = None

    async def async_added_to_hass(self) -> None:
        await super().async_added_to_hass()
        last = await self.async_get_last_extra_data()
        if last is not None:
            raw = last.as_dict() or {}
            self._label_map = _coerce_mapping(raw.get(STORAGE_KEY_LABEL_MAP))

        bus = self.hass.bus
        self._unsubs.append(
            bus.async_listen("label_registry_updated", self._handle_registry_event)
        )
        self._unsubs.append(
            bus.async_listen("area_registry_updated", self._handle_registry_event)
        )
        self._unsubs.append(
            bus.async_listen("floor_registry_updated", self._handle_registry_event)
        )
        self._unsubs.append(
            bus.async_listen(EVENT_HOMEASSISTANT_START, self._handle_ha_start)
        )

        # Initial rebuild.
        self._rebuild_label_map()
        self.async_write_ha_state()
        self.async_on_remove(self._teardown_listeners)

    @callback
    def _teardown_listeners(self) -> None:
        for un in self._unsubs:
            try:
                un()
            except Exception:  # noqa: BLE001
                pass
        self._unsubs.clear()

    @property
    def native_value(self) -> int:
        if self._area_leader_cache is None:
            self._area_leader_cache = set(_areas_with_label(self.hass, self._leader_label()))
        return len(self._area_leader_cache)

    @property
    def extra_state_attributes(self) -> dict[str, Any]:
        return {"label_map": copy.deepcopy(self._label_map)}

    @property
    def extra_restore_state_data(self) -> Any:
        from homeassistant.helpers.restore_state import ExtraStoredData

        payload = {STORAGE_KEY_LABEL_MAP: self._label_map}

        class _Data(ExtraStoredData):
            def as_dict(self_inner) -> dict[str, Any]:  # noqa: N805
                return copy.deepcopy(payload)

        return _Data()

    def _leader_label(self) -> str:
        return _entry_option(self._entry, CONF_LEADER_LABEL, DEFAULT_LEADER_LABEL)

    @callback
    def _handle_registry_event(self, event: Event) -> None:
        try:
            # Invalidate the area-leader cache so `native_value` and the
            # rebuild pick up fresh registry state.
            self._area_leader_cache = None
            self._rebuild_label_map()
            self.async_write_ha_state()
        except Exception as exc:  # noqa: BLE001
            handle_error(
                self.hass,
                self._entry,
                "Labeled Feature Areas State",
                f"registry event handler failed: {exc}",
                exc,
            )

    @callback
    def _handle_ha_start(self, event: Event) -> None:
        try:
            self._area_leader_cache = None
            self._rebuild_label_map()
            self.async_write_ha_state()
        except Exception as exc:  # noqa: BLE001
            handle_error(
                self.hass,
                self._entry,
                "Labeled Feature Areas State",
                f"homeassistant.start handler failed: {exc}",
                exc,
            )

    def _rebuild_label_map(self) -> None:
        """Rebuild `label_map` fresh from the registry."""
        new_map: dict[str, dict[str, Any]] = {}
        leader_label = self._leader_label()
        if self._area_leader_cache is None:
            self._area_leader_cache = set(_areas_with_label(self.hass, leader_label))
        gated_areas = list(self._area_leader_cache)
        for aid in gated_areas:
            try:
                area_labels = _labels_of(self.hass, area_id=aid)
                floor_id = _floor_id_for_area(self.hass, aid)
                for lbl in area_labels:
                    parsed = parse_provides_label(lbl)
                    if parsed is None:
                        continue
                    scope_val, fname = parsed
                    # Map raw scope enum
                    if scope_val == SCOPE_AREA:
                        scope_id_val = aid
                    elif scope_val == SCOPE_FLOOR:
                        if not floor_id:
                            handle_error(
                                self.hass,
                                self._entry,
                                "Labeled Feature Areas State",
                                f"floor-scoped Provides on area {aid} without a floor: {lbl!r}",
                            )
                            continue
                        scope_id_val = floor_id
                    else:
                        # 'none' scope: entity lives in the declaring area
                        scope_id_val = aid
                    # Look up Component override
                    pfx = scope_to_prefix(SCOPE_AREA if scope_val == SCOPE_AREA
                                          else SCOPE_FLOOR if scope_val == SCOPE_FLOOR
                                          else SCOPE_NONE)
                    component = "select"
                    for other in area_labels:
                        override = parse_component_override(other, fname, pfx)
                        if override is not None:
                            component = override
                            break
                    key = f"{scope_id_val}||{fname}"
                    if key in new_map:
                        # First-declaring-area wins on floor-dedup collisions.
                        continue
                    new_map[key] = {
                        "scope_id": scope_id_val,
                        "label": fname,
                        "scope": scope_val,
                        "component": component,
                        "declaring_area_id": aid,
                        "label_data": {
                            "scope": scope_val,
                            "scope_id": scope_id_val,
                            "component": component,
                            "declaring_area_id": aid,
                        },
                    }
            except Exception as exc:  # noqa: BLE001
                handle_error(
                    self.hass,
                    self._entry,
                    "Labeled Feature Areas State",
                    f"failed to parse labels for area {aid}: {exc}",
                    exc,
                )
                continue
        self._label_map = new_map


# ─────────────────────────────────────────────────────────────────────────
# Coercion helper (legacy-safe mapping)
# ─────────────────────────────────────────────────────────────────────────


def _coerce_mapping(value: Any) -> dict[str, Any]:
    """Defensive coercion: legacy/corrupt restore payloads → empty dict."""
    if isinstance(value, dict):
        return value
    return {}
