"""Actions for the Labeled Features integration.

Native validated write paths into the default (suffix-less) instance:

  labeled_features.set_feature  — write a manual override into `features`
  labeled_features.set_snapshot — write/clear a `snapshots` entry
  labeled_features.handle_error — route an error through the error tiers
    (field-compatible with the legacy script.labeled_feature_error_mode)

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging

import voluptuous as vol

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant, ServiceCall
from homeassistant.exceptions import ServiceValidationError
from homeassistant.helpers import config_validation as cv
from homeassistant.util import dt as dt_util

from .const import (
    CONF_SUFFIX,
    DEFAULT_ALERT_SEVERITY,
    DEFAULT_ERROR_MODE,
    DOMAIN,
    ERROR_MODES,
    SCOPE_AREA,
    SCOPE_FLOOR,
    SCOPE_GLOBAL,
    SERVICE_HANDLE_ERROR,
    SERVICE_SET_FEATURE,
    SERVICE_SET_SNAPSHOT,
    SEVERITIES,
)
from .error_handler import async_route_error

_LOGGER = logging.getLogger(__name__)

SET_FEATURE_SCHEMA = vol.Schema(
    {
        vol.Required("target_feature"): cv.string,
        vol.Optional("scope", default=SCOPE_GLOBAL): vol.In(
            [SCOPE_AREA, SCOPE_FLOOR, SCOPE_GLOBAL]
        ),
        vol.Optional("scope_id", default=""): cv.string,
        vol.Optional("enabled", default=True): cv.boolean,
    }
)

SET_SNAPSHOT_SCHEMA = vol.Schema(
    {
        vol.Required("snapshot_name"): cv.string,
        vol.Optional("payload", default=dict): dict,
    }
)

HANDLE_ERROR_SCHEMA = vol.Schema(
    {
        vol.Optional("error_mode", default=DEFAULT_ERROR_MODE): vol.In(ERROR_MODES),
        vol.Required("message"): cv.string,
        vol.Optional("source", default="Labeled Features"): cv.string,
        vol.Optional("severity", default=DEFAULT_ALERT_SEVERITY): vol.In(SEVERITIES),
    }
)


def _loaded_entries(hass: HomeAssistant) -> dict[str, str]:
    """Map of loaded entry_id -> suffix (domain-level routing table)."""
    return hass.data.setdefault(DOMAIN, {}).setdefault("entries", {})


def get_default_entry(hass: HomeAssistant) -> ConfigEntry | None:
    """Return the loaded suffix-less (production) instance's entry."""
    for entry_id, suffix in _loaded_entries(hass).items():
        if suffix == "" and (
            entry := hass.config_entries.async_get_entry(entry_id)
        ) is not None:
            return entry
    return None


def get_any_entry(hass: HomeAssistant) -> ConfigEntry | None:
    """Return any loaded instance's entry (default first)."""
    if (entry := get_default_entry(hass)) is not None:
        return entry
    for entry_id in _loaded_entries(hass):
        if (entry := hass.config_entries.async_get_entry(entry_id)) is not None:
            return entry
    return None


async def _handle_set_feature(call: ServiceCall) -> None:
    """Write a manual override into the default instance's features."""
    hass = call.hass
    if (entry := get_default_entry(hass)) is None:
        raise ServiceValidationError(
            translation_domain=DOMAIN,
            translation_key="no_default_instance",
        )
    entry.runtime_data.features_coordinator.apply_manual(
        {
            "target_feature": call.data["target_feature"].strip(),
            "scope": call.data["scope"],
            "scope_id": str(call.data["scope_id"]),
            "enabled": call.data["enabled"],
            "timestamp": dt_util.utcnow().timestamp(),
        }
    )


async def _handle_set_snapshot(call: ServiceCall) -> None:
    """Write/clear a snapshot entry in the default instance."""
    hass = call.hass
    if (entry := get_default_entry(hass)) is None:
        raise ServiceValidationError(
            translation_domain=DOMAIN,
            translation_key="no_default_instance",
        )
    entry.runtime_data.features_coordinator.apply_snapshot(
        snapshot_name=call.data["snapshot_name"].strip(),
        payload=call.data["payload"],
    )


async def _handle_handle_error(call: ServiceCall) -> None:
    """Route an error through the error tiers (legacy script compat)."""
    hass = call.hass
    if (entry := get_any_entry(hass)) is None:
        _LOGGER.warning(
            "%s: %s (no labeled_features instance loaded)",
            call.data["source"],
            call.data["message"],
        )
        return
    await async_route_error(
        hass,
        entry,
        key="service",
        message=call.data["message"],
        source=call.data["source"],
        severity=call.data["severity"],
        mode=call.data["error_mode"],
    )


def async_register_services(hass: HomeAssistant) -> None:
    """Register the domain actions (idempotent)."""
    if hass.services.has_service(DOMAIN, SERVICE_SET_FEATURE):
        return
    hass.services.async_register(
        DOMAIN, SERVICE_SET_FEATURE, _handle_set_feature, schema=SET_FEATURE_SCHEMA
    )
    hass.services.async_register(
        DOMAIN,
        SERVICE_SET_SNAPSHOT,
        _handle_set_snapshot,
        schema=SET_SNAPSHOT_SCHEMA,
    )
    hass.services.async_register(
        DOMAIN,
        SERVICE_HANDLE_ERROR,
        _handle_handle_error,
        schema=HANDLE_ERROR_SCHEMA,
    )


def async_unregister_services(hass: HomeAssistant) -> None:
    """Unregister the domain actions (last instance unloaded)."""
    for service in (SERVICE_SET_FEATURE, SERVICE_SET_SNAPSHOT, SERVICE_HANDLE_ERROR):
        hass.services.async_remove(DOMAIN, service)
