"""Service actions for the Labeled Features integration.

Both actions internally publish the same event names the sensor already
listens for so we have exactly one write path.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging
from typing import Any

import voluptuous as vol
from homeassistant.core import HomeAssistant, ServiceCall
from homeassistant.helpers import config_validation as cv
from homeassistant.util import dt as dt_util

from .const import (
    DOMAIN,
    EVENT_FEATURE_SET,
    EVENT_SNAPSHOT_SET,
    SCOPE_AREA,
    SCOPE_FLOOR,
    SCOPE_GLOBAL,
    SERVICE_SET_FEATURE,
    SERVICE_SET_SNAPSHOT,
)
from .error_handler import handle_error

_LOGGER = logging.getLogger(__name__)


SET_FEATURE_SCHEMA = vol.Schema(
    {
        vol.Required("target_feature"): vol.All(cv.string, vol.Length(min=1)),
        vol.Required("scope"): vol.In((SCOPE_AREA, SCOPE_FLOOR, SCOPE_GLOBAL)),
        vol.Required("scope_id"): cv.string,
        vol.Required("enabled"): cv.boolean,
    }
)

SET_SNAPSHOT_SCHEMA = vol.Schema(
    {
        vol.Required("snapshot_name"): vol.All(
            cv.string, vol.Match(r"^[A-Za-z_][A-Za-z0-9_]*$")
        ),
        vol.Required("payload"): vol.Schema({str: object}),
    }
)


async def _handle_set_feature(hass: HomeAssistant, call: ServiceCall) -> None:
    try:
        data = SET_FEATURE_SCHEMA(dict(call.data))
    except vol.Invalid as exc:
        handle_error(
            hass,
            None,
            "Labeled Features Services",
            f"invalid set_feature payload: {exc}",
            exc,
        )
        raise
    hass.bus.async_fire(
        EVENT_FEATURE_SET,
        {
            "target_feature": data["target_feature"],
            "scope": data["scope"],
            "scope_id": data["scope_id"],
            "enabled": data["enabled"],
            "timestamp": dt_util.utcnow().timestamp(),
        },
    )


async def _handle_set_snapshot(hass: HomeAssistant, call: ServiceCall) -> None:
    try:
        data = SET_SNAPSHOT_SCHEMA(dict(call.data))
    except vol.Invalid as exc:
        handle_error(
            hass,
            None,
            "Labeled Features Services",
            f"invalid set_snapshot payload: {exc}",
            exc,
        )
        raise
    hass.bus.async_fire(
        EVENT_SNAPSHOT_SET,
        {
            "snapshot_name": data["snapshot_name"],
            "payload": data["payload"],
        },
    )


def async_register_services(hass: HomeAssistant) -> None:
    """Register `labeled_features.set_feature` and `set_snapshot` once per HA lifetime."""
    if hass.services.has_service(DOMAIN, SERVICE_SET_FEATURE):
        return

    async def _feature_wrapper(call: ServiceCall) -> None:
        await _handle_set_feature(hass, call)

    async def _snapshot_wrapper(call: ServiceCall) -> None:
        await _handle_set_snapshot(hass, call)

    hass.services.async_register(
        DOMAIN, SERVICE_SET_FEATURE, _feature_wrapper, schema=SET_FEATURE_SCHEMA
    )
    hass.services.async_register(
        DOMAIN, SERVICE_SET_SNAPSHOT, _snapshot_wrapper, schema=SET_SNAPSHOT_SCHEMA
    )


def async_unregister_services(hass: HomeAssistant) -> None:
    """Remove the services (called when the last config entry is unloaded)."""
    for name in (SERVICE_SET_FEATURE, SERVICE_SET_SNAPSHOT):
        if hass.services.has_service(DOMAIN, name):
            hass.services.async_remove(DOMAIN, name)
