"""Services for Labeled Features.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import Any

import voluptuous as vol
from homeassistant.core import HomeAssistant, ServiceCall
from homeassistant.helpers import config_validation as cv
from homeassistant.util import dt as dt_util

from .const import (
    DOMAIN,
    EVENT_LABELED_FEATURE_SET,
    EVENT_LABELED_FEATURE_SNAPSHOT_SET,
)


async def _handle_labeled_feature_set(call: ServiceCall) -> None:
    """Handle labeled_feature_set service call."""
    target_feature = call.data.get("target_feature", "").strip()
    scope = call.data.get("scope", "").lower().strip()
    scope_id = str(call.data.get("scope_id", ""))
    enabled = bool(call.data.get("enabled", False))

    if not target_feature or scope not in ("area", "floor", "global"):
        return

    call.hass.bus.async_fire(
        EVENT_LABELED_FEATURE_SET,
        {
            "target_feature": target_feature,
            "scope": scope,
            "scope_id": scope_id,
            "enabled": enabled,
            "timestamp": dt_util.now().timestamp(),
        },
    )


async def _handle_labeled_feature_snapshot_set(call: ServiceCall) -> None:
    """Handle labeled_feature_snapshot_set service call."""
    snapshot_name = call.data.get("snapshot_name", "").strip()
    payload = call.data.get("payload")

    if not snapshot_name:
        return

    call.hass.bus.async_fire(
        EVENT_LABELED_FEATURE_SNAPSHOT_SET,
        {
            "snapshot_name": snapshot_name,
            "payload": payload if isinstance(payload, dict) else {},
            "timestamp": dt_util.now().timestamp(),
        },
    )


def _build_set_feature_schema() -> vol.Schema:
    """Return schema for labeled_feature_set service."""
    return vol.Schema(
        {
            vol.Required("target_feature"): cv.string,
            vol.Required("scope"): vol.In(["area", "floor", "global"]),
            vol.Optional("scope_id", default=""): cv.string,
            vol.Required("enabled"): vol.Boolean(),
        }
    )


def _build_set_snapshot_schema() -> vol.Schema:
    """Return schema for labeled_feature_snapshot_set service."""
    return vol.Schema(
        {
            vol.Required("snapshot_name"): cv.string,
            vol.Required("payload"): dict,
        }
    )


async def async_setup_services(hass: HomeAssistant) -> None:
    """Set up all services for this integration."""
    hass.services.async_register(
        DOMAIN,
        "labeled_feature_set",
        _handle_labeled_feature_set,
        schema=_build_set_feature_schema(),
    )
    hass.services.async_register(
        DOMAIN,
        "labeled_feature_snapshot_set",
        _handle_labeled_feature_snapshot_set,
        schema=_build_set_snapshot_schema(),
    )


async def async_unsetup_services(hass: HomeAssistant) -> None:
    """Unregister all services."""
    if hass.services.has_service(DOMAIN, "labeled_feature_set"):
        hass.services.async_remove(DOMAIN, "labeled_feature_set")
    if hass.services.has_service(DOMAIN, "labeled_feature_snapshot_set"):
        hass.services.async_remove(DOMAIN, "labeled_feature_snapshot_set")